mongodb/specifications

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
@ajdavis please review
Instead of marking a whole topology stale, now only a single server gets check and only after "not master".  The rest of the time, the usual heartbeatFrequencyMS timeout or server selection failure governs full cluster scans.
> SPEC-166 remove stale; add server check on single-thread not-master

- source/index-management.rst
https://jira.mongodb.org/browse/SPEC-195
> SPEC-195: Legacy index creation must use write concern w:1

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-255
> SPEC-255: insertMany should throw BulkWriteException

- source/connection-string/connection-string-spec.rst
- source/connection-string/tests/Makefile
- source/connection-string/tests/README.rst
- source/connection-string/tests/invalid-uris.json
- source/connection-string/tests/invalid-uris.yml
- source/connection-string/tests/valid-auth.json
- source/connection-string/tests/valid-auth.yml
- source/connection-string/tests/valid-host_identifiers.json
- source/connection-string/tests/valid-host_identifiers.yml
- source/connection-string/tests/valid-options.json
- source/connection-string/tests/valid-options.yml
- source/connection-string/tests/valid-unix_socket-absolute.json
- source/connection-string/tests/valid-unix_socket-absolute.yml
- source/connection-string/tests/valid-unix_socket-relative.json
- source/connection-string/tests/valid-unix_socket-relative.yml
- source/connection-string/tests/valid-warnings.json
- source/connection-string/tests/valid-warnings.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/59)
> Added connection-string specification

- source/read-write-concern/read-write-concern.rst
Clarify title for String based implementations of ReadConcern
Fix CRUD spec links
> Read Write Concern fixes

- source/driver-bulk-update.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/73)
> Clarify writeConcernErrors reporting

- source/crud/crud.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/76)
> Typos in comments about bypassDocumentValidation

- source/command-monitoring/tests/find.json
- source/command-monitoring/tests/find.yml
64-bit batchSize, skip, limit in command monitor tests.
> 64-bit batchSize, skip, limit in command monitor tests.

- source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
- source/server-discovery-and-monitoring/tests/monitoring/README.rst
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_no_primary.json
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_no_primary.yml
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_primary.json
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_primary.yml
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_removal.json
- source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_removal.yml
- source/server-discovery-and-monitoring/tests/monitoring/required_replica_set.json
- source/server-discovery-and-monitoring/tests/monitoring/required_replica_set.yml
- source/server-discovery-and-monitoring/tests/monitoring/standalone.json
- source/server-discovery-and-monitoring/tests/monitoring/standalone.yml
This is the approved specification added as a sub-specification to the
original server discovery and monitoring specification.
> SPEC-222: SDAM Monitoring:

- README.rst
Adding licensing information to the repo.
> Update README.rst to include licensing info

- source/auth/auth.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/101)
> SPEC-254: added FAQ related to multiple credentials.

- source/crud/tests/README.rst
https://jira.mongodb.org/browse/SPEC-834
> SPEC-834: Clarify (in|ex)clusivity of maxServerVersion and minServerVersion

- source/connection-string/tests/README.rst
This looks like leftovers from before the spec was merged into this repo
> Remove outdate text

- source/collation/collation.rst
Affected commands should each be listed on their own line.
> minor: Markup fixes in API section

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-469
> SPEC-469: FAQ entry for save()'s omission from CRUD API

- source/crud/crud.rst
- source/crud/tests/write/findOneAndUpdate-arrayFilters.json
- source/crud/tests/write/findOneAndUpdate-arrayFilters.yml
- source/crud/tests/write/updateMany-arrayFilters.json
- source/crud/tests/write/updateMany-arrayFilters.yml
- source/crud/tests/write/updateOne-arrayFilters.json
- source/crud/tests/write/updateOne-arrayFilters.yml
This pull request updates the CRUD spec to detail the `arrayFilters` option and adds a few tests for it
> Add arrayFilters specification

- source/retryable-writes/retryable-writes.rst
- source/retryable-writes/tests/README.rst
- source/retryable-writes/tests/supported-multi-statement-failure.yml
- source/retryable-writes/tests/supported-multi-statement.yml
- source/retryable-writes/tests/supported-single-statement-failure.yml
- source/retryable-writes/tests/supported-single-statement.yml
- source/retryable-writes/tests/unsupported-multi-statement.yml
- source/retryable-writes/tests/unsupported-single-statement.yml
- source/retryable-writes/tests/unsupported-write-commands.yml
- source/retryable-writes/tests/unsupported-write-concern.yml
https://jira.mongodb.org/browse/SPEC-857
> SPEC-857: Retryable Writes

- source/crud/tests/write/findOneAndUpdate-arrayFilters.yml
- source/crud/tests/write/updateMany-arrayFilters.yml
- source/crud/tests/write/updateOne-arrayFilters.json
- source/crud/tests/write/updateOne-arrayFilters.yml
When running the Ruby tests for the arrayFilters updates, I found a few mistakes.
> Fix mistakes in arrayFilters crud tests

- source/change-streams.rst
> refactor(change-streams): `lookup` => `updateLookup`

- source/change-streams.rst
> refactor(change-streams): add exception for "cursor not found" error

- source/enumerate-databases.rst
https://jira.mongodb.org/projects/SPEC/issues/SPEC-865
> SPEC-865: Port database enumeration spec to reStructuredText

- source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-857
> SPEC-857: retryWrites is now a MongoClient option

- source/change-streams.rst
> refactor(change-streams): remove `desired user experience` example

- README.rst
- source/Makefile
- source/server-discovery-and-monitoring/tests/rs/primary_mismatched_me.yml
- source/server-discovery-and-monitoring/tests/rs/secondary_mismatched_me.yml
The old tool wasn't quite usable, this one is a seamless replacement.  Additionally, it caught two cases where we had erroneously named YAML files with JSON content.
> Update the tool we use to generate JSON from YAML

- source/retryable-writes/tests/README.rst
- source/retryable-writes/tests/supported-multi-statement.json
- source/retryable-writes/tests/supported-multi-statement.yml
https://jira.mongodb.org/browse/SPEC-940
> SPEC-940: Update tests for onPrimaryTransactionalWrite fail point

- source/crud/tests/write/bulkWrite-arrayFilters.json
- source/crud/tests/write/bulkWrite-arrayFilters.yml
Jira: https://jira.mongodb.org/browse/SPEC-958
> SPEC-958 Use standard bulkWrite format for arrayFilters tests.

- source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-963
> SPEC-963: Rename txnNum to txnNumber and note 64-bit requirement

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-939
> SPEC-939: Split UpdateOptions and ReplaceOptions

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-843
> SPEC-843: Prohibit empty insertMany() and bulkWrite() ops

- source/retryable-writes/tests/README.rst
https://jira.mongodb.org/browse/SPEC-959
/cc @visemet since I can't seem to tag you as a reviewer.
> SPEC-959: Replica set failover test for retryable writes

- source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-972
> SPEC-972: Clarify which second attempt errors may replace original

- source/find_getmore_killcursors_commands.rst
The logic tables in the spec were confusing and duplicative.  The same logic can be expressed much more concisely and clearly.
> SPEC-378 Clarify singleBatch, limit, and batchSize logic

- source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-979
https://jira.mongodb.org/browse/SPEC-980
This commit reorders sections to discuss support profiles before the implementation and pseudo-code.
Additionally, we discuss checking logicalSessionTimeoutMinutes when considering server support (SPEC-979).
> SPEC-980: Fall back to non-retryable for unsupported servers

- source/auth/auth.rst
* Remove the lazy authentication section
* Update Q & A regarding support for multiple credentials
* Add Q & A regarding support for lazy authentication
* Update minimum server version to 2.6
* Add Spec Version 1.3
> Updates to the authentication specification

- source/retryable-writes/tests/bulkWrite.json
- source/retryable-writes/tests/bulkWrite.yml
Jira: https://jira.mongodb.org/browse/SPEC-1001
This test runs 7 write commands, not 3.
> SPEC-1001 All commands are retried test should retry all commands.

- source/retryable-writes/tests/README.rst
https://jira.mongodb.org/browse/SPEC-898
> SPEC-898 prose test for split write batches

- source/server-selection/tests/server_selection/ReplicaSetNoPrimary/read/Primary.json
- source/server-selection/tests/server_selection/ReplicaSetNoPrimary/read/Primary.yml
- source/server-selection/tests/server_selection/ReplicaSetWithPrimary/read/Primary.json
- source/server-selection/tests/server_selection/ReplicaSetWithPrimary/read/Primary.yml
> refactor(server-selection): tag sets cannot be used with `primary`

- source/command-monitoring/command-monitoring.rst
[SPEC-535](https://jira.mongodb.org/browse/SPEC-535)
> refactor(command-monitoring): clarify what requestId should be

- source/gridfs/gridfs-spec.rst
This also defines a transitional `disableMD5` to turn it off if needed
until the deprecated feature is removed.
> SPEC-1022 Deprecate GridFS MD5

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-1025
> SPEC-1025: batchSize for find/aggregate should also apply to getMore

- source/sessions/driver-sessions.rst
Perl contractors were surprised there wasn't a test that the correct session
was sent.  I expanded that to a full implicit/explicit test.
> Add implicit/explicit session tests

- source/auth/auth.rst
Also adds the mechanism negotiation process for MongoDB 4.0.
> WRITING-2509 Add SCRAM-SHA-256 to auth spec

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
I think adding a term should be enough to clear up the ambiguity.
> Clarify what a "network error" is

- source/retryable-writes/retryable-writes.rst
> SPEC-1044: Clarify that retryable writes may fail with FCV 3.4 shard

- source/change-streams.rst
This should have the same note as `batchSize` and `collation`.
> Note that maxAwaitTimeMS is an aggregate option

- source/change-streams.rst
- source/retryable-writes/retryable-writes.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Asked Spencer for a recommendation for someone from DS to review as well.
> SPEC-1051 retryable, resumable, and SDAMnable errors

- source/gridfs/tests/upload.json
- source/gridfs/tests/upload.yml
Added missing test for the disableMD5 flag.
> Add test for "disableMD5" flag

- source/retryable-writes/tests/bulkWrite.json
- source/retryable-writes/tests/bulkWrite.yml
https://jira.mongodb.org/browse/SPEC-1064
> SPEC-1064: Fix insertedIds index in expected bulk write result

- source/server-discovery-and-monitoring/tests/rs/normalize_case_me.json
- source/server-discovery-and-monitoring/tests/rs/normalize_case_me.yml
> Adding mixed case hostname tests in SDAM

- source/retryable-writes/retryable-writes.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring-tests.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Props to Shane for hashing out the details.
> SPEC-1063 writeConcernErrors are retryable

- source/transactions/tests/read-pref.json
- source/transactions/tests/read-pref.yml
- source/transactions/tests/reads.json
- source/transactions/tests/reads.yml
- source/transactions/tests/run-command.json
- source/transactions/tests/run-command.yml
- source/transactions/tests/transaction-options.json
- source/transactions/tests/transaction-options.yml
Tested on  latest version 4.1.0-141-g65bfd4b.
> SPEC-1101 Count is no longer supported in transactions

- source/causal-consistency/causal-consistency.rst
- source/change-streams/change-streams.rst
> Updates spec to detail acquisition of startAtOperationTime for ChangeStreams

- source/wireversion-featurelist.rst
See: https://docs.mongodb.com/manual/reference/command/explain/
> Explains supports distinct and findAndModify since 3.2

- source/crud/crud.rst
- source/crud/tests/write/updateMany-arrayFilters.json
- source/crud/tests/write/updateMany-arrayFilters.yml
- source/crud/tests/write/updateOne-arrayFilters.json
- source/crud/tests/write/updateOne-arrayFilters.yml
https://jira.mongodb.org/browse/SPEC-1135
> SPEC-1135: Add upsertedCount to UpdateResult

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
These sections are somewhat redundant and should be closer together. I solved the second problem.
> refactor(sdam): reorder network error sections

- source/change-streams/change-streams.rst
SERVER-35029 added a "databaseDrop" notification.
> Add dropDatabase to change stream operationType

- source/crud/tests/write/bulkWrite-collation.json
- source/crud/tests/write/bulkWrite-collation.yml
https://jira.mongodb.org/browse/SPEC-900
@ShaneHarvey, @saghm: Please test in Python and Ruby when you get a chance. I've tested these with PHP and Swift.
> SPEC-900: Collation tests for bulkWrite()

- source/server-discovery-and-monitoring/tests/README.rst
> Add maxSetVersion and maxElectionId to sdam tests readme

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Without this test an implementation can publish server description & topology change events on each ismaster response, even when there are no changes between the ismaster response being processed and the previous one.
https://jira.mongodb.org/browse/RUBY-1557?
> Define SDAM server description equality and specify that equal descriptions do not run SDAM flow

- source/crud/crud.rst
- source/crud/tests/README.rst
- source/crud/tests/db/db-aggregate.json
- source/crud/tests/db/db-aggregate.yml
[SPEC-884](https://jira.mongodb.org/browse/SPEC-884)
> SPEC-884 add database-level aggregation

- source/change-streams/change-streams.rst
This solves the problem of resuming a change stream with a potentially very old resume token. This can happen if the change stream has not received any events in a long time. And consequences of this are: (1) the oplog may have already rolled over and (2) loading a very old oplog entry can be a huge performance hit.
In 4.2, the query team is planning to have responses of aggregate and getMore include a minPromisedResumeToken. This will represent a resume token greater or equal to the last document returned. When not in the middle of a returning documents in a batch, a change stream should resume using the most recent minPromisedResumeToken.
This commit does not include tests. Tests will be added after the corresponding server work is done.
> SPEC-1122 Handle postBatchResumeToken in change streams.

- source/crud/tests/db/db-aggregate.json
- source/crud/tests/db/db-aggregate.yml
> Added min server version to db-aggregate tests

- source/transactions-convenient-api/transactions-convenient-api.rst
https://jira.mongodb.org/browse/WRITING-3159
https://jira.mongodb.org/browse/DRIVERS-556
> WRITING-3159: Convert Conventient Transaction API spec to RST

- source/transactions-convenient-api/tests/commit-retry.json
- source/transactions-convenient-api/tests/commit-retry.yml
- source/transactions-convenient-api/tests/commit-writeconcernerror.json
- source/transactions-convenient-api/tests/commit-writeconcernerror.yml
https://jira.mongodb.org/browse/SPEC-1185
> SPEC-1185: Remove skips and add wtimeout in withTransaction tests

- source/transactions-convenient-api/tests/README.rst
- source/transactions-convenient-api/tests/callback-aborts.json
- source/transactions-convenient-api/tests/callback-aborts.yml
- source/transactions-convenient-api/tests/callback-commits.json
- source/transactions-convenient-api/tests/callback-commits.yml
- source/transactions-convenient-api/tests/callback-retry.json
- source/transactions-convenient-api/tests/callback-retry.yml
- source/transactions-convenient-api/tests/commit-retry.json
- source/transactions-convenient-api/tests/commit-retry.yml
- source/transactions-convenient-api/tests/commit-transienttransactionerror-4.2.json
- source/transactions-convenient-api/tests/commit-transienttransactionerror-4.2.yml
- source/transactions-convenient-api/tests/commit-transienttransactionerror.json
- source/transactions-convenient-api/tests/commit-transienttransactionerror.yml
- source/transactions-convenient-api/tests/commit-writeconcernerror.json
- source/transactions-convenient-api/tests/commit-writeconcernerror.yml
- source/transactions-convenient-api/tests/commit.json
- source/transactions-convenient-api/tests/commit.yml
- source/transactions-convenient-api/tests/transaction-options.json
- source/transactions-convenient-api/tests/transaction-options.yml
- source/transactions-convenient-api/transactions-convenient-api.rst
The previous spec tests weren't consistent with the test format. Thanks to @mbroadst for pointing that out.
Note: this may break your existing test harness.
> Nest withTransaction's callback under operation.arguments

- source/transactions-convenient-api/transactions-convenient-api.rst
Related to: https://github.com/mongodb/specifications/pull/462
> Use shorter name for options argument and add changelog template

- source/connection-monitoring-and-pooling/tests/connection-must-have-id.json
- source/connection-monitoring-and-pooling/tests/connection-must-have-id.yml
- source/connection-monitoring-and-pooling/tests/connection-must-order-ids.json
- source/connection-monitoring-and-pooling/tests/connection-must-order-ids.yml
- source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.json
- source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.yml
Just a couple of small changes that I needed to get the tests passing
> CMAP test fixes

- source/transactions-convenient-api/tests/README.rst
- source/transactions-convenient-api/tests/commit-retry.yml
- source/transactions-convenient-api/tests/commit-transienttransactionerror-4.2.yml
- source/transactions-convenient-api/tests/commit-transienttransactionerror.yml
Just some small test cleanup. There are no functional changes, hence the absence of any JSON files in the diff.
> Convenient API spec test cleanup

- source/transactions-convenient-api/tests/commit-writeconcernerror.json
- source/transactions-convenient-api/tests/commit-writeconcernerror.yml
- source/transactions-convenient-api/transactions-convenient-api.rst
https://jira.mongodb.org/browse/SPEC-1208
> SPEC-1208: withTransaction() should retry commits after a wtimeout

- source/crud/tests/v2/aggregate-out-readConcern.json
- source/crud/tests/v2/aggregate-out-readConcern.yml
- source/out-aggregation-pipeline-operator.rst
- source/read-write-concern/read-write-concern.rst
> Spec 1153: add read concern support to aggregation $out

- source/crud/crud.rst
[SPEC-1209](https://jira.mongodb.com/browse/SPEC-1209)
> SPEC-1209 Mark the request field of BulkWriteError as NOT REQUIRED

- source/retryable-reads/tests/mapReduce.json
- source/retryable-reads/tests/mapReduce.yml
Just linking to https://jira.mongodb.org/browse/DRIVERS-405
> DRIVERS-405 Fix mapReduce retryable reads test

- source/transactions/tests/mongos-recovery-token.json
- source/transactions/tests/mongos-recovery-token.yml
- source/transactions/tests/pin-mongos.json
- source/transactions/tests/pin-mongos.yml
~~No functional changes here~~, just trying to improve these confusing and hard to read comments.
Minor change here to actually increase heartbeatFrequencyMS higher than the default 10 seconds.
> SPEC-1168 Update comments in transaction unpinning spec test

- source/transactions/tests/README.rst
Jira: https://jira.mongodb.org/browse/SPEC-1234
This is just documenting what is already true. Tests that set `useMultipleMongoses: true` use `targetedFailPoint` and never use the higher level `failPoint` so drivers don't need to run the fail point on all mongoses.
> SPEC-1234 useMultipleMongoses: true and non-targeted fail points are mutually exclusive

- source/connection-string/connection-string-spec.rst
https://jira.mongodb.org/browse/SPEC-1212
> SPEC-1212: Require drivers to document option precedence rules

- README.rst
Per driver leads discussion, opening a PR to put driver mantras in the README in the specs repo.
> Add driver mantras section to README

- source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-1213
Bumping the minor version since we're changing MAY to MUST NOT here, although I don't expect driver changes will be needed (per @vincentkam's feedback cited in the JIRA issue description).
> SPEC-1213: Clarify rules for resending wire protocol messages

- source/change-streams/change-streams.rst
Also add spacing to doc blocks.
> Clarify that startAfter is a $changeStream option

- source/change-streams/change-streams.rst
- source/change-streams/tests/README.rst
- source/change-streams/tests/change-streams.json
- source/change-streams/tests/change-streams.yml
> Change Streams: Ensure that getMore right after a resume is retried

- source/enumerate-collections.rst
Jira: https://jira.mongodb.org/browse/SPEC-1258
> SPEC-1258 Naming guidance for listCollectionNames/listMongoCollections

- source/transactions/tests/README.rst
Jira: https://jira.mongodb.org/browse/SPEC-1245
> SPEC-1245 Workaround StaleDbVersion error with distinct

- source/transactions/tests/mongos-pin-auto-tests.py
- source/transactions/tests/mongos-pin-auto.json
- source/transactions/tests/mongos-pin-auto.yml
- source/transactions/tests/pin-mongos.json
- source/transactions/tests/pin-mongos.yml
We forgot to update these two tests in the last PR.
> SPEC-1279 Send recoveryToken on abort test fixes

- source/connections-survive-step-down/tests/README.rst
Fix not master error code
Test interrupted at shutdown also clears the pool
DRIVERS-552
> Connection survive step down prose test tweaks

- source/crud/tests/v2/db-aggregate.json
- source/crud/tests/v2/db-aggregate.yml
Closes [SPEC-1319](https://jira.mongodb.org/browse/SPEC-1319)
> SPEC-1319 Database-level aggregation should be tested on server versions 3.6+

- source/change-streams/tests/change-streams.json
- source/change-streams/tests/change-streams.yml
https://jira.mongodb.org/browse/SPEC-1322
> SPEC-1322: Fix result assertion in change stream spec test

- source/crud/tests/v2/updateWithPipelines.json
- source/crud/tests/v2/updateWithPipelines.yml
Closes [SPEC-1323](https://jira.mongodb.org/browse/SPEC-1323)
> SPEC-1323 Fix updateWithPipelines spec tests

- source/client-side-encryption/tests/badQueries.json
- source/client-side-encryption/tests/badQueries.yml
- source/client-side-encryption/tests/badQueries.yml.template
Noted in the follow-up ticket to add tests for all of $aggregate/$expr WRITING-3793.
> remove failing  test

- source/crud/tests/README.rst
- source/crud/tests/v2/aggregate-merge.yml
- source/crud/tests/v2/aggregate-out-readConcern.yml
- source/crud/tests/v2/bulkWrite-arrayFilters.yml
- source/crud/tests/v2/db-aggregate.yml
- source/crud/tests/v2/updateWithPipelines.yml
> feat: introduce `runOn` to the CRUDv2 tests

- source/auth/auth.rst
- source/auth/tests/connection-string.yml
- source/connection-string/connection-string-spec.rst
https://jira.mongodb.org/browse/SPEC-1313
> spec-1313 clarify username requirements for each auth mechanism

- .travis.yml
- source/auth/auth.rst
- source/benchmarking/benchmarking.rst
- source/causal-consistency/causal-consistency.rst
- source/client-side-encryption/tests/README.rst
- source/driver-bulk-update.rst
- source/find_getmore_killcursors_commands.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst
- source/transactions/tests/README.rst
Closes #501
Needs the TravisCI integration to be enabled on this repository in order to work.
Example of a successful build: https://travis-ci.org/prashantmital/specifications/builds/553562294
Example of a failing build: https://travis-ci.org/prashantmital/specifications/jobs/553555919
> Use TravisCI to perform a RST syntax check

- source/change-streams/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1308
> SPEC-1308: Clarify iteration for error and non-error tests

- source/client-side-encryption/tests/README.rst
Also reworks prose tests to be more prescriptive.
> SPEC-1337 [FLE] test explicit encryption with key alt name

- source/client-side-encryption/tests/README.rst
Add missing field to the schema document
> Fix prose test

- source/client-side-encryption/corpus/corpus-schema.json
- source/client-side-encryption/corpus/corpus.json
- source/client-side-encryption/tests/README.rst
Follow-up to https://github.com/mongodb/specifications/pull/606. I hadn't actually updated the schema or corpus, just the generation script.
> SPEC-1359 update corpus data (pt. 2)

- source/change-streams/tests/README.rst
Closes [SPEC-1360](https://jira.mongodb.org/browse/SPEC-1360).
> SPEC-1360 Remove unrealistic change stream prose tests

- source/client-side-encryption/corpus/corpus-encrypted.json
- source/client-side-encryption/corpus/corpus.json
- source/client-side-encryption/etc/generate-corpus.py
- source/client-side-encryption/etc/update-corpus.py
- source/client-side-encryption/etc/validate-corpus.py
- source/client-side-encryption/tests/README.rst
And update the steps to explicitly decrypt the expected corpus fields.
Validated with Java driver:
https://github.com/mongodb/mongo-java-driver/pull/519
> SPEC-1369 + SPEC-1368 add all padding lengths to corpus

- source/uri-options/uri-options.rst
https://jira.mongodb.org/browse/SPEC-1441
Bumped the minor version since this is a new addition to the table.
> SPEC-1441: Document retryReads URI option

- source/connections-survive-step-down/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1472
See: https://github.com/mongodb/specifications/pull/627#issuecomment-540612468
> SPEC-1472: Advise using separate client for serverStatus assertions

- source/connections-survive-step-down/tests/README.rst
Closes [SPEC-1393](https://jira.mongodb.org/browse/SPEC-1393)
> SPEC-1393 Connections survive primary step-down tests should always test for success

- source/crud/crud.rst
- source/crud/tests/v2/bulkWrite-update-hint.json
- source/crud/tests/v2/bulkWrite-update-hint.yml
- source/crud/tests/v2/replaceOne-hint.json
- source/crud/tests/v2/replaceOne-hint.yml
- source/crud/tests/v2/updateMany-hint.json
- source/crud/tests/v2/updateMany-hint.yml
- source/crud/tests/v2/updateOne-hint.json
- source/crud/tests/v2/updateOne-hint.yml
https://jira.mongodb.org/browse/SPEC-1334
Note: I wrote these tests blind, as I don't yet have a CRUD v2 test runner. I'd appreciate it if one of the reviewers could manually check them against their test runner.
> SPEC-1334: Hint option for update commands

- source/auth/auth.rst
To address [GODRIVER-1344](https://jira.mongodb.org/browse/GODRIVER-1344).
> SPEC-1301 Require auth on direct connections

- source/client-side-encryption/client-side-encryption.rst
Let me know if this warrants a version bump/entry to the changelog (I don't think it does, but I'll defer to reviewers).
> Some small FLE grammar/typo fixes

- source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
> Adds rationale for the deprecation of waitQueue(Size|Multiple)

- source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-1491
> SPEC-1491: Deprecate oplogReplay find option

- source/retryable-writes/retryable-writes.rst
- source/retryable-writes/tests/insertOne-serverErrors.json
- source/retryable-writes/tests/insertOne-serverErrors.yml
- Updated the list of errors
- Added a new test to insertOne-serverErrors tests
> SPEC-1296 Make ExceededTimeLimit retryable writes errors

- source/retryable-writes/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1573
> Drivers may skip MMAPv1 test on mongos

- source/ocsp-support/ocsp-support.rst
- source/ocsp-support/tests/README.rst
A collection of spec/test fixes that I made while implementing the spec. Feel free to suggest changes I may have missed.
> OCSP spec + test plan changes

- source/server-discovery-and-monitoring/tests/single/too_old_then_upgraded.json
- source/server-discovery-and-monitoring/tests/single/too_old_then_upgraded.yml
https://jira.mongodb.org/browse/SPEC-1586
> add spec test for incompatible server becoming compatible

- source/ocsp-support/tests/README.rst
Syncs the test plan with https://github.com/mongodb-labs/drivers-evergreen-tools/pull/86
> Add tests for OCSP delegates + ECDSA certs

- source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
https://jira.mongodb.org/browse/SPEC-1583
> SPEC-1583 Fix link to internal heading

- source/uri-options/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1600
> SPEC-1600: Update description of "valid" in uri-options test plan

- source/ocsp-support/ocsp-support.rst
Minor fix for rendering OCSP Support spec correctly on Github.
> Fix add whitespace correctly render 'Suggested OCSP Caching Behavior' section

- source/ocsp-support/ocsp-support.rst
- source/ocsp-support/tests/README.rst
- source/uri-options/tests/tls-options.json
- source/uri-options/tests/tls-options.yml
- source/uri-options/uri-options.rst
https://jira.mongodb.org/browse/SPEC-1595
> SPEC-1595: Add URI option to disable certificate revocation checking

- source/ocsp-support/tests/README.rst
See also: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/97
https://jira.mongodb.org/browse/SPEC-1587
> SPEC-1587 Update Windows + macOS stapled OCSP test plan

- source/ocsp-support/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1644
> SPEC-1644: Update OCSP ECDSA test plan

- source/ocsp-support/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1649
> SPEC-1679: Clarify OCSP mock responder setup

- source/bson-corpus/tests/top.json
> Fix invalid JSON in top.json parse error cases

- source/max-staleness/max-staleness-tests.rst
Validated in libmongoc: https://jira.mongodb.org/browse/CDRIVER-2985
> SPEC-1677 add wait step to 'Parse lastWriteDate' test

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
https://jira.mongodb.org/browse/DRIVERS-1280
https://jira.mongodb.org/browse/SPEC-1701
> SPEC-1701: Clarify reasoning behind how SDAM determines if a topologyVersion is stale

- source/server-discovery-and-monitoring/server-monitoring.rst
Jira: [SPEC-1690](https://jira.mongodb.org/browse/SPEC-1690)
> SPEC-1690 Add average RTT tracking to server monitoring pseudocode

- source/connections-survive-step-down/tests/README.rst
- source/server-discovery-and-monitoring/tests/README.rst
Jira: [SPEC-1708](https://jira.mongodb.org/browse/SPEC-1708)
> SPEC-1708 Retry replSetStepDown in SDAM and connection failover tests

- source/crud/tests/v2/bulkWrite-update-validation.json
- source/crud/tests/v2/bulkWrite-update-validation.yml
- source/crud/tests/v2/replaceOne-validation.json
- source/crud/tests/v2/replaceOne-validation.yml
- source/crud/tests/v2/updateMany-validation.json
- source/crud/tests/v2/updateMany-validation.yml
- source/crud/tests/v2/updateOne-validation.json
- source/crud/tests/v2/updateOne-validation.yml
https://jira.mongodb.org/browse/SPEC-1710
Confirmed that tests pass in PHPLIB.
> SPEC-1710: Test update/replacement validation

- source/atlas-data-lake-testing/tests/README.rst
- source/atlas-data-lake-testing/tests/aggregate.json
- source/atlas-data-lake-testing/tests/aggregate.yml
- source/atlas-data-lake-testing/tests/count.json
- source/atlas-data-lake-testing/tests/count.yml
- source/atlas-data-lake-testing/tests/find.json
- source/atlas-data-lake-testing/tests/find.yml
- source/atlas-data-lake-testing/tests/getMore.json
- source/atlas-data-lake-testing/tests/getMore.yml
- source/atlas-data-lake-testing/tests/listCollections.json
- source/atlas-data-lake-testing/tests/listCollections.yml
- source/atlas-data-lake-testing/tests/listDatabases.json
- source/atlas-data-lake-testing/tests/listDatabases.yml
- source/atlas-data-lake-testing/tests/runCommand.json
- source/atlas-data-lake-testing/tests/runCommand.yml
https://jira.mongodb.org/browse/SPEC-1684
This PR includes a README for the tests provided. The tests cover all of the commands found in the scope as well as the commands used as arguments to `runCommand`. In addition, there are connectivity tests for SCRAM authentication.
> SPEC-1684: Testing Atlas Data Lake with Drivers

- source/atlas-data-lake-testing/tests/README.rst
https://jira.mongodb.org/browse/SPEC-1684
> SPEC-1684: Clarify that collection under test must not be dropped

- source/retryable-writes/retryable-writes.rst
- source/retryable-writes/tests/insertOne-serverErrors.json
- source/retryable-writes/tests/insertOne-serverErrors.yml
https://jira.mongodb.org/browse/SPEC-1747
> SPEC-1747 Specify error label in InsertOne test

- CODEOWNERS
Once this PR is merged, spec owners are automatically requested for reviews on pull requests that change their specs. This review is not necessary to merge the pull request yet, we're mainly testing to see if this feature can improve the review process.
> Add code owners file to automatically assign spec owners

- source/auth/auth.rst
@p-mongo, I'm tagging you here just in case you wanted to review the fix to your reported issue. Feel free to ignore.
> SPEC-1668 conflicting requirements for AWS creds

- README.rst
> Remove "in the future" section from README

- source/client-side-encryption/client-side-encryption.rst
Modernize terminology per a note from @mbroadst. No functional change.
> use allow-list in CSFLE

- source/unified-test-format/tests/valid-pass/poc-retryable-reads.yml
- source/unified-test-format/unified-test-format.rst
Note: test file changes do not affect generated JSON.
> Fix RST code block formatting and missing YAML references

- source/unified-test-format/unified-test-format.rst
> DRIVERS-1591 clarify comparison behaviour for version strings

- source/client-side-encryption/tests/README.rst
[SPEC-1791](https://jira.mongodb.org/browse/SPEC-1791)
Adds two new prose tests to verify that KMS TLS connections actually verify the KMS server's certs.
Current working implementation in Go is available on my branch [here](https://github.com/benjirewis/mongo-go-driver/tree/kmsTlsConnsVerification) with a patch of the new tests [here](https://spruce.mongodb.com/version/6041254b32f41736e9b916da/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). Note that I only test on Ubuntu. I _can_ run the tests on MacOS and Windows, but both lack certain dependencies that will have to be installed from a list I make in drivers-evergreen-tools; just let me know if I should add that functionality.
New tests make use of new features added to drivers evergreen tools …
> SPEC-1791 Add prose tests for KMS TLS cert verification

- source/unified-test-format/unified-test-format.rst
Depends on https://github.com/mongodb/specifications/pull/921
> Split out serverApi and clarifications for loop args

- source/server-discovery-and-monitoring/tests/errors/write_errors_ignored.json
- source/server-discovery-and-monitoring/tests/errors/write_errors_ignored.yml
Adds missing index property on WriteError
> DRIVERS-1637: Add index property to writeError

- source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-1577
> DRIVERS-1577 Note caveats for killAllSessions

- source/crud/tests/README.rst
- source/crud/tests/v1/read/aggregate-collation.yml
- source/crud/tests/v1/read/count-collation.yml
- source/crud/tests/v1/read/distinct-collation.yml
- source/crud/tests/v1/read/find-collation.yml
- source/crud/tests/v1/write/bulkWrite-collation.yml
- source/crud/tests/v1/write/deleteMany-collation.yml
- source/crud/tests/v1/write/deleteOne-collation.yml
- source/crud/tests/v1/write/findOneAndDelete-collation.yml
- source/crud/tests/v1/write/findOneAndReplace-collation.yml
- source/crud/tests/v1/write/findOneAndUpdate-collation.yml
- source/crud/tests/v1/write/replaceOne-collation.yml
- source/crud/tests/v1/write/updateMany-collation.yml
- source/crud/tests/v1/write/updateOne-collation.yml
- source/driver-bulk-update.rst
Also changed URLs in tests to point to our current docs URL.
> DRIVERS-1293: Updated CRUD spec to use hello and legacy hello

- source/command-monitoring/command-monitoring.rst
- source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
- source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst
- source/load-balancers/load-balancers.rst
- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
- source/server-selection/server-selection.rst
- source/sessions/driver-sessions.rst
- source/transactions/transactions.rst
- source/uri-options/uri-options.rst
Includes the load balancer spec itself, as well as modifications to other related specifications.
Also includes a second commit to handle DRIVERS-1293 in the specs modified by the load balancer work.
> WRITING-6786: Load Balancer Spec

- source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.json
- source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.yml
- source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.json
- source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.yml
- source/connection-monitoring-and-pooling/tests/pool-create-min-size-error.json
https://jira.mongodb.org/browse/DRIVERS-1724
> Fix a race condition in pool-checkout-no-idle, pool-checkout-no-stale tests

- source/connection-monitoring-and-pooling/tests/pool-clear-clears-waitqueue.json
- source/connection-monitoring-and-pooling/tests/pool-clear-clears-waitqueue.yml
https://jira.mongodb.org/browse/DRIVERS-1727
> Ignore ConnectionPoolCleared events in pool-clear-clears-waitqueue to avoid a race condition

- source/uri-options/tests/connection-options.json
- source/uri-options/tests/connection-options.yml
Allow loadBalanced=true&directConnection=false
This test was missed in the original commit.
DRIVERS-1721
> Update uri options test

- source/bson-corpus/tests/dbref.json
- source/dbref.rst
- source/extended-json.rst
https://jira.mongodb.org/browse/DRIVERS-1173
> DRIVERS-1173: DBRef spec

- source/crud/crud.rst
- source/crud/tests/unified/aggregate-let.json
- source/crud/tests/unified/aggregate-let.yml
https://jira.mongodb.org/browse/DRIVERS-776
PHPLIB POC: https://github.com/mongodb/mongo-php-library/pull/830
> DRIVERS-776: Add let to AggregateOptions

- source/crud/crud.rst
- source/crud/tests/README.rst
https://jira.mongodb.org/browse/DRIVERS-820
> DRIVERS-820: WriteError.details and clarify WriteError construction

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
> DRIVERS-1804 Connection pools must be created and eventually marked ready for any server if a direct connection is used

- source/connection-monitoring-and-pooling/tests/wait-queue-timeout.json
- source/connection-monitoring-and-pooling/tests/wait-queue-timeout.yml
- source/load-balancers/tests/wait-queue-timeouts.json
- source/load-balancers/tests/wait-queue-timeouts.yml
This change reduces the probability of timing out accidentally
DRIVERS-1806
> DRIVERS-1806 Increase `waitQueueTimeoutMS` in `wait-queue-timeout.yml`, `wait-queue-timeouts.yml`

- source/unified-test-format/unified-test-format.rst
Adds missing items to change log entry for load balancer work.
Fixes date for version string clarification to match original entry from 06fc4c36c392b271ea03a3303448c229e20a02f7.
> Revise change log entries

- source/sessions/snapshot-sessions.rst
Various small changes from reading through the spec while preparing for the PHPC implementation ([PHPC-1761](https://jira.mongodb.org/browse/PHPC-1761)).
Feel free to disregard anything that's unwelcome.
> Grammar and formatting revisions for snapshot reads spec

- source/polling-srv-records-for-mongos-discovery/tests/README.rst
https://jira.mongodb.org/browse/DRIVERS-1832
> DRIVERS-1832: Number SRV polling prose tests

- source/unified-test-format/tests/valid-pass/observeSensitiveCommands.json
- source/unified-test-format/tests/valid-pass/observeSensitiveCommands.yml
- source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-1868
These tests pass locally in PHPLIB while working on [PHPLIB-664](https://jira.mongodb.org/browse/PHPLIB-664) and [PHPLIB-676](https://jira.mongodb.org/browse/PHPLIB-676) (actual tickets for command redaction).
> DRIVERS-1868: Integration tests for observeSensitiveCommands

- source/unified-test-format/tests/valid-fail/entity-findCursor-malformed.json
- source/unified-test-format/tests/valid-fail/entity-findCursor-malformed.yml
- source/unified-test-format/tests/valid-fail/entity-findCursor.json
- source/unified-test-format/tests/valid-fail/entity-findCursor.yml
- source/unified-test-format/tests/valid-fail/ignoreResultAndError-malformed.json
- source/unified-test-format/tests/valid-fail/ignoreResultAndError-malformed.yml
Opening a PR for your consideration, as I manually split up the tests myself for Swift testing purposes already; see DRIVERS-1883 for details. (I have left it in "needs triage" for now to avoid spinning out language tickets in the event we don't end up going forward with this.)
> DRIVERS-1883 Split unified runner valid-fail malformed operation tests into separate files

- source/server-selection/server-selection.rst
Corrects 91b963d87e3775e8240074691123821eb255a4ac
> DRIVERS-1912: Fix change log and last modified date

- source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
- source/connection-monitoring-and-pooling/tests/pool-checkout-custom-maxConnecting-is-enforced.json
- source/connection-monitoring-and-pooling/tests/pool-checkout-custom-maxConnecting-is-enforced.yml
- source/uri-options/tests/connection-pool-options.json
- source/uri-options/tests/connection-pool-options.yml
- source/uri-options/uri-options.rst
@BorisDog and @patrickfreed are owners of the CMAP spec, @JamesKovacs is an owner of the URI options spec.
DRIVERS-1943
> DRIVERS-1943 Make maxConnecting configurable

- source/server-discovery-and-monitoring/tests/errors/prefer-error-code.json
- source/server-discovery-and-monitoring/tests/errors/prefer-error-code.yml
This test must have the string "not master".
> DRIVERS-1990 Fix test for preferring error codes over messages

- source/find_getmore_killcursors_commands.rst
- Describe behavior of exhaust cursors across server versions.
- Refactor driver requirements into a table by server version.
No changes to behavior.
Requested in https://github.com/mongodb/specifications/pull/1110#discussion_r769028345
> DRIVERS-1857 Refactor exhaust section

- source/retryable-reads/retryable-reads.rst
- source/retryable-writes/retryable-writes.rst
I'm reverting the CSOT changes from retryable reads/writes specs to unblock Neal's work on retrying handshakes in DRIVERS-746 (#1115). We're also reworking the retry policy in DRIVERS-1807 so I think it makes sense to revert and re-review these CSOT changes anyway.
Note this diff was generated by:
```
git checkout 6dc6f80026f0f8d99a8c81f996389534b14f6602~ -- source/retryable-reads source/retryable-writes
```
> DRIVERS-1807 Revert CSOT changes from retryable reads/writes specs

- source/versioned-api/versioned-api.rst
> Fix design rationale link in versioned api spec fixes #1143

- source/crud/tests/unified/updateMany-let.json
- source/crud/tests/unified/updateMany-let.yml
- source/crud/tests/unified/updateOne-let.json
- source/crud/tests/unified/updateOne-let.yml
https://jira.mongodb.org/browse/DRIVERS-2210
> DRIVERS-2210 Fix server versions for update*-let

- source/sessions/driver-sessions.rst
Fixes:
* bullets
* code syntax highlighting
* header underline
* (sp.)
> chore: fix driver-sessions RST rendering issues

- source/crud/tests/unified/bulkWrite-comment.json
- source/crud/tests/unified/bulkWrite-comment.yml
- source/crud/tests/unified/bulkWrite-replaceOne-let.json
- source/crud/tests/unified/bulkWrite-replaceOne-let.yml
- source/crud/tests/unified/bulkWrite-update-hint-serverError.yml
- source/crud/tests/unified/bulkWrite-updateMany-let.yml
- source/crud/tests/unified/replaceOne-comment.json
- source/crud/tests/unified/replaceOne-comment.yml
- source/crud/tests/unified/replaceOne-hint.yml
- source/crud/tests/unified/replaceOne-let.json
- source/crud/tests/unified/replaceOne-let.yml
- source/crud/tests/unified/updateMany-comment.json
- source/crud/tests/unified/updateMany-comment.yml
- source/crud/tests/unified/updateMany-hint-serverError.yml
- source/crud/tests/unified/updateMany-hint.yml
- source/crud/tests/unified/updateMany-let.json
- source/crud/tests/unified/updateMany-let.yml
- source/crud/tests/unified/updateOne-comment.json
- source/crud/tests/unified/updateOne-comment.yml
- source/crud/tests/unified/updateOne-hint-serverError.yml
- source/crud/tests/unified/updateOne-hint.yml
- source/crud/tests/unified/updateOne-let.json
- source/crud/tests/unified/updateOne-let.yml
- source/crud/tests/unified/updateWithPipelines.yml
https://jira.mongodb.org/browse/DRIVERS-2270
This was missed in previous PRs for both the `comment` and `let` CRUD options.
> DRIVERS-2270: Use $$unsetOrMatches for upsert and multi

- source/crud/tests/unified/aggregate-allowdiskuse.json
- source/crud/tests/unified/aggregate-allowdiskuse.yml
- source/crud/tests/unified/find-allowdiskuse.yml
https://jira.mongodb.org/browse/DRIVERS-2265
PHPLIB POC: https://github.com/mongodb/mongo-php-library/pull/913
> DRIVERS-2265: Tests for aggregate allowDiskUse option

- source/server-selection/server-selection-tests.rst
DRIVERS-1926
This PR makes some modifications to the prose test for the operationCount-based load balancing algorithm used in server selection intended to reduce the frequency of false negative failures. From [initial tests](https://evergreen.mongodb.com/version/6244f04457e85a04f1ff7ff6), they seem to work well for the Rust driver.
> DRIVERS-1926 Improve stability of server selection load balancing algorithm test

- source/change-streams/tests/unified/change-streams-errors.json
- source/change-streams/tests/unified/change-streams-errors.yml
- source/change-streams/tests/unified/change-streams-pre_and_post_images.json
- source/change-streams/tests/unified/change-streams-pre_and_post_images.yml
- source/change-streams/tests/unified/change-streams-resume-allowlist.json
- source/change-streams/tests/unified/change-streams-resume-allowlist.yml
- source/change-streams/tests/unified/change-streams-resume-errorLabels.json
- source/change-streams/tests/unified/change-streams-resume-errorLabels.yml
- source/change-streams/tests/unified/change-streams.json
- source/change-streams/tests/unified/change-streams.yml
- source/unified-test-format/tests/valid-pass/poc-change-streams.json
- source/unified-test-format/tests/valid-pass/poc-change-streams.yml
https://jira.mongodb.org/browse/DRIVERS-2288
PHPLIB POC included in: https://github.com/mongodb/mongo-php-library/pull/919
> DRIVERS-2288: Forbid serverless for unified change stream tests

- source/client-side-encryption/client-side-encryption.rst
- source/client-side-encryption/tests/README.rst
> DRIVERS-2297 Clarify that drivers should not spawn mongocryptd if bypassQueryAnalysis is set

- source/collection-management/tests/clustered-indexes.json
- source/collection-management/tests/clustered-indexes.yml
https://jira.mongodb.org/browse/DRIVERS-2325
PHPLIB POC: https://github.com/mongodb/mongo-php-library/pull/929
> DRIVERS-2325: commandStartedEvent assertions for clusteredIndex tests

- source/client-side-encryption/client-side-encryption.rst
This PR fixes RST syntax only.
> Fix rst syntax

- source/client-side-encryption/tests/README.rst
MONGOCRYPT-427 adds handling for explain command with csfle.
> DRIVERS-1950 remove note of explain

- source/client-side-encryption/client-side-encryption.rst
> Clarify how encryptedFields interacts with create and drop commands

- source/client-side-encryption/client-side-encryption.rst
> Define ECC, ECOC, and ESC acronyms within encryptedFields

- source/crud/crud.rst
This reverts a partial change from 9b3d539add0fc096d9cc961fb6bc5e9311d48f6d
> Add @TylerBrock back to list of CRUD spec authors

- source/client-side-encryption/etc/test-templates/fle2-Delete.yml.template
- source/client-side-encryption/etc/test-templates/fle2-EncryptedFields-vs-jsonSchema.yml.template
- source/client-side-encryption/etc/test-templates/fle2-FindOneAndUpdate.yml.template
- source/client-side-encryption/etc/test-templates/fle2-InsertFind-Indexed.yml.template
- source/client-side-encryption/etc/test-templates/fle2-Update.yml.template
- source/client-side-encryption/tests/legacy/fle2-Delete.json
- source/client-side-encryption/tests/legacy/fle2-Delete.yml
- source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.json
- source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.yml
- source/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.json
- source/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.yml
- source/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.json
- source/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.yml
- source/client-side-encryption/tests/legacy/fle2-Update.json
- source/client-side-encryption/tests/legacy/fle2-Update.yml
This reverts commit 631ee988fdcfaf2443633e3d6efca8a5bed7aea9.
> DRIVERS-2343 Revert "update FLE 2 find payloads (#1235)"

- source/client-side-encryption/client-side-encryption.rst
> Update minimum server versions & clarify abstract

- source/change-streams/tests/unified/change-streams-showExpandedEvents.json
- source/change-streams/tests/unified/change-streams-showExpandedEvents.yml
Tests are updated in passing in Node - https://github.com/mongodb/node-mongodb-native/pull/3288
> fix(DRIVERS-1975): add commandName to runCommand usage in tests

- source/client-side-encryption/tests/unified/rewrapManyDataKey.json
- source/client-side-encryption/tests/unified/rewrapManyDataKey.yml
> DRIVER-2017 relax multi/upsert expectations

- source/server-discovery-and-monitoring/server-monitoring.rst
Removing the mention of an optimization that doesn't apply because of DRIVERS-830
- Make sure there are generated JSON files from the YAML test files.
- Test changes in at least one language driver.
- Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
> DRIVERS-2329: remove optimization mention that no longer applies

- source/client-side-encryption/client-side-encryption.rst
> Make KMS options more typescript-shaped

- source/client-side-encryption/tests/unified/addKeyAltName.json
- source/client-side-encryption/tests/unified/addKeyAltName.yml
- source/client-side-encryption/tests/unified/getKey.json
- source/client-side-encryption/tests/unified/getKey.yml
- source/client-side-encryption/tests/unified/getKeyByAltName.json
- source/client-side-encryption/tests/unified/getKeyByAltName.yml
- source/client-side-encryption/tests/unified/removeKeyAltName.json
- source/client-side-encryption/tests/unified/removeKeyAltName.yml
> Updated CSE tests where there is no expected result

- source/server-discovery-and-monitoring/tests/integration/hello-command-error.json
- source/server-discovery-and-monitoring/tests/integration/hello-command-error.yml
- source/server-discovery-and-monitoring/tests/integration/hello-network-error.json
- source/server-discovery-and-monitoring/tests/integration/hello-network-error.yml
- source/server-discovery-and-monitoring/tests/integration/hello-timeout.json
- source/server-discovery-and-monitoring/tests/integration/hello-timeout.yml
[DRIVERS-2386](https://jira.mongodb.org/browse/DRIVERS-2386)
> DRIVERS-2386 Improve reliability of SDAM heartbeat error spec tests.

- source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-2305
> DRIVERS-2305: Note schema version bumps in spec change log

- source/client-side-operations-timeout/tests/gridfs-advanced.json
- source/client-side-operations-timeout/tests/gridfs-advanced.yml
- source/client-side-operations-timeout/tests/gridfs-delete.json
- source/client-side-operations-timeout/tests/gridfs-delete.yml
- source/client-side-operations-timeout/tests/gridfs-download.json
- source/client-side-operations-timeout/tests/gridfs-download.yml
- source/client-side-operations-timeout/tests/gridfs-find.json
- source/client-side-operations-timeout/tests/gridfs-find.yml
- source/client-side-operations-timeout/tests/gridfs-upload.json
- source/client-side-operations-timeout/tests/gridfs-upload.yml
> DRIVERS-555 Increase GridFS test timeouts and other fixes for CSOT

- source/sessions/tests/README.rst
> DRIVERS-2398 add mongos limiting note

- source/server-selection/tojson.sh
The script for converting YAML to JSON is in [source/Makefile](https://github.com/mongodb/specifications/blob/b1a3fdd46a0c7797557215a0804a2c3b96b3be94/source/Makefile).
> Remove unused tojson.sh script.

- source/retryable-writes/retryable-writes.rst
- source/retryable-writes/tests/README.rst
> DRIVERS-2327 NoWritesPerformed Retryable Writes Error Handling

- source/auth/auth.rst
- source/auth/tests/mongodb-aws.rst
> DRIVERS-1746 Add native support for AWS IAM Roles for service accounts, EKS in particular

- source/change-streams/tests/unified/change-streams-clusterTime.json
- source/change-streams/tests/unified/change-streams-clusterTime.yml
- source/change-streams/tests/unified/change-streams-showExpandedEvents.json
- source/change-streams/tests/unified/change-streams-showExpandedEvents.yml
> DRIVERS-2443 Add serverless: forbid to change stream clusterTime test

- source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Fixes indentation of the pseudo code for `updateRSFromPrimary`
> DRIVERS-2412: fix updateRSFromPrimary pseudo code indentation

- .github/CODEOWNERS
Shane Harvey
Benji Rewis
- [Not applicable] Update changelog.
- [Not applicable ] Make sure there are generated JSON files from the YAML test files.
- [Not applicable] Test changes in at least one language driver.
- [Not applicable] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
> Add CSOT spec codeowners

- source/client-side-encryption/client-side-encryption.rst
- source/client-side-encryption/tests/README.rst
These test cases give a basis for testing various situations of an IMDS server without requiring testing within an Azure VM.
While writing this, I thought of possible additional IMDS behaviors that may be prudent to handle, but they would require updating the `fake_azure.py` application.
---
> [DRIVERS-2411] Prose Tests for IMDS Communication

- source/client-side-operations-timeout/client-side-operations-timeout.rst
- source/client-side-operations-timeout/etc/templates/retryability-legacy-timeouts.yml.template
- source/client-side-operations-timeout/etc/templates/retryability-timeoutMS.yml.template
- source/client-side-operations-timeout/tests/bulkWrite.json
- source/client-side-operations-timeout/tests/bulkWrite.yml
- source/client-side-operations-timeout/tests/retryability-legacy-timeouts.json
- source/client-side-operations-timeout/tests/retryability-legacy-timeouts.yml
- source/client-side-operations-timeout/tests/retryability-timeoutMS.json
- source/client-side-operations-timeout/tests/retryability-timeoutMS.yml
- source/retryable-reads/retryable-reads.rst
- source/retryable-writes/retryable-writes.rst
> DRIVERS-1807 Keep existing retry behavior unless CSOT is enabled

- source/client-side-encryption/tests/README.rst
- Add integration tests for Azure KMS
Tests requiring an Azure VM depend on the scripts in drivers-evergreen-tools here: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/239
> DRIVERS-2411 add integration tests for Azure KMS

- source/crud/tests/unified/findOneAndUpdate-errorResponse.json
- source/crud/tests/unified/findOneAndUpdate-errorResponse.yml
https://jira.mongodb.org/browse/DRIVERS-2385
This was added by mistake in 9fec9df099d132df047650315411bc0a532f0cef
> DRIVERS-2385: Revert useMultipleMongoses:false in findOneAndUpdate test

- source/connection-monitoring-and-pooling/tests/pool-clear-schedule-run-interruptInUseConnections-false.yml
- source/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.yml
> DRIVERS-1707 formatting and bug fixes for yml files 

- source/auth/auth.rst
> DRIVERS-1746 Add note about AssumeRole distinction

- source/client-side-encryption/client-side-encryption.rst
https://jira.mongodb.org/browse/DRIVERS-2462
> DRIVERS-2462: Reformat CSFLE spec changelog

- source/auth/auth.rst
- source/auth/tests/mongodb-aws.rst
> DRIVERS-2493 Ensure Auth Environment Variables are Always Dynamic

- source/client-side-encryption/client-side-encryption.rst
No DRIVERS ticket since this is a clarification.
> Clarify requirement of TLS options API

- source/connection-string/connection-string-spec.rst
Context: https://mongodb.slack.com/archives/C72LB5RPV/p1671703867728959
> Note that host info ends with "/" in connection string opts section

- source/logging/logging.rst
> Fix typo in trace log level example

- source/command-logging-and-monitoring/command-logging-and-monitoring.rst
- source/logging/logging.rst
This is a collection of minor changes that have been discussed on other spec PRs as well as in the drivers-1204-logging Slack channel; see DRIVERS-2516 for details.
> DRIVERS-2516 Collection of follow-up logging changes

- source/initial-dns-seedlist-discovery/tests/replica-set/dbname-with-commas-escaped.json
- source/initial-dns-seedlist-discovery/tests/replica-set/dbname-with-commas-escaped.yml
- source/initial-dns-seedlist-discovery/tests/replica-set/dbname-with-commas.json
- source/initial-dns-seedlist-discovery/tests/replica-set/dbname-with-commas.yml
Updates the Initial DNS Seedlist Discovery tests for this specific case.
> DRIVERS-1777: Add DB name with commas spec tests

- source/transactions/tests/README.rst
- Remove outdated Q&A for reducing `transactionLifetimeLimitSeconds`.
This is a follow-up to https://github.com/10gen/mongo-orchestration/pull/295
Decreasing `transactionLifetimeLimitSeconds` is no longer required to speed up transaction tests.
~~- [ ] Update changelog.~~ N/A.
~~- [ ] Make sure there are generated JSON files from the YAML test files.~~ N/A.
~~- [ ] Test changes in at least one language driver.~~ N/A.
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~ N/A.
> DRIVERS-2286 remove outdated Q&A

- source/sessions/driver-sessions.rst
- source/sessions/tests/README.rst
- [N/A] Make sure there are generated JSON files from the YAML test files.
> DRIVERS-2530: Defer checking for session support until after connection checkout

- source/mongodb-handshake/handshake.rst
- [*] Update changelog.
- [n/a] Make sure there are generated JSON files from the YAML test files.
- [*] Test changes in at least one language driver.
- [*] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
I've implemented this in a [branch](https://github.com/abr-egn/mongo-rust-driver/tree/RUST-1501/faas-poc) of the Rust driver, and tests pass across all configurations.
> DRIVERS-2209 Collect FaaS information in handshake metadata

- source/collection-management/tests/timeseries-collection.json
- source/collection-management/tests/timeseries-collection.yml
[DRIVERS-2546](https://jira.mongodb.org/browse/DRIVERS-2546)
> DRIVERS-2546: Add test for new time series collection options

- source/faas-automated-testing/faas-automated-testing.rst
Node PR: https://github.com/mongodb/node-mongodb-native/pull/3569
Tools PR: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/274
> test(DRIVERS-2384): test deployed faas functions

- source/faas-automated-testing/faas-automated-testing.rst
> Format AWS SAM CLI link for rst

- source/faas-automated-testing/faas-automated-testing.rst
> fix(DRIVERS-2384): faas testing spec updates

- source/polling-srv-records-for-mongos-discovery/polling-srv-records-for-mongos-discovery.rst
Fix `mongo+srv` -> `mongodb+srv`
> Fix typo in polling-srv-records-for-mongos-discovery.rst

- source/retryable-reads/retryable-reads.rst
- source/retryable-reads/tests/README.rst
- source/retryable-writes/retryable-writes.rst
- source/retryable-writes/tests/README.rst
- source/server-selection/server-selection.rst
> DRIVERS-1571 Fix changelog entries

- source/server-discovery-and-monitoring/server-discovery-and-monitoring-logging-and-monitoring.rst
> Fix typo in SDAM logging

- source/unified-test-format/unified-test-format.rst
> DRIVERS-2698: clarify that the unified test format is only intended for enterprise servers

- source/retryable-reads/retryable-reads.rst
https://jira.mongodb.org/browse/DRIVERS-2764 
This is similar to the error and fix in #1466.
> DRIVERS-2764 Fix error in retryable read pusedocode when CSOT is not enabled

- source/unified-test-format/unified-test-format.md
> DRIVERS-2789 Fix links in Unified Test Format

- .pre-commit-config.yaml
- scripts/check_anchors/check-anchors.sh
- scripts/check_anchors/index.js
- scripts/check_anchors/package-lock.json
- scripts/check_anchors/package.json
- source/auth/auth.md
- source/client-side-operations-timeout/client-side-operations-timeout.md
- source/index.md
- source/unified-test-format/unified-test-format.md
> DRIVERS-2789 Add Markdown Anchor Check

- markdown_link_config.json
This was introduced in fd5a68d749d37d8afe20f78eeb0a2491f8fa61a0
> Ignore links to private 10gen/mongohouse repo

- source/auth/auth.md
- source/auth/tests/mongodb-oidc.md
> DRIVERS-2878 OIDC Atlas Testing Updates

- source/auth/auth.md
> DRIVERS-2601 Fix API description for GCP built-in OIDC provider

- source/retryable-writes/retryable-writes.rst
> docs(retryable-writes.rst): correct Driver Session ref

- source/client-side-operations-timeout/tests/change-streams.json
- source/client-side-operations-timeout/tests/change-streams.yml
- source/client-side-operations-timeout/tests/close-cursors.json
- source/client-side-operations-timeout/tests/close-cursors.yml
- source/client-side-operations-timeout/tests/convenient-transactions.json
- source/client-side-operations-timeout/tests/convenient-transactions.yml
- source/client-side-operations-timeout/tests/non-tailable-cursors.json
- source/client-side-operations-timeout/tests/non-tailable-cursors.yml
- source/client-side-operations-timeout/tests/sessions-inherit-timeoutMS.json
- source/client-side-operations-timeout/tests/sessions-inherit-timeoutMS.yml
- source/client-side-operations-timeout/tests/sessions-override-operation-timeoutMS.json
- source/client-side-operations-timeout/tests/sessions-override-operation-timeoutMS.yml
- source/client-side-operations-timeout/tests/sessions-override-timeoutMS.json
- source/client-side-operations-timeout/tests/sessions-override-timeoutMS.yml
- source/client-side-operations-timeout/tests/tailable-awaitData.json
- source/client-side-operations-timeout/tests/tailable-awaitData.yml
- source/client-side-operations-timeout/tests/tailable-non-awaitData.json
- source/client-side-operations-timeout/tests/tailable-non-awaitData.yml
> DRIVERS-2870 CSOT tests. Increase timeouts to allow for testing on slower envs

- source/client-side-operations-timeout/tests/close-cursors.json
- source/client-side-operations-timeout/tests/close-cursors.yml
> DRIVERS-2873 CSOT test: Fix collection name in expected event

- source/crud/bulk-write.md
> Fix bulk write spec status

- source/server_write_commands.rst
Clarify why _id values are created client-side by default
> Add client-side _id FAQ entry

- source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
> Fix wrong link

- mkdocs.yml
- source/requirements.txt
> DRIVERS-2789 Render Admonitions on ReadTheDocs

- source/extended-json.md
- source/faas-automated-testing/faas-automated-testing.md
- source/retryable-reads/tests/README.md
- source/server-discovery-and-monitoring/server-discovery-and-monitoring.md
- source/server-discovery-and-monitoring/server-monitoring.md
- source/server-selection/server-selection.md
> DRIVERS-2789 Fix malformed links

- source/client-side-encryption/tests/README.md
> rename duplicate FLE prose test 22 to 23

- source/client-side-operations-timeout/tests/command-execution.json
- source/client-side-operations-timeout/tests/command-execution.yml
- source/load-balancers/tests/sdam-error-handling.json
- source/load-balancers/tests/sdam-error-handling.yml
- source/server-discovery-and-monitoring/tests/unified/hello-command-error.json
- source/server-discovery-and-monitoring/tests/unified/hello-command-error.yml
- source/server-discovery-and-monitoring/tests/unified/hello-network-error.json
- source/server-discovery-and-monitoring/tests/unified/hello-network-error.yml
- source/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.json
- source/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.yml
- source/server-discovery-and-monitoring/tests/unified/minPoolSize-error.json
- source/server-discovery-and-monitoring/tests/unified/minPoolSize-error.yml
> DRIVERS-1725 Unskip failCommand+appName tests on MongoDB 4.4.7+

- source/connection-string/tests/valid-warnings.json
- source/connection-string/tests/valid-warnings.yml
https://github.com/mongodb/mongo-python-driver/pull/1685
> DRIVERS-2915 OIDC: Add missing data in connection string test

- source/crud/tests/unified/aggregate-write-readPreference.json
This PR regenerates a json file that didn't get updated from these yml changes: https://github.com/mongodb/specifications/pull/1660.
> DRIVERS-2914: Regenerate aggregate-write-readPreference.json (#1660)

- source/crud/bulk-write.md
> DRIVERS-2967 Define more options for modeling bulk write results

- source/crud/tests/unified/client-bulkWrite-partialResults.json
- source/crud/tests/unified/client-bulkWrite-partialResults.yml
> Fix duplicate bulk write test name

- source/unified-test-format/unified-test-format.md
> Document namespace option for failCommand

- source/transactions/transactions.md
> chore: fix txn spec lint

- source/uri-options/tests/read-preference-options.json
- source/uri-options/tests/read-preference-options.yml
- ~[ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
This adds a single new test with read preference tags that are mixed case, to ensure that drivers don't inadvertently lowercase values.
> DRIVERS-1400: Add test to ensure read preference tags are case sensitive

- source/load-balancers/tests/transactions.json
- source/load-balancers/tests/transactions.yml
- source/transactions/transactions.md
Node patch running new test: https://spruce.mongodb.com/version/67249f9b8462ef00074de706/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> feat(DRIVERS-2647): ensure endSessions unpins

- source/bson-binary-vector/bson-binary-vector.md
Updating status, which wasn't done before merge.
> DRIVERS-2926 Updated BSON Binary Subtype 9 - Vector Status to Accepted

- source/client-side-encryption/client-side-encryption.md
Updates some client side encryption sample code to remove an erroneous option that was passed in ClientEncryptionOpts.
> DRIVERS-953: Remove erroneous option from ClientEncryptionOpts sample code

- source/client-side-encryption/tests/benchmarks.md
> JAVA-5584 Fix link to Java MongoCrypt class implementation

- source/client-side-encryption/tests/legacy/keyCache.yml
Follow-up to https://github.com/mongodb/specifications/pull/1730 to attempt to fix the "Check if all JSON test files are up-to-date" GitHub action.
~~- [ ] Test changes in at least one language driver.~~
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
> DRIVERS-2781 regenerate keyCache.yml

- source/retryable-writes/tests/unified/aggregate-out-merge.json
- source/retryable-writes/tests/unified/aggregate-out-merge.yml
https://jira.mongodb.org/browse/DRIVERS-3061
POC: https://github.com/mongodb/mongo-php-library/pull/1547
> DRIVERS-3061: Skip $out test on serverless

- docs/workforce-human-oidc-auth.md
> MONGOSH-2027 Specify that addresses must be unique for OIDC auth

- source/unified-test-format/unified-test-format.md
This was omitted from the change log entry in a8a7d01036615dc6122ad16a854834453b25e6f8
> Note that $$lte was introduced in schema 1.9

- .github/PULL_REQUEST_TEMPLATE.md
Added a new bullet to require a DRIVERS ticket for PR templates
clusters).
> DRIVERS-3293: Add DRIVERS ticket requirement to PR checklist
