mongodb/specifications

source/index-management.rst
Resolves: https://jira.mongodb.org/browse/SPEC-193
=> SPEC-193: Document for 2.4 that create indexes must insert into system.indexes

source/index-management.rst
Resolves: https://jira.mongodb.org/browse/SPEC-189
=> SPEC-189: Be explicit on index name generation

source/driver-bulk-update.rst
This spec is superseded by the Driver CRUD API Spec, but it might as well be public, especially since the CRUD spec relies on some details from this spec.
=> Publish deprecated Bulk API Spec.

source/crud/crud.rst
=> CountOptions skip should refer to counting, not returning

source/command-monitoring/tests/bulkWrite.json, source/command-monitoring/tests/bulkWrite.yml, source/command-monitoring/tests/find.json, source/command-monitoring/tests/find.yml, source/command-monitoring/tests/updateOne.json, source/command-monitoring/tests/updateOne.yml
This handles:
1. mixed bulk write
2. faked reply when no GLE is sent
3. find with all renamed options present (not all options, just the ones that need special massaging)
4. upsert where the identifier does not come back from the server due to it's non-objectid-ness.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/45)
=> added new command-monitoring tests.

source/crud/crud.rst
Moves bypassDocumentValidation out of the individual bulk write models and into the BulkWriteOptions. This negates the need to batch writes differently based on the bypassDocumentValidation setting.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/specifications/64)
=> fixed issue with bypass doc change being specified at the wrong level.

source/server-discovery-and-monitoring/tests/rs/primary_reports_new_member.json, source/server-discovery-and-monitoring/tests/rs/primary_reports_new_member.yml
The Ruby driver had a bug where a primary in a ReplicaSetWithPrimary topology would report an additional member in its list of hosts but not add it to the cluster. We don't have an SDAM test for this simple, vanilla case. This PR adds one.
See [RUBY-1087](https://jira.mongodb.org/browse/RUBY-1087) for details.
=> Additional test for adding new hosts to ReplicaSetWithPrimary

source/connection-string/connection-string-spec.rst
The spec and tests aren't in alignment about the acceptable port range (the spec says "between 0 and 65535", the tests treat [1,65535] as the acceptable range).
This proposes a fix to the spec.
=> Fix acceptable range of ports in Port section

source/command-monitoring/command-monitoring.rst, source/crud/crud.rst, source/find_getmore_killcursors_commands.rst
These are written with underscore:
https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#request-opcodes
=> Use opcode names as documented

source/crud/crud.rst
Supersedes https://github.com/mongodb/specifications/pull/102.
=> SPEC-337: Deprecate modifiers and clean up existing wording for default values

source/crud/tests/README.rst
Improves description of the test file contents. Also removes trailing whitespace and applies consistent indentation and an 80-character line wrap.
=> Revise README for CRUD spec tests

source/connection-string/connection-string-spec.rst, source/connection-string/tests/invalid-uris.json, source/connection-string/tests/invalid-uris.yml, source/connection-string/tests/valid-auth.json, source/connection-string/tests/valid-host_identifiers.json, source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-unix_socket-absolute.json, source/connection-string/tests/valid-unix_socket-relative.json, source/connection-string/tests/valid-warnings.json
https://jira.mongodb.org/browse/SPEC-835
Supersedes https://github.com/mongodb/specifications/pull/105.
=> SPEC-835: Clarify that percent signs must be encoded in userinfo

source/connection-string/connection-string-spec.rst
The spec requires usernames that contain % @ and : to be URL encoded.
It then goes on to say % @ and more-than-one : is prohibited in user information.
URL encoded % still contains % (%25) so % is acceptable character
=> % is valid character in user information

source/bson-corpus/tests/dbref.json, source/bson-corpus/tests/double.json
Add test cases for DBRef in ~document.json~ (now dbref.json).
=> Extended JSON test case for NaN with payload is lossy.

source/connection-string/connection-string-spec.rst
The full connection string could include sensitive information, such as credentials, which we would not want to expose in logs
=> Do not encourage authors to print the full connection string

source/bson-corpus/tests/top.json
https://jira.mongodb.org/browse/SPEC-849
These tests were incorrectly added under the "decodeErrors" cases; all these documents can be converted between bson/json.
=> SPEC-849 - Fix BSON/JSON spec tests for keys that start with '$'.

source/bson-corpus/tests/double.json
There are a variety of double values that are not a number. The Extended JSON Spec does not specify which variant is decoded from `{"$numberDouble": "NaN"}`, although it says that "NaN (all variants)" is encoded as "NaN". In C, `strtod ("NaN", NULL)` chooses different values on different platforms. Consider:
```c
#include <stdio.h>
#include <stdlib.h>
int main() {
union {
double d;
unsigned char c[sizeof(double)];
} u;
u.d = strtod("NaN", NULL);
printf("nan: %02x%02x%02x%02x%02x%02x%02x%02x\n",
u.c[0], u.c[1], u.c[2], u.c[3], u.c[4], u.c[5], u.c[6], u.c[7]);
}
```
On my Mac with Clang 8, or an Ubuntu 16.04 VirtualBox on my Mac with GCC 4.8, or Ubuntu 16.04 EC2 instance with GCC 5.4, this prints:
```
nan: 000000000000f87f
```
On a Windows EC2 instance with Visual Studio 2015, or Solaris …
=> Extended JSON test: mark NaN test as "lossy"

source/bson-corpus/tests/maxkey.json
http://bsonspec.org/spec.html
| 	"\xFF" e_name 	Min key
| 	"\x7F" e_name 	Max key
=> Fix Max Key type id

source/crud/crud.rst
The description of `snapshot` is a duplicate of `showRecordId`.
=> minor: fix description of FindOptions snapshot field

source/crud/crud.rst
0617520964b35fe21ab29fc7e0f217e45b94a754 accidentally added a second copy of the "collation" option in some bulk write models.
=> crud.rst: Remove extra "collation" option added to several bulk write models

source/crud/crud.rst
`returnKey` and `snapshot` should be booleans, not documents
=> minor: fix types of options in crud spec

source/change-streams.rst
=> refactor(change-streams): `none` => `default` for `fullDocument`

source/message/OP_MSG.rst
I suggest we take out this test, as it's not relevant to OP_MSG and the math isn't accurate given the current maxMessageSizeBytes.
=> Take out irrelevant OP_MSG test

source/crud/crud.rst, source/crud/tests/write/bulkWrite-arrayFilters.json, source/crud/tests/write/bulkWrite-arrayFilters.yml, source/crud/tests/write/findOneAndUpdate-arrayFilters.json, source/crud/tests/write/findOneAndUpdate-arrayFilters.yml, source/crud/tests/write/updateMany-arrayFilters.json, source/crud/tests/write/updateMany-arrayFilters.yml, source/crud/tests/write/updateOne-arrayFilters.json, source/crud/tests/write/updateOne-arrayFilters.yml
In the original PR https://github.com/mongodb/specifications/pull/159 we forgot to add `arrayFilters` to UpdateOneModel and UpdateManyModel.
=> SPEC-888 Add arrayFilters to bulk write update models.

source/enumerate-indexes.rst
I did end up bumping the patch version of the spec, as some little behaviour has changed. As it only makes things more lenient, it is however not a BC break.
=> SPEC-57: Clarify what the error codes actually indicate

source/change-streams.rst
If a user choses to use the change stream helper, and not just run
an aggregation (resulting in a raw cursor), then it is assumed that
they have opted in to "resumability".  If we receive a response doc
that does not have a resume token, we can no longer provide this
guarantee and therefore MUST close the stream.
=> fix(change-streams): change streams should close on missing token

source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-861
Related issues discussed in the spec ticket were previously fixed by @saghm in https://github.com/mongodb/specifications/commit/72190ee6ee132c9e79d392a6a62d29b39bcf56c3
https://github.com/mongodb/specifications/commit/587c9654f5f1ee47287c57855ce8058e44b5a0d6 in #150 and #151, respectively.
=> SPEC-861: showRecordId in FindOptions is a boolean

source/crud/tests/read/aggregate-out.json, source/crud/tests/read/aggregate-out.yml
This is a pretty small change (just duplicating the existing $out test with the batch size changed to zero), so I think one LGTM should be enough.
=> SPEC-826 Add test of aggregate with $out with a batch size of 0

source/retryable-writes/tests/README.rst
https://jira.mongodb.org/browse/SPEC-964
=> SPEC-964: Tests no longer need to specify writeConcern

source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-941
=> SPEC-941: Document negative limit for FindOptions

source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-959
747d3cdc9d1eccbcdff6b20765218e11de46d079 added a test case for retrying "not master" errors but neglected to update the spec itself.
This change was missing from https://github.com/mongodb/specifications/pull/213.
=> SPEC-959: Retry writes after a "not master" error

source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst, source/initial-dns-seedlist-discovery/tests/one-result-default-port.json, source/initial-dns-seedlist-discovery/tests/one-result-default-port.yml, source/initial-dns-seedlist-discovery/tests/one-txt-record.json, source/initial-dns-seedlist-discovery/tests/one-txt-record.yml, source/initial-dns-seedlist-discovery/tests/two-results-default-port.json, source/initial-dns-seedlist-discovery/tests/two-results-default-port.yml, source/initial-dns-seedlist-discovery/tests/two-results-nonstandard-port.json, source/initial-dns-seedlist-discovery/tests/two-results-nonstandard-port.yml, source/initial-dns-seedlist-discovery/tests/two-txt-records-with-override.json, source/initial-dns-seedlist-discovery/tests/two-txt-records-with-override.yml, source/initial-dns-seedlist-discovery/tests/two-txt-records.json, source/initial-dns-seedlist-discovery/tests/two-txt-records.yml
And update the tests to use localhost.build.10gen.cc instead of localhost.
=> Remove prohibition of raising errors when DNS issues occur during parsing

source/retryable-writes/tests/README.rst, source/retryable-writes/tests/bulkWrite.json, source/retryable-writes/tests/bulkWrite.yml
https://jira.mongodb.org/browse/SPEC-971
Note that the first commit in this PR also fixes an off-by-one error for indexes of `insertedIds` objects in the write result. @rozza: If you didn't notice that error while reviewing https://github.com/mongodb/specifications/pull/219, it's possible that you might not be asserting `insertedIds` correctly.
=> SPEC-971: Allow assertions of write results on BulkWriteException

source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/README.rst
https://jira.mongodb.org/browse/SPEC-969
=> SPEC-969: Standalone servers do not support retryable writes

source/crud/crud.rst, source/retryable-writes/retryable-writes.rst
https://jira.mongodb.org/browse/SPEC-971
https://jira.mongodb.org/browse/SPEC-972
Note: I've lumped both tickets into the same PR as they're somewhat related. The retryable writes revisions for SPEC-972 are also relevant to improving access to intermediary write results during a failed bulk write (SPEC-971).
=> SPEC-971 and SPEC-972: Revise error reporting for retryable and bulk writes

source/retryable-writes/tests/insertMany.json, source/retryable-writes/tests/insertMany.yml
With `times: 2` the retry attempt for this insert still succeeds:
```
> db.adminCommand( { "configureFailPoint" : "onPrimaryTransactionalWrite", "mode" : { "times" : 2 }, "data" : { "failBeforeCommitExceptionCode" : 1 } })
{ "ok" : 1, "operationTime" : Timestamp(1509648432, 5) }
> var txnCmd = {"insert":"test","documents":[{_id:1},{_id:2},{_id:3}], "lsid": {"id": BinData(4, "nGmSpxKoTcWrYclQh5xF0A==")}, txnNumber: NumberLong(12), ordered: true}
> db.runCommand(txnCmd);
2017-11-02T14:47:25.664-0400 E QUERY    [thread1] Error: error doing query: failed: network error while attempting to run command 'insert' on host '127.0.0.1:27017'  :
DB.prototype.runCommand@src/mongo/shell/db.js:132:1
@(shell):1:1
2017-11-02T14:47:25.666-0400 I NETWORK  [thread1] trying reconnect to 127.0.0.1:27017 …
```
=> Fix insertMany failpoint

source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst, source/initial-dns-seedlist-discovery/tests/README.rst, source/initial-dns-seedlist-discovery/tests/one-txt-record-multiple-strings.json, source/initial-dns-seedlist-discovery/tests/one-txt-record-multiple-strings.yml
Please note that test7 to test10 are missing, and that the version jumps from 1.1.2 to 1.1.4 due to this PR  #233
=> SPEC-981 Clarify that TXT records may contain multiple 255-character strings

source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst, source/initial-dns-seedlist-discovery/tests/README.rst, source/initial-dns-seedlist-discovery/tests/txt-record-utf8-character.yml, source/initial-dns-seedlist-discovery/tests/txt-record-with-listable-option-override.json, source/initial-dns-seedlist-discovery/tests/txt-record-with-listable-option-override.yml
It also fixes a previous error with the other readPreferenceTags test.
=> SPEC-984 Listable options aren't specifically mentioned / SPEC-988 Clarify which host names to query SRV and TXT records on

source/retryable-writes/tests/bulkWrite.json, source/retryable-writes/tests/bulkWrite.yml
https://jira.mongodb.org/browse/SPEC-996
See: https://github.com/jmikola/mongo-c-driver/pull/3/commits/e74ff806d59fba37c4af64ac69519aed25348735#r151318363 for additional context.
=> SPEC-996 re-order bulk write ops to avoid mid-batch error

source/Makefile
This fixes the issue where running `make` would wipe any JSON files if the corresponding yaml file had an error
=> don't wipe json files if the yaml is invalid

source/sessions/driver-sessions.rst
The team working on implementing sessions for the Perl driver noticed these
issues with the sessions spec:
* Assumed, but never stated, that MongoClient holds a clusterTime
* Test plan written assuming APM is implemented
This PR has minor clarifications for both.  No changes are needed by drivers
that have implmented the spec.
=> Clarify session spec

source/sessions/driver-sessions.rst
It's implied but not clearly stated and this confused an implementer unfamiliar
with the spec.
=> Clarify that sessions require replica sets or sharded clusters

source/initial-dns-seedlist-discovery/tests/README.rst, source/initial-dns-seedlist-discovery/tests/uri-with-auth.json, source/initial-dns-seedlist-discovery/tests/uri-with-auth.yml
There was a bug in our driver's implementation of the DNS Seedlist discovery where auth that came in with a `+srv` uri was not preserved in the final connection string.
This PR adds a spec for that case by duplicating the `one-result-default-port` spec and adding dummy `user` and `password` credentials that can be checked by driver tests. No new test servers need to be set up for this.
🔗 https://github.com/mongodb/node-mongodb-native/pull/1640.
cc @mbroadst @daprahamian
=> Add tests for auth in DNS Seedlist specs

source/crud/crud.rst
I don't think this change is worth adding CRUD Spect tests for.
=> Only send bypassDocumentValidation if it's false

source/read-write-concern/tests/connection-string/write-concern.json, source/read-write-concern/tests/connection-string/write-concern.yml
Given that the spec says that this option should error [when specified](https://github.com/mongodb/specifications/blob/master/source/read-write-concern/read-write-concern.rst#inconsistent-writeconcern), I think this should be an error instead of a warning.
=> Inconsistent write concern should cause error in connection string

source/read-write-concern/tests/README.rst, source/read-write-concern/tests/document/write-concern.json, source/read-write-concern/tests/document/write-concern.yml
(Apologies for not noticing this before the last PR)
Similar to #267, one of the "document" tests in the read-write-concern spec also describes `w=0,j=true` as being valid. I think_that this should be invalid, although the phrasing of what "valid" means for this test in the README is copy-pasted from the above test and therefore doesn't really make sense. I proposed a wording change to README which clarifies that this should be invalid, but it's possible that we want this test to be interpreted differently since it's just creating write concern from a document, so theoretically we might want users to still be able to construct this write concern even if it causes an error when actually used.
=> Inconsistent write concern in document test is invalid

source/server-selection/server-selection.rst
I also went ahead and alphabetized the list so that it more closely resembles [the `set_read_preference_secondary.js` override in the mongodb/mongo repository](https://github.com/mongodb/mongo/blob/r3.7.1/jstests/libs/override_methods/set_read_preference_secondary.js#L25-L38).
=> SPEC-1020: Add "find" command to "may-use-secondary" list

source/connection-string/tests/invalid-uris.yml
This was causing the Ruby YAML parser to error.
=> Fix invalid-uris connection string YAML test format

source/server_write_commands.rst
This correctly specifies a 16KB overhead allowance for command envelopes, and clarifies this limit with respect to maximum size of a batch operation.
SPEC-497
=> refactor(server-write-commands): clarify command overhead size

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
The SDAM spec states that the subroutine `updateRSWithoutPrimary` does not remove any servers from the topology description. As shown directly above it in the pseudocode, this is not the case.
=> revise statement about host removal in `updateRSWithoutPrimary`

source/sessions/driver-sessions.rst
Updates the cursor prose test for sessions to use a collection of
5 with a batchsize of 3. This way, iterating past 4 documents
will result in the cursor being exhausted.
=> docs(sessions): updating session cursor prose test

source/command-monitoring/tests/find.json, source/command-monitoring/tests/find.yml
The server has begun rejecting queries with "snapshot" and I assume it will eventually reject queries with "maxScan". To avoid test failures, remove them from the Command Monitoring tests.
=> Deprecate snapshot and maxScan

source/transactions/tests/auto-start.json, source/transactions/tests/auto-start.yml
The way this test is currently written is broken: if an empty commit succeeds (first operation), then an empty commit (last operation) after a non-empty commit (third operation) should also succeed. So the expectation of an error is incorrect, but is it worth keeping the test around anyway? I'm not sure. There aren't any expectations in the test anymore, other than the fact that no error is thrown.
=> test(auto-start): correct assumptions about committing empty txns

source/change-streams.rst
https://jira.mongodb.org/browse/SPEC-905
=> SPEC-905: Clarify that the initial aggregate command for a change stream should not be retried

source/auth/tests/connection-string.json, source/auth/tests/connection-string.yml
Test cases that are not valid should throw an exception
rather than log a warning.
=> Auth tests - set warning to false

source/transactions/tests/commit.json, source/transactions/tests/commit.yml
Kevin noticed a bug in my C Driver implementation that wasn't caught by any spec test: even an empty transaction must still spend a txnNumber.
=> Test that an empty commit increments txnNumber

source/transactions/tests/commit.json, source/transactions/tests/commit.yml
Should I expand this and test every operation that can be performed (delete, update, find, agg, etc..) or do you think a single case is enough? My assumption is that there is a single place the driver should reset the sate and that a single test is enough. I want to avoid creating a combinatorial explosion of tests.
=> SPEC-1092 Test reset session state to "no transaction"

source/command-monitoring/tests/insertMany.json, source/command-monitoring/tests/insertMany.yml
The command monitoring bulk tests were updated to use a different syntax for options, but a few places in the insertMany file were missed.
=> fix unchanged command monitoring options to follow previous changes

source/retryable-writes/tests/retryableErrors.json, source/retryable-writes/tests/retryableErrors.yml
Update the failCommand failpoint with "failCommands" so that the failpoint is reliable on a multi-member replica set (https://jira.mongodb.org/browse/SERVER-34943).
The "failCommands" argument was added in SERVER-35004.
=> SPEC-1071 Specify which commands to fail in failCommand

source/transactions/tests/README.rst, source/transactions/tests/retryable-writes.json, source/transactions/tests/retryable-writes.yml
Adds a test to ensure that drivers do not retry insert operations within a transaction even when retryWrites=true. Also adds errorLabelsContain and ErrorLabelsOmit to verify that the insert operation raises an exception with the "TransientTransactionError" error label.
I've only added a single test (of insertOne) for now. We can expand this to test more write operations when we agree on the format.
=>  SPEC-1085 Test that writes are not retried inside a transaction

source/transactions/tests/README.rst, source/transactions/tests/retryable-abort.json, source/transactions/tests/retryable-abort.yml, source/transactions/tests/retryable-commit.json, source/transactions/tests/retryable-commit.yml
Tests that commitTransaction and abortTransaction are retried once after the retryable errors in https://github.com/mongodb/specifications/blob/master/source/retryable-writes/retryable-writes.rst#terms. The errors that I've skipped testing for now are write concern errors. That will be done as part of https://jira.mongodb.org/browse/SPEC-1090.
=> SPEC-1083 Test commit/abortTransaction commands are retried

source/transactions/tests/retryable-abort.json, source/transactions/tests/retryable-abort.yml, source/transactions/tests/retryable-commit.json, source/transactions/tests/retryable-commit.yml
Tests commit/abortTransaction behavior with writeConcernErrors containing error codes Interrupted, InterruptedAtShutdown, InterruptedDueToReplStateChange, PrimarySteppedDown, and ShutdownInProgress.
CC: @kevinAlbs
=> SPEC-1106 Test commit/abortTransaction with retryable writeConcernErrors

source/crud/tests/read/count.json
For some reason the js-yaml did not convert this one properly.
=> Fixing JSON version of count crud test

source/change-streams/change-streams.rst
The spec clearly states for each change stream option whether it is (a) an option of the `$changeStream` aggregation stage or (b) an aggregation command option. This had not been the case for the recently added `startAtOperationTime` option and this change fixes that.
=> Specify that startAtOperationTime is a changeStream option

source/transactions/tests/README.rst, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml, source/transactions/transactions.rst
When commitTransaction fails with a retryable writes error it is also labelled UnknownTransactionCommitResult.
=>  SPEC-1112 Retryable writes errors are labelled UnknownTransactionCommitResult

source/change-streams/tests/change-streams.json, source/change-streams/tests/change-streams.yml
startAtOperation time is no longer automatically added to the command - so examples can be removed from the tests.
SPEC-1114
=> Updated change stream tests

source/change-streams/tests/README.rst
Fixes:
- Formatting issue that was causing subfields of 'operations' to show up as a paragraph instead on a nested, bulleted list.
- The field corresponding to the name of the command to be run was specified incorrectly as `commandName` instead of `name`.
=> Minor fixes to change stream spec tests README

source/transactions/transactions.rst
This clears some ambiguity surrounding read preferences, reinforcing behavior specified elsewhere in the spec.
=> Clarify behavior of operation-level `readPreference`

source/read-write-concern/read-write-concern.rst
I'm implementing `ReadConcern` for the Swift driver, and I found this section a bit confusing. I've updated it to clarify. This is how @mbroadst and I interpreted it, let us know if it's incorrect.
=> Clarify when to send a command's ReadConcern

source/enumerate-collections.rst
nameOnly doesn't allow filters on anything other than `name`.
=> Clarify use of nameOnly in collection enumeration

source/change-streams/tests/README.rst
This test appears to date back to the original spec commit in 9784d5d2fd52f36b15ff41d262ab171d3968ab0a; however, it does not jive with the spec's current language, which states that errors on aggregate commands are never to be retried. Only errors from getMore commands may be considered resumable.
Adding @mbroadst since this was his original commit and @kevinAlbs since he recently worked on error logic in https://github.com/mongodb/specifications/commit/7021f759c4c2a918808660a2e4e55ba1f4e4acb5.
=> Correct prose test for not resuming during an aggregate

source/crud/crud.rst
This came up in https://github.com/mongodb/mongo-swift-driver/pull/83#discussion_r199623171.
The doc block here already includes a reference to "FAQ about the previous bulk API and how it relates to this". I feel that's going to do a better job of explaining how the implementation should operate.
The existing text seemed odd because `requests` is really split into one or more batches depending on the operation types, their order in the array, and value of the `ordered` option. Also "at the same time" may be misleading (depending on how it is understood), since batches are sent in sequence and not concurrently.
=> Revise description for bulkWrite() method

source/wireversion-featurelist.rst
With data from https://github.com/mongodb/mongo/blob/master/src/mongo/db/wire_version.h, but potentially not complete in the description
=> Added new wire protocol versions

source/transactions/tests/read-concern.json, source/transactions/tests/read-concern.yml
Adds tests that readConcern is only added for the initial command in a transaction. None of the existing tests cover this case. Tests countDocuments, find, aggregate, distinct, and runCommand.
These changes are tested by the python driver.
=> SPEC-1121 Test only initial commands include readConcern

source/crud/tests/write/bulkWrite-arrayFilters.json, source/crud/tests/write/bulkWrite-arrayFilters.yml, source/retryable-writes/tests/bulkWrite-serverErrors.json, source/retryable-writes/tests/bulkWrite-serverErrors.yml, source/retryable-writes/tests/bulkWrite.json, source/retryable-writes/tests/bulkWrite.yml, source/transactions/tests/bulk.json, source/transactions/tests/bulk.yml, source/transactions/tests/transaction-options.json, source/transactions/tests/transaction-options.yml
https://jira.mongodb.org/browse/SPEC-1136
`insertedCount` is a required BulkWriteResult field, so there's no reason we shouldn't include it in the expectation.
=> SPEC-1136: Add insertedCount to BulkWriteResult

source/change-streams/change-streams.rst
https://jira.mongodb.org/browse/SPEC-1124
Per the SDAM spec, the numeric codes for errors that may contain "not master" or "node is recovering" do not overlap with the three error codes specifically excluded by the change stream spec. Therefore, such errors should already be considered resumable based on the second criterion.
=> SPEC-1124: Checking error messages for resumable errors is redundant

source/crud/tests/README.rst, source/read-write-concern/tests/README.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-selection/tests/README.rst
This copypasta was no longer accurate, as specs are still revised after being initially published and tags are not used consistently.
=> Update blurb about spec file versioning

source/crud/tests/write/updateMany-arrayFilters.json, source/crud/tests/write/updateMany-arrayFilters.yml
@kmahar pointed out that I missed this in https://github.com/mongodb/specifications/pull/376.
=> SPEC-1135: Add upsertedCount to missed UpdateResult

source/server-discovery-and-monitoring/tests/rs/secondary_ignore_ok_0.json, source/server-discovery-and-monitoring/tests/rs/secondary_ignore_ok_0.yml
This tests the bug that was found in the SDAM implementation of the Ruby driver. I verified that it failed the test before the fix and passes the test after.
=> add test that "ok: 0" from secondary is ignored

source/crud/crud.rst
This removes a line that was added in 1d765dd6b7c8452c4664794e1e69b4590d001bdc. The findAndModify command does not use opcodes, so the note combining arrayFilters with an unacknowledged write concern does not apply.
@saghm I believe the original addition in your commit was a copy/paste error, but please confirm.
=> Remove FindOneAndUpdateOptions note about opcodes

source/crud/tests/README.rst, source/crud/tests/write/bulkWrite.json, source/crud/tests/write/bulkWrite.yml
https://jira.mongodb.org/browse/SPEC-870
Note: this does not entail testing expected commands with APM (to be done [SPEC-1133](https://jira.mongodb.org/browse/SPEC-1133)). We're just adding additional tests for `bulkWrite()` using the existing format.
The JSON tests in this PR have been successfully tested against the PHP and Swift drivers, both of which assert all fields in the result document (including spec-optional fields such as `insertedIds`).
=> SPEC-870: Additional bulkWrite() spec tests

source/retryable-writes/tests/README.rst, source/retryable-writes/tests/deleteMany.json, source/retryable-writes/tests/deleteMany.yml, source/retryable-writes/tests/updateMany.json, source/retryable-writes/tests/updateMany.yml
These CRUD operations are not retryable, so they should ignore
retryWrites=true in the URI and not set the txnId.
=> SPEC-1160 Test delete/updateMany with retryWrites

source/crud/tests/README.rst, source/crud/tests/write/bulkWrite.json, source/crud/tests/write/bulkWrite.yml, source/crud/tests/write/insertMany.json, source/crud/tests/write/insertMany.yml
https://jira.mongodb.org/browse/SPEC-1142
These are the first CRUD tests to trigger an error (and use ordered=false, if that matters). Some test harnesses may need revisions to detect the error and possibly extract a write result from the error for additional assertions.
I had to update PHPLIB's test runner and am currently in the process of updating Swift's.
=> SPEC-1142: Test continue-on-error behavior with unordered insertMany() and bulkWrite()

source/transactions/tests/read-concern.json, source/transactions/tests/read-concern.yml, source/transactions/transactions.rst
The Transactions Spec says, "Drivers MUST override all other collection,
database, or client readConcerns with the transaction’s readConcern.
Drivers MUST add this readConcern to the first command in a transaction
if and only if the readConcern is supplied and not the default."
I believe this applies when a transaction has *no* readConcern as well:
drivers ignore collection, database, or client readConcern and use no
readConcern in this case.
When I synced the tests for SPEC-1121, I found a new libmongoc bug, CDRIVER-2841. We *do* obey the rule, "Only send readConcern in the first transaction command." But it's the wrong readConcern: it should be the transaction's readConcern, not the collection's. This test further proves that drivers follow the readConcern rules in transactions.
=> SPEC-1161 Test that txn reads don't inherit readConcern

source/server-discovery-and-monitoring/tests/rs/primary_becomes_ghost.json, source/server-discovery-and-monitoring/tests/rs/primary_becomes_ghost.yml, source/server-discovery-and-monitoring/tests/rs/primary_becomes_mongos.json, source/server-discovery-and-monitoring/tests/rs/primary_becomes_mongos.yml
This is in addition to the existing test for primary becoming standaone.
=> Add tests for RS primary becoming ghost and mongos

source/server-discovery-and-monitoring/tests/rs/equal_electionids.json, source/server-discovery-and-monitoring/tests/rs/equal_electionids.yml, source/server-discovery-and-monitoring/tests/rs/new_primary_new_electionid.json, source/server-discovery-and-monitoring/tests/rs/new_primary_new_electionid.yml, source/server-discovery-and-monitoring/tests/rs/new_primary_new_setversion.json, source/server-discovery-and-monitoring/tests/rs/new_primary_new_setversion.yml, source/server-discovery-and-monitoring/tests/rs/null_election_id.json, source/server-discovery-and-monitoring/tests/rs/null_election_id.yml, source/server-discovery-and-monitoring/tests/rs/primary_disconnect_electionid.json, source/server-discovery-and-monitoring/tests/rs/primary_disconnect_electionid.yml, source/server-discovery-and-monitoring/tests/rs/primary_disconnect_setversion.json, source/server-discovery-and-monitoring/tests/rs/primary_disconnect_setversion.yml, source/server-discovery-and-monitoring/tests/rs/setversion_without_electionid.json, source/server-discovery-and-monitoring/tests/rs/setversion_without_electionid.yml, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid.json, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid.yml
Existing specs verify set version & election id on individual servers. This PR adds verification of max of both of those on topologies.
Implemented in Ruby in https://github.com/mongodb/mongo-ruby-driver/pull/1117.
=> Verify max set version and max election id on topologies

source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-1169
=> SPEC-1169: Aggregate with $out should not specify batchSize

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Which is to stop processing & possibly transition to no primary if affected server was a primary.
=> Handling for mismatched RS name should be the same as me mismatch

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
I couldn't find where the spec said to change topology type to RS with primary. This point is explicitly defined for other topology type transitions.
There are two ways of doing this - either conditionally in updateRSFromPrimary based on whether the topology is already ReplicaSetWithPrimary, or unconditionally in two places where we go from another topology to ReplicaSetWithPrimary. This PR proposes the second route.
=> Specify when topology type unknown becomes RS with primary

source/transactions/tests/insert.json, source/transactions/tests/insert.yml
Jira: https://jira.mongodb.org/browse/SPEC-1096
The new test passes locally with pymongo.
=> SPEC-1096 Add transaction test with session1 in APM expectations

source/transactions/tests/README.rst
Jira: https://jira.mongodb.org/browse/SPEC-1179
Discovered and fixed in PyMongo: https://jira.mongodb.org/browse/PYTHON-1691
We must use "local" to ensure we read our own writes even when a test runs a write with w=1 and the find would otherwise be run with "majority" read concern.
=> SPEC-1179 Transaction tests require local read concern for final find

source/change-streams/change-streams.rst
Revises previous note from https://github.com/mongodb/specifications/pull/257
This came up while responding to https://github.com/mongodb/specifications/pull/422/files#r238470484.
=> Clarify that maxAwaitTimeMS is neither an aggregate nor $changeStream option

source/server-selection/server-selection.rst, source/transactions/tests/README.rst, source/transactions/tests/commit.json, source/transactions/tests/commit.yml, source/transactions/tests/pin-mongos.json, source/transactions/tests/pin-mongos.yml, source/transactions/tests/transaction-options.json, source/transactions/tests/transaction-options.yml, source/transactions/transactions.rst
Jira: https://jira.mongodb.org/browse/SPEC-1140
This change adds the "Mongos Pinning for Sharded Transactions" section to the transactions spec and updates the tests for 4.2 sharded transactions.
I have run the tests against a 4.1.6 sharded cluster with two mongoses, see [PYTHON-1673](https://jira.mongodb.org/browse/PYTHON-1673).
Some open questions:
```python
with client.start_session() as s:
with s.start_transaction():
client.test.test.insert_one({}, session=s) 
client.test.test.find_one({}, session=s)
doc = client.test.test.find_one({}, session=s)
```
=> SPEC-1140 Support mongos pinning for sharded transactions

source/crud/crud.rst
If a `$changeStream` stage is run in an aggregation, a tailable
awaitdata cursor is returned and therefore `maxAwaitTimeMS` should
apply.
SPEC-1034
=> feat(crud): document support for `maxAwaitTimeMs` in aggregate

source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst
Hopefully, no one implemented the table literally, but since I'm reviewing SDAM monitoring for the Perl driver, I figured I should fix it for posterity.
=> Fix table of SDAM monitoring readable/writable rules

source/bson-corpus/tests/datetime.json
This tests the bug discovered in [CDRIVER-2910](https://jira.mongodb.org/browse/CDRIVER-2910). I see an argument being made that the bug is pretty specific and likely wouldn't catch bugs in other drivers. But since the fix should be tested in the C driver, it seemed wasteful not to add it here too.
=> Test leading zeroes in datetime ms

source/server-selection/server-selection.rst
[SPEC-1186](https://jira.mongodb.org/browse/SPEC-1186)
This PR updates a very small `tag_sets` example to use only String values in the tag set as it does in other specs.
=> SPEC-1186 Fix Server Selection Spec non-string value in tag_set example

source/transactions/tests/commit.json, source/transactions/tests/commit.yml, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml, source/transactions/tests/retryable-commit.json, source/transactions/tests/retryable-commit.yml, source/transactions/transactions.rst
https://jira.mongodb.org/browse/SPEC-1185
Opening the PR with just the spec language change. Test changes will be added in time.
=> SPEC-1185: Apply majority write concern when retrying commitTransaction

source/retryable-reads/tests/README.rst
@vincentkam: I think this was an oversight in #431. The tests have `error` as a child of `operations`, but the README file showed it one level up (sibling of `operations` and `expectations`).
=> Move error field under operations (like result)

source/transactions-convenient-api/tests/commit-writeconcernerror.json, source/transactions-convenient-api/tests/commit-writeconcernerror.yml
See https://github.com/mongodb/specifications/pull/435#discussion_r251951402
=> Use a less contrived error message for non-wtimeout WC error

source/transactions-convenient-api/tests/commit-writeconcernerror.json, source/transactions-convenient-api/tests/commit-writeconcernerror.yml
https://jira.mongodb.org/browse/SPEC-1197
No driver changes were needed for SPEC-1197, so this test should not be skipped.
=> SPEC-1197: Remove skip in withTransaction test

source/transactions-convenient-api/tests/commit-writeconcernerror.json, source/transactions-convenient-api/tests/commit-writeconcernerror.yml
Until SERVER-39292 is completed, we cannot specify a `closeConnection`
with a `failCommand` that includes a `writeConcernError`.
=> fix(convenient-txns): don't send `closeConnection` to fail command

source/transactions-convenient-api/tests/transaction-options.json, source/transactions-convenient-api/tests/transaction-options.yml
`callback` was moved into the `arguments` yesterday, but we forgot
to include `transactionOptions` here as well. Additionally, the
`transactionOptions` were renamed `options` to be consistent with
the transactions spec test format.
=> fix(convenient-txns): `transactionOptions` => `options`

source/command-monitoring/tests/bulkWrite.json, source/command-monitoring/tests/bulkWrite.yml, source/command-monitoring/tests/updateMany.json, source/command-monitoring/tests/updateMany.yml, source/command-monitoring/tests/updateOne.json, source/command-monitoring/tests/updateOne.yml
https://jira.mongodb.org/browse/SPEC-1049
CRUD spec does not require drivers to always specify a value for these fields. Note that some drivers do always specify a value (mostly for historical reasons, when we expected a future database version might change its default), but the spec tests should not be so strict.
=> SPEC-1049: Do not expect default upsert/multi values for update

source/connection-monitoring-and-pooling/tests/pool-checkout-multiple.json, source/connection-monitoring-and-pooling/tests/pool-checkout-multiple.yml, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.json, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.yml
When implementing the CMAP spec test runner, it was suggested that I have it sleep in between each operation being run in order to facilitate separate threads performing operations in a more deterministic order. Given that there are only two places in the tests where comments suggest that the operations may not be deterministic and that the spec runner description already provides a mechanism for specifying sleeps of a given length, it probably makes more sense to just add `wait` operations in the places where they're needed to save each implementation from having to do it manually. As an added bonus, this also makes the test run faster, as it greatly cuts down on the total amount of time the runner needs to sleep.
=> add sleeps to make cmap tests more consistent

source/connection-monitoring-and-pooling/tests/pool-create-max-size.json, source/connection-monitoring-and-pooling/tests/pool-create-max-size.yml, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.json, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.yml
I found another place in the CMAP tests that need a sleep. In order to ensure that the final `ConnectionCheckoutStarted` event happens before the final `ConnectionCheckedIn` event, we need to give the thread time to start the checkout. (It shouldn't actually matter what order they happen for the purpose of testing behavior, but making the events occur more deterministically makes the tests pass more easily).
I've also pushed a second commit adding a fourth wait to the wait-queue-fairness.yml test which I should have added in the previous PR.
=> add additional sleep needed for cmap test

source/transactions/transactions.rst
Related to some questions @jyemin brought up in Slack about interpreting the “Why don’t drivers retry after write concern timeout errors?” FAQ entry in light of the `withTransaction()` spec, which _does_ retry for wtimeout errors (see: #478). @ShaneHarvey suggested rephrasing this question so it's clear that it only pertains to the internal retry-once logic discussed in the Transactions spec.
I only refer to `commitTransaction` here, as `abortTransaction` doesn't talk about wtimeout errors at all. `abortTransaction` is only retried once after a retryable error, which excludes wtimeout. Drivers also don't report errors for `abortTransaction` (so there is no label to check) and applications aren't supposed to call abort a second time, so I don't think there's any need to discuss aborts for …
=> Clarify FAQ about not automatically retrying commit after wtimeout

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
Remove "handshakeFailed" from enumeration of possible reasons for
a ConnectionClosedEvent.
=> Remove "handshakeFailed" reason

source/crud/tests/v2/bulkWrite-arrayFilters.json, source/crud/tests/v2/bulkWrite-arrayFilters.yml
While https://jira.mongodb.org/browse/SPEC-1215 is still in progress, we should stick to the old paradigm of using `42` to match 'any value' and `null` to indicate 'must not exist'.
=> Revert to using null instead of rejected $exists operator to assert non-existent fields

source/crud/tests/v1/write/bulkWrite.json, source/crud/tests/v1/write/bulkWrite.yml
Closes https://jira.mongodb.org/browse/SPEC-1223
=> SPEC-1223: Remove bulkWrite test operation whose result depends on document key-order

source/transactions-convenient-api/tests/callback-retry.json, source/transactions-convenient-api/tests/callback-retry.yml, source/transactions/tests/abort.json, source/transactions/tests/abort.yml, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml
The old behavior was:
```
> session.startTransaction()
> session.getDatabase("test").runCommand({
insert: 'c', 
documents: [{_id: 0}, {_id: 0}]
})
{
"ok" : 0,
"errmsg" : "duplicate key error",
"code" : 11000,
"codeName" : "DuplicateKey"
}
```
The behavior after https://jira.mongodb.org/browse/SERVER-38583 is:
```
{
"ok" : 1,
"n" : 1,
"writeErrors" : [
{
"index" : 1,
"code" : 11000,
"errmsg" : "duplicate key error"
}
]
}
```
This error reporting change is going to be backported to 4.0.
For now I simply removed the `errorCodeName: DuplicateKey` assertions to get the tests to pass regardless of how the error is reported. Alternatively we could change the definition of `errorCodeName` to also look at error codes in `writeErrors` but since writeErrors don't have `codeName` we would either need …
=> SPEC-1221 DuplicateKey error is not reported as a top-level command error

source/change-streams/change-streams.rst, source/driver-bulk-update.rst, source/gridfs/gridfs-spec.rst, source/retryable-writes/tests/README.rst, source/server_write_commands.rst
[SPEC-1222](https://jira.mongodb.com/browse/SPEC-1222)
I didn't update any of the changelogs since this *should not* require changes in behavior in any of the drivers, since they have been interpreting KB as KiB already. This is just a clarification for new drivers.
`MaxMessageSizeBytes` is defined to be actually 48MB (in SI units, so 48,000,000 bytes).
The benchmarking spec explicitly uses the SI definition of MB, so that has also been left unchanged.
=> SPEC-1222 Standardize units of bytes

source/crud/tests/v2/db-aggregate.json, source/crud/tests/v2/db-aggregate.yml
When running these CRUD tests against a sharded cluster the
`$currentOp` stage will likely return many results, occasionally
too many to return the initiating aggregtion command we expect
to see in the results. Limiting the stage to return only local
operations corrects the race condition.
=> test(db-aggregate): only check local operations in $currentOp test

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Although the specification lists error code names, these names
may be changed by the server at any time (for example, 4.0 still
uses InterruptedDueToReplStateChange while 4.1 uses
InterruptedDueToStepDown for 11602). Explicitly state that
code names are not to be used for matching.
=> Require that driver matches error code and not code name.

source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-multiple.json, source/connection-monitoring-and-pooling/tests/pool-checkout-multiple.yml, source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.json, source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.yml, source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.json, source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.yml, source/connection-monitoring-and-pooling/tests/pool-create-max-size.json, source/connection-monitoring-and-pooling/tests/pool-create-max-size.yml, source/connection-monitoring-and-pooling/tests/pool-create-min-size.json, source/connection-monitoring-and-pooling/tests/pool-create-min-size.yml, source/connection-monitoring-and-pooling/tests/pool-create-with-options.json, source/connection-monitoring-and-pooling/tests/pool-create-with-options.yml, source/connection-monitoring-and-pooling/tests/pool-create.json, source/connection-monitoring-and-pooling/tests/pool-create.yml, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.json, source/connection-monitoring-and-pooling/tests/wait-queue-fairness.yml, source/connection-monitoring-and-pooling/tests/wait-queue-timeout.json, source/connection-monitoring-and-pooling/tests/wait-queue-timeout.yml
This is the solution that I arrived at to address the race conditions we were seeing: I added a `waitForEvent` command which operates as follows:
- Every thread keeps track of what events have occurred in a queue*
- When a `waitForEvent` command happens on a thread, the thread dequeues events until the necessary event is found
- If the event was not in the queue, the thread blocks until the event occurs.
Does this sound like a reasonable solution? If so, I'll update the README to include this command.
=> Updating cmap spec tests with waitForEvent

source/transactions/tests/README.rst
This was changed in https://github.com/10gen/mongo-orchestration/pull/267.
=> SPEC-1168 mongo-orchestration reduces transaction timeout

source/uri-options/tests/tls-options.json, source/uri-options/tests/tls-options.yml
I realized that some implementations would have order-dependent processing of the TLS options, so added some more variants that test the reverse order.
=> Add more variants of the TLS-related URI options tests

source/transactions/tests/README.rst, source/transactions/transactions.rst
Also fixes some rst syntax errors found via:
```
pip install docutils
rst2html.py transactions/transactions.rst > output.html
transactions/transactions.rst:991: (WARNING/2) Title underline too short.
Drivers add the "TransientTransactionError" label to network errors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
transactions/transactions.rst:991: (WARNING/2) Title underline too short.
Drivers add the "TransientTransactionError" label to network errors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
rst2html.py transactions/tests/README.rst > output.html
transactions/tests/README.rst:465: (WARNING/2) Duplicate explicit target name: "server-39349".
transactions/tests/README.rst:467: (SEVERE/4) Title level inconsistent:
**Changelog** …
```
=> SPEC-1168 Drivers must disable targetedFailPoint

source/crud/tests/v1/read/aggregate-out.json, source/crud/tests/v1/read/aggregate-out.yml
Drivers are not required to provide a cursor against the collection
indicated in a `$out`. The presence of a `result` as well as
`collection` fields in this test is inconsistent with the rest of
the crud tests, and makes it difficult for implementations to
share common code for checking expectations without writing very
specific code to check for this isolated case.
=> test(crud): remove `result` expectation for $out agg test

source/transactions/tests/write-concern.json, source/transactions/tests/write-concern.yml
Jira: https://jira.mongodb.org/browse/SPEC-1125
These tests prove that a collection configured with WriteConcern(w=0) can still be used within a transaction. I added tests for all the supported CRUD methods for completeness.
Passing python driver patch: https://evergreen.mongodb.com/version/5ca66d46e3c33119ed332b5c
=> SPEC-1125 Test collection unack'd write concern is compatible with transactions

source/change-streams/change-streams.rst, source/change-streams/tests/README.rst
As it was proposed in the ticket and discussed in the slack with @kevinAlbs, I've added only `prose` tests.
In addition to the tests which were proposed/discussed with Kevin, I also added one more common test for tracking `postBatchResumeToken`.
=> SPEC-1194: Add tests for `postBatchResumeToken` support.

source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_removal.json, source/server-discovery-and-monitoring/tests/monitoring/replica_set_with_removal.yml
Background: currently, there are tests for SDAM state transitions ("sdam") and some of the events generated by SDAM flow ("sdam monitoring"), but there are areas not covered by the existing monitoring tests, specifically:
- server removal/server close events
- some situations when the first response is not from primary
- multiple servers responding
The existing "sdam" tests cover topology outcomes in most of these cases, but those tests do not specify the order in which events should be published (or event contents, but this is a minor point).
Therefore, #410 proposes to add a number of "sdam monitoring" tests to formalize the order of sdam events being published in various situations.
In order for the new tests to be possible, a change in spec runner is necessary which is to perform …
=> SPEC-1170: SDAM monitoring multi phase testing

source/change-streams/tests/README.rst
This is necessary because a change stream on server versions >= 4.0.7 will cache the `postBatchResumeToken` from the initial aggregate response and use that for resuming rather than the cached operation time.
=> Fix server version constraints for startAtOperationTime prose test

source/server-discovery-and-monitoring/tests/rs/incompatible_ghost.json, source/server-discovery-and-monitoring/tests/rs/incompatible_ghost.yml
Ghosts are not expected to have either a setName or a hosts list
=> Fix incompatible ghost spec test

source/retryable-writes/tests/README.rst, source/transactions/tests/README.rst
If this looks good, I'll update the [`failCommand` wiki page](https://github.com/mongodb/mongo/wiki/The-%22failCommand%22-fail-point#failcommand-parameters) after merging. That page should clarify exactly whether the command is executed if `closeConnection` or `errorCode` is used.
cc: @lankas can you chime in here, since you originally implemented [SERVER-35004](https://jira.mongodb.org/browse/SERVER-35004)?
=> Clarify failCommand behavior for writes

source/transactions-convenient-api/tests/commit-retry.json, source/transactions-convenient-api/tests/commit-retry.yml, source/transactions-convenient-api/tests/commit-writeconcernerror.json, source/transactions-convenient-api/tests/commit-writeconcernerror.yml, source/transactions-convenient-api/transactions-convenient-api.rst, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml, source/transactions/tests/transaction-options.json, source/transactions/tests/transaction-options.yml, source/transactions/transactions.rst
Jira: https://jira.mongodb.org/browse/SPEC-1206
Changes:
- TransactionOptions gains a new max_time_ms option. 
- MaxTimeMSExpired errors on commit (both `{ok:0, code: 50, codeName: "MaxTimeMSExpired"}` and `{ok:1, writeConcernError: {code: 50, codeName: "MaxTimeMSExpired"}}`) are labelled UnknownTransactionCommitResult.
- withTransaction does not retry commit after a MaxTimeMSExpired error. Aly requested that MaxTimeMSExpired halt any retry attempts.
I have a POC in pymongo implemented here: https://github.com/ShaneHarvey/mongo-python-driver/tree/SPEC-1206
Here is a passing patch build: https://evergreen.mongodb.com/version/5cc0e14230661576bcab0b82 (note the failures are due to [PYTHON-1796](https://jira.mongodb.org/browse/PYTHON-1796)/[SERVER-40685](https://jira.mongodb.org/browse/SERVER- …
=> SPEC-1206 Support maxTimeMS on transaction commit

source/sessions/driver-sessions.rst
Since transactions have been implemented, language referring to transactions in the future tense can be updated.
=> Update transaction-related note in sessions spec 

source/transactions/tests/README.rst
Prior to SERVER-38335, killAllSessions might kill its own session (implicit or explicit). In practice, this does not pose a risk for blocking subsequent tests due to a lingering, open transaction so drivers should be OK to simply disregard this error.
=> Note that drivers can ignore killAllSessions interruptions

source/transactions/tests/README.rst
This was not immediately clear to me when implementing the test runner in PHPLIB. As a result, I was passing the map itself to `startSession`, which resulted in all options being ignored.
=> Note that sessionOptions is a map

source/change-streams/tests/README.rst
This minor change makes the prose test apply always, and provides context for what type of errors to expect for different wire versions.
=> SPEC-1211 require missing resume token test always

source/auth/auth.rst
Command names are case sensitive.
```
> db.runCommand({getnonce: 1})
{ "nonce" : "810478340848c1fe", "ok" : 1 }
> db.runCommand({getNonce: 1})
{
"ok" : 0,
"errmsg" : "no such command: 'getNonce'",
"code" : 59,
"codeName" : "CommandNotFound"
}
```
=> getNonce => getnonce

source/server-selection/server-selection.rst
https://jira.mongodb.org/browse/SPEC-1292
I'm open to adding a prose test for this, but currently there is nothing covering the existing behavior.
=> SPEC-1292: Add rule to ignore read preference for standalone servers

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/pool-create-with-options.json, source/connection-monitoring-and-pooling/tests/pool-create-with-options.yml
This PR fixes the `pool-create-with-options.yml` test to ignore ConnectionReadyEvent. Without ignoring this error my test runner fails with this error:
```
FAIL: test_cmap_pool_create_with_options_must_be_able_to_start_a_pool_with_various_options_set (test.test_cmap.TestCMAP)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/shane/git/mongo-python-driver/test/__init__.py", line 410, in wrap
return f(*args, **kwargs)
File "/Users/shane/git/mongo-python-driver/test/test_cmap.py", line 285, in run_scenario
self.run_scenario(scenario_def, test)
File "/Users/shane/git/mongo-python-driver/test/test_cmap.py", line 277, in run_scenario
self.check_events(test['events'], test['ignore'])
File …
```
=> SPEC-1311 Ignore ConnectionReadyEvent in pool creation test

source/crud/tests/v2/db-aggregate.json, source/crud/tests/v2/db-aggregate.yml
Closes [SPEC-1312](https://jira.mongodb.org/browse/SPEC-1312).
Note that `$project` does not support fields with names starting in `$`. Here is the relevant error message:
```
FieldPath field names may not start with '$'.
```
Consequently, I have removed the `$db` field from `result`. However, this doesn't seem to be an issue since the `$currentOp` pipeline stage cannot be run against any other database:
```
MongoDB Enterprise mongos> db.aggregate([{ "$currentOp" : {}}])
2019-06-06T13:01:33.928-0700 E QUERY    [js] Error: command failed: {
"ok" : 0,
"errmsg" : "$currentOp must be run against the 'admin' database with {aggregate: 1}",
"code" : 73,
"codeName" : "InvalidNamespace",
"operationTime" : Timestamp(1559851290, 2),
"$clusterTime" : {
"clusterTime" : Timestamp(1559851290, 2), …
```
=> SPEC-1312 Project out all relevant fields in database-level aggregation tests

source/change-streams/change-streams.rst
Fixes a typo introduced in https://github.com/mongodb/specifications/commit/dece0402de347817fe1a812be5de1bdf2cef2608#diff-875f237661962b4ca9b2e58d97449831R510 for [SPEC-1263](https://jira.mongodb.org/browse/SPEC-1263). Per [SPEC-1194](https://jira.mongodb.org/browse/SPEC-1194) and [SERVER-35740](https://jira.mongodb.org/browse/SERVER-35740), this was introduced in 4.0.7.
=> SPEC-1263: Fix server version for addition of postBatchResumeToken

source/client-side-encryption/tests/README.rst, source/client-side-encryption/tests/generate.py, source/client-side-encryption/tests/missingKey.json, source/client-side-encryption/tests/missingKey.yml, source/client-side-encryption/tests/missingKey.yml.template
Now explicitly says that "admin.datakeys" is the default. And changes the "missingKeys" test to validate that we pass the keyVaultNamespace option through and use it.
I validated on the old Java test runner (on j3071) with a change to add keyVaultNamespace. Though the Java test runner has changed a lot, so I don't have a PR for the newest test runner.
=> SPEC-1321 test keyVaultNamespace

source/auth/tests/connection-string.json, source/auth/tests/connection-string.yml, source/crud/tests/v2/aggregate-out-readConcern.json, source/crud/tests/v2/bulkWrite-arrayFilters.json, source/crud/tests/v2/db-aggregate.json
The YAML in the most recent changes to the auth spec tests was invalid, which caused the generation to JSON to fail when I attempted to run it for a different change. I've fixed it and generated the JSON again (which also picked up some unrelated changes to the CRUD spec tests, which were also updated without the makefile being run).
=> Fix yaml typo

source/client-side-encryption/corpus/corpus-encrypted.json, source/client-side-encryption/corpus/corpus-key-aws.json, source/client-side-encryption/corpus/corpus-key-local.json, source/client-side-encryption/corpus/corpus-schema.json, source/client-side-encryption/corpus/corpus.json, source/client-side-encryption/etc/generate-corpus.py, source/client-side-encryption/tests/README.rst
This adds an exhaustive way of testing encryption and decryption of FLE with a single document where each field is encrypted in a different way by enumerating the matrix with the following axes:
- KMS (local, aws)
- BSON type
- algorithm (random, deterministic)
- method (explicit, automatic)
- key identifier (_id, keyAltName)
The test is also run with local and remote configured schema.
In the process of generating this corpus with the Java driver, this caught multiple bugs:
(CDRIVER-3204, CDRIVER-3205, CDRIVER-3216, JAVA-3335, SERVER-41994).
=> SPEC-1339 add FLE corpus test

source/change-streams/change-streams.rst
Drivers that have idiomatic ways of disposing resources shouldn't have to implement the close function.
=> SPEC-1343 Clarify requirements for a "close" function

.travis.yml
This adds a Travis job that will fail if JSON regeneration changes any files in the repository.
Closes https://github.com/mongodb/specifications/issues/593
=> Update .travis.yml to test JSON regeneration 

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-error-closed.json, source/connection-monitoring-and-pooling/tests/pool-checkout-error-closed.yml
Is there any way to add a spec test for this? If not I can add a prose test.
=> SPEC-1298 Add "connectionError" as a valid reason for ConnectionCheckOutFailedEvent

source/connection-string/tests/invalid-uris.json, source/connection-string/tests/invalid-uris.yml
https://jira.mongodb.org/browse/SPEC-1349
=> SPEC-1349: Expanding test coverage for percent encoding in connection strings

source/change-streams/change-streams.rst, source/change-streams/tests/README.rst
Supersedes #580 
Prose tests had to be added instead of spec tests because the spec test format does not provide a way to initialize a change stream with a valid `startAfter` token.
=> SPEC-1335 clarify resume process for changeStreams started with startAfter

source/retryable-reads/tests/changeStreams-client.watch-serverErrors.json, source/retryable-reads/tests/changeStreams-client.watch-serverErrors.yml, source/retryable-reads/tests/changeStreams-client.watch.json, source/retryable-reads/tests/changeStreams-client.watch.yml, source/retryable-reads/tests/changeStreams-db.coll.watch-serverErrors.json, source/retryable-reads/tests/changeStreams-db.coll.watch-serverErrors.yml, source/retryable-reads/tests/changeStreams-db.coll.watch.json, source/retryable-reads/tests/changeStreams-db.coll.watch.yml, source/retryable-reads/tests/changeStreams-db.watch-serverErrors.json, source/retryable-reads/tests/changeStreams-db.watch-serverErrors.yml, source/retryable-reads/tests/changeStreams-db.watch.json, source/retryable-reads/tests/changeStreams-db.watch.yml
This was overlooked in #600 
Tested on PyMongo.
=> SPEC-1350 [Follow up] Remove fullDocument field from retryableReads spec tests

source/change-streams/tests/README.rst
Closes [SPEC-1367](https://jira.mongodb.org/browse/SPEC-1367)
Also renumbers changeStreams prose tests with fixed numbers in accordance with [SPEC-1364](https://jira.mongodb.org/browse/SPEC-1364).
=> Remove startAfter from changeStream test meant for server version <4.0.7

source/crud/tests/v2/aggregate-merge.json, source/crud/tests/v2/aggregate-merge.yml, source/retryable-reads/tests/aggregate-merge.json, source/retryable-reads/tests/aggregate-merge.yml
https://jira.mongodb.org/browse/SPEC-1289
`$merge` was added in 4.1.11 in [SERVER-40429](https://jira.mongodb.org/browse/SERVER-40429). 
In https://github.com/mongodb/mongo-php-library/pull/644#discussion_r306576915, I realized that I used 4.2.0 when writing these tests instead of the exact version.
=> SPEC-1289: Use specific server version for $merge tests

source/client-side-encryption/external/external-key.json, source/client-side-encryption/external/external-schema.json, source/client-side-encryption/tests/README.rst
A simple test of external key vault by configuring the external key vault to use a bad username/password.
Validated with a Java driver PoC here:
https://github.com/kevinAlbs/JavaFLEProsePoC/blob/95e9fc211f7ac33f7672885723f9d9794111e32f/src/main/java/ExternalKeyVaultTest.java
=> SPEC-1371 add prose test for external key vault

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/etc/test-templates/bypassedCommand.yml.template, source/client-side-encryption/tests/README.rst, source/client-side-encryption/tests/bypassedCommand.json, source/client-side-encryption/tests/bypassedCommand.yml
Adds a spec test for a prohibited database operation for automatic encryption, and a prose test for a view operation.
I verified the new prose test with: https://github.com/kevinAlbs/JavaFLEProsePoC/blob/9ad5859b9aec03c8d4b4ecdef991c66a7de3d2a4/src/main/java/ViewTest.java
And verified the new spec test with the Java test runner.
=> SPEC-1386 Test that auto encryption on views is prohibited

source/client-side-encryption/client-side-encryption.rst
=> Fix typos in ClientEncryption api description

source/connections-survive-step-down/tests/README.rst
The getMore test requires a replica set because it invokes the `replSetStepDown` command.
I think it also makes sense for the other two "not master" tests to require a replica set, even if the fail point technically makes it possible to simulate the error in other topologies.
I've left the final two shutdown tests alone, as I don't think those codes are specific to replica sets and I imagine those tests could be executed against a sharded cluster or standalone. That said, perhaps we should note thjat sharded cluster URIs should only include a single mongos node since the test calls `configureFailPoint`.
=> Note topology requirements for step down tests

source/retryable-reads/tests/README.rst
Something I noticed in https://github.com/mongodb/mongo-php-library/pull/671, which I thought be better clarified in the test README so that users don't have to infer this from the test files themselves.
=> Clarify that data field may be an object or array

source/transactions-convenient-api/transactions-convenient-api.rst
This is a non-functional typo fix, so I opted not to bump last modified date or create a changelog entry.
=> Use correct variable name for callback

source/bson-corpus/tests/array.json
Fixes #625.
For reference this is the first test:
```
$ echo "130000000461000B00000010000A0000000000" | perl bsonview -x
13000000 04 "a" 00 [ 0b000000 10 "" 00 0A000000 00 ] 00
```
And this is the second:
```
$ echo "150000000461000D000000106162000A0000000000" | perl bsonview -x
15000000 04 "a" 00 [ 0d000000 10 "ab" 00 0A000000 00 ] 00
```
=> SPEC-1392 Make bson-corpus array test descriptions unique

source/transactions/tests/README.rst
This clarifies that drivers should either run the `configureFailPoint` command used for the `targetedFailPoint` operation on a different client, or need to filter commands in the logger as the tests don't include `configureFailPoint` in the command expectations.
=> SPEC-1434: Clarify ignoring configureFailPoint command in spec tests

source/crud/tests/README.rst, source/transactions-convenient-api/tests/callback-retry.json, source/transactions-convenient-api/tests/callback-retry.yml, source/transactions/tests/abort.json, source/transactions/tests/abort.yml, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml
=> SPEC-1221 Reinstate DuplicateKey code assertions in error labels tests

source/crud/tests/v2/updateWithPipelines.json, source/crud/tests/v2/updateWithPipelines.yml
This adds two tests to ensure that drivers implement pipeline-style updates for bulkwrite operations as well. I'm not sure whether this warrants bumping the crud spec version. These new tests are used in the PHP driver: https://github.com/mongodb/mongo-php-library/pull/684
=> SPEC-1455: Add missing tests for aggregation pipeline in bulk write updates

source/client-side-encryption/etc/test-templates/bulk.yml.template, source/client-side-encryption/tests/bulk.json, source/client-side-encryption/tests/bulk.yml
I hope this is uncontroversial. This fixes a test failure in Python: https://evergreen.mongodb.com/version/5d97d4647742ae4dbe7aaeea
See the Jira ticket for an explanation of why: https://jira.mongodb.org/browse/SPEC-1464
=> SPEC-1464 Workaround for unordered JSON parsers in FLE test

source/server-discovery-and-monitoring/tests/monitoring/standalone_suppress_equal_description_changes.json, source/server-discovery-and-monitoring/tests/monitoring/standalone_suppress_equal_description_changes.yml
The SDAM specification describes an algorithm for ServerDescription
equality, and mandates that this equality operator should be used
during topology updates to guard event emission. We should include
a test that expresses this part of the spec.
=> SPEC-1475: add SDAM monitoring test for debouncing update events

README.rst, source/change-streams/tests/README.rst, source/retryable-writes/tests/README.rst
Initially, SPEC-1364 called for removing relative numbered bullets. This leaves a minor problem, where if the last spec test gets removed, future work on the spec could re-use this test number.
To avoid this problem, the spec readme clarifies that tests should no longer be removed, but instead marked as removed by either striking through (for short test descriptions) or removing the test description if it's a larger block of test. This shows readers that the test previously existed but is no longer relevant. At the same time, this ensures that new tests are always added to the end of the list.
Since the new changes no longer allow repurposing test numbers, there's no more reason to not use relative numbered bullets. Existing prose test lists have been changed to relative numbered bullets …
=> SPEC-1364: Clarify use of relative numbered bullets in prose tests

source/connection-string/connection-string-spec.rst
This is just a formatting change, so I'm not bothering with a SPEC ticket or change log bump.
This formatting error dates back to https://github.com/mongodb/specifications/commit/3cf351d1265bc8833776f3a8c7e0fead1957846b.
=> Fix log message example for unsupported keys

source/connection-string/connection-string-spec.rst
The latter two links here seem to be copy-pasted from the first one
=> minor: fix userinfo RFC links in auth spec

source/client-side-encryption/client-side-encryption.rst
Drivers don't need to support an IP address or literal as a custom endpoint. We're also not using it for testing. Since this is a clarification, I did not create a spec ticket. But if I should, I can do so.
Related PR for libmongocrypt docs: https://github.com/mongodb/libmongocrypt/pull/67
=> [FLE] clarify that endpoint host name is not an IP address

source/client-side-encryption/client-side-encryption.rst
- Refers to the key vault collection as "key vault collection" where possible.
- Fixes links to the appendix section describing the key vault collection schema.
- Includes an example of a data key.
- Includes the phrase "data keys" in the section describing the key vault collection schema.
Covers:
https://jira.mongodb.org/browse/SPEC-1490
https://jira.mongodb.org/browse/SPEC-1493
https://jira.mongodb.org/browse/SPEC-1494
https://jira.mongodb.org/browse/SPEC-1488
=> Cleanup key vault collection descriptions

source/extended-json.rst
Fixed a malformed JSON example for the new cannonical format for `binary`.
=> fixed fomart typo in new binary format

source/uri-options/uri-options.rst
This clarifies that all integer options are 32-bit unless otherwise specified. The only exception is the wTimeoutMS option, which is a 64-bit value according to the [Read and Write Concern](https://github.com/mongodb/specifications/blob/master/source/read-write-concern/read-write-concern.rst#write-concern) spec.
=> SPEC-1481: Clarify integer sizes in URI options spec

source/client-side-encryption/client-side-encryption.rst
I believe this should only affect libmongoc's single-threaded client implementation currently. These were the changes I made in the implementation to prevent server selection from immediately failing, and from a delay of 5 seconds due to the cooldown.
=> SPEC-1476 add constraints for single-threaded connection to mongocryptd

source/uuid.rst
This is the final version of the UUID specification.  It's copied from Google Docs, with a few small edits to fix the RST content hierarchy.
=> Add final draft of UUID specification

source/uri-options/tests/auth-options.json, source/uri-options/tests/auth-options.yml
The Ruby driver implements GSSAPI authentication in another gem, mongo-ruby-kerberos, which is not included in the driver by default. To handle this, the Ruby driver tests skip GSSAPI-related tests unless this gem is installed by checking whether the word "GSSAPI" is present in the test description. To make the URI-option tests easier to run on the Ruby Driver, I have made two changes:
1. I added "(GSSAPI)" to the description of the first test so that the Ruby test runner will know to skip it if GSSAPI is not installed. This is consistent with the way descriptions are written in the [auth spec tests](https://github.com/mongodb/specifications/blob/master/source/auth/tests/connection-string.yml#L33).
2. I added a second test using a different mechanism that exists by default in the Ruby …
=> SPEC-1423: Update auth URI options spec for Ruby Driver

source/max-staleness/max-staleness.rst, source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
[SPEC-1525](https://jira.mongodb.org/browse/SPEC-1525).
This PR fixes the description of opTime in the SDAM spec, and it also updates the section to clarify why only mongos records the value.
=> SPEC-1525 Fix SDAM spec's description of opTime

source/crud/crud.rst
https://jira.mongodb.org/browse/SPEC-1540
https://jira.mongodb.org/browse/SPEC-1542
I didn't realize the rationale behind this copypasta when originally implementing [SPEC-1334](https://jira.mongodb.org/browse/SPEC-1334), but I understand now why it's relevant for any option that may not have a place in a legacy opcode. This could technically apply to all legacy opcode usage, but I believe unacknowledged writes are the only place where modern drivers might still use them (if they aren't already using OP_MSG).
My second commit updates language for options other than `hint` to be more clear and also adds a Q&A entry to explain our current design. That commit does not entail driver changes.
=> SPEC-1540: Error if hint specified for unacknowledged update using legacy opcode

source/client-side-encryption/tests/README.rst
By passing a custom pidfilepath and port that differs from any possible existing mongocryptd running in the background, if the driver was mistakenly spawning mongocryptd when it should not have, the spawned mongocryptd will not self-terminate, so it can be detected by either the pidfile or by connecting with a MongoClient.
I've PoC'ed this test with libmongoc.
=> add prose test for bypassing mongocryptd spawning

source/crud/crud.rst, source/gridfs/gridfs-spec.rst
https://jira.mongodb.org/browse/SPEC-1418
Requested in https://github.com/mongodb/specifications/pull/692#discussion_r367667587 but this was missed before that PR was merged.
=> SPEC-1418: Note allowDiskUse find option is ignored for OP_QUERY

source/enumerate-indexes.rst
[SPEC-1399](https://jira.mongodb.org/browse/SPEC-1399)
Starting in MongoDB 4.4, the `ns` field will no longer be present in the index specifications returned from the `listIndexes` server command. This affects drivers that return statically defined models of index specifications as part of their own `listIndexes` helpers, as well as drivers that document the contents of any loose documents/dictionaries they return from that helper instead. 
This PR updates the index enumeration spec and test plan to describe how affected drivers should handle the `ns` field being missing.
After a brief survey, I _think_ the only affected drivers are PHP and legacy C#.
=> SPEC-1399 Handle absence of 'ns' field in index specifications

source/server-discovery-and-monitoring/tests/rs/primary_mismatched_me_not_removed.json, source/server-discovery-and-monitoring/tests/rs/primary_mismatched_me_not_removed.yml
This test validates the pseudocode provided in the SDAM specification, ensuring that a primary is always added to the working server set even if it has a `me` mismatch.
=> SPEC-1533 primary mismatched me is not removed from server set

source/crud/crud.rst, source/crud/tests/v2/findOneAndReplace-hint-clientError.json, source/crud/tests/v2/findOneAndReplace-hint-clientError.yml, source/crud/tests/v2/findOneAndReplace-hint-serverError.json, source/crud/tests/v2/findOneAndReplace-hint-serverError.yml, source/crud/tests/v2/findOneAndReplace-hint.json, source/crud/tests/v2/findOneAndReplace-hint.yml, source/crud/tests/v2/findOneAndUpdate-hint-clientError.json, source/crud/tests/v2/findOneAndUpdate-hint-clientError.yml, source/crud/tests/v2/findOneAndUpdate-hint-serverError.json, source/crud/tests/v2/findOneAndUpdate-hint-serverError.yml, source/crud/tests/v2/findOneAndUpdate-hint.json, source/crud/tests/v2/findOneAndUpdate-hint.yml
https://jira.mongodb.org/browse/SPEC-1398
This is related to #596 but I've split it out into its own PR since `findAndModify` support for `hint` is still waiting on [SERVER-42099](https://jira.mongodb.org/browse/SERVER-42099).
=> SPEC-1398: Hint option for findAndModify update/replace operations

source/retryable-writes/tests/findOneAndReplace-errorLabels.json, source/retryable-writes/tests/findOneAndReplace-errorLabels.yml
I mistyped the command on which to execute the failPoint. It should read "findAndModify" rather than "findOneAndModify."
=> RetryableWrites: findOneAndModify --> findAndModify

source/read-write-concern/tests/operation/default-write-concern-2.6.json, source/read-write-concern/tests/operation/default-write-concern-2.6.yml, source/read-write-concern/tests/operation/default-write-concern-3.2.json, source/read-write-concern/tests/operation/default-write-concern-3.2.yml, source/read-write-concern/tests/operation/default-write-concern-3.4.json, source/read-write-concern/tests/operation/default-write-concern-3.4.yml, source/read-write-concern/tests/operation/default-write-concern-4.2.json, source/read-write-concern/tests/operation/default-write-concern-4.2.yml
Some follow-up of SPEC-1352. I accidentally introduced the top-level field "other_collection_name". Other spec tests of $out/$merge don't set that as a top-level field, and just reference it with YML anchors ([example](https://github.com/kevinAlbs/specifications/blob/wc-fix/source/crud/tests/v2/aggregate-out-readConcern.yml/#L26)). Credit to @divjotarora for catching this.
For a non-functional change like this, LMK if a separate SPEC ticket is warranted to resync the tests, or if I should add this commit to SPEC-1352.
=> SPEC-1352 remove other_collection_name field

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
This change simplifies the wording of how drivers handle "node is shutting down" errors and updates the pseudocode to include this rule. This does not require any driver changes. The motivation is simply to make the spec easier to read.
=> Reword connections survive primary stepdown error handling rule

source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml, source/transactions/tests/retryable-abort-errorLabels.json, source/transactions/tests/retryable-abort-errorLabels.yml, source/transactions/tests/retryable-abort.json, source/transactions/tests/retryable-abort.yml, source/transactions/tests/retryable-commit-errorLabels.json, source/transactions/tests/retryable-commit-errorLabels.yml, source/transactions/tests/retryable-commit.json, source/transactions/tests/retryable-commit.yml
Cleaning up some of the files and adding the RetryableWriteError label to the failpoints that need it.
=> SPEC-1562 transactions test fixes for RetryableWriteError label

source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst, source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/server-monitoring.rst
[SPEC-1580](https://jira.mongodb.org/browse/SPEC-1580)
This change refactors "server monitoring" out of the main SDAM spec into a new document "server-monitoring.rst" with the goal of making the SDAM spec easier to read. The new "server monitoring" document should cover everything related to server monitoring, including:
- monitoring connections
- running isMaster commands
- handling network errors during server checks
- RTT calculation 
- monitoring threads
There are no functional changes here, I only moved/copied sections into the new document and updated RST links between the two documents.
=> SPEC-1580 Refactor Server Monitoring out of the SDAM Spec

source/ocsp-support/ocsp-support.rst, source/uri-options/tests/tls-options.json, source/uri-options/tests/tls-options.yml
`OCSP` was not consistently capitalized and two of the URI options tests said `valid: false` rather than `valid: true` which was causing tests to fail.
=> Fix tests for tlsDisableOCSPEndpointCheck

source/transactions/tests/README.rst, source/transactions/tests/create-collection.json, source/transactions/tests/create-collection.yml, source/transactions/tests/create-index.json, source/transactions/tests/create-index.yml, source/transactions/transactions.rst
https://jira.mongodb.org/browse/SPEC-1419
This PR adds spec changes to allow for collection and index creation within a transaction. The tests are added to ensure that drivers don't inspect commands or prevent creating collections or indexes in transaction on their own.
The test include four new test runner operations to check if collections/indexes exist/do not exist. Note that these currently can't be used along with a `session` argument as the server does not allow running `listCollections` and `listIndexes` commands in a transaction. The tests thus only assert against the state outside of the transaction.
Along with test runner operations, the new `createCollection` and `dropCollection` operations have been added on the `database` object and `createIndex` to the `collection` object.
A …
=> SPEC-1419 Support for collection and index creation in Transactions

source/transactions-convenient-api/tests/commit-retry.json, source/transactions-convenient-api/tests/commit-retry.yml
https://jira.mongodb.org/browse/SPEC-1562
I noticed that the libmongoc test suite failed on MongoDB 4.3 due to a commit not being retried. This label was likely forgotten in #737, as adding it fixes the test in question.
=> SPEC-1562 Add missing RetryableWriteError label

source/transactions/tests/create-index.json, source/transactions/tests/create-index.yml
This change was made because the read/write concern tests added for the 4.4 cycle also have a `createIndex` operation and they use "keys" as the YAML/JSON key name instead of "key". See https://github.com/mongodb/specifications/blob/master/source/read-write-concern/tests/operation/default-write-concern-3.4.json#L120 for an example.
=> Change index key name from "key" to "keys"

source/command-monitoring/command-monitoring.rst
When the driver sends an isMaster command, the server replies with
ismaster in all lowercase. This commit updates the command monitoring
spec to account for this when redacting isMaster commands with
speculative authentication fields.
=> SPEC-1552 Ban ismaster from being published in APM events

source/server-discovery-and-monitoring/server-monitoring.rst
Jira: https://jira.mongodb.org/browse/SPEC-1576
The motivation for this ticket is faster initial SDAM discovery and faster rediscovery. If a client does not use the initial handshake then it require 2 ismasters to update a server's description.
=> SPEC-1576 A monitor's connection handshake satisfies a check and updates the topology

source/ocsp-support/ocsp-support.rst
Running locally I needed to remove `*` from this command.
=> remove asterisk from macOS cache clear

source/enumerate-collections.rst, source/enumerate-indexes.rst
https://jira.mongodb.org/browse/SPEC-1584
This adds the note added to the "Enumerate indexes" in #712 to the "Enumerate collections" spec. The `idIndex` option also no longer contains a `ns` field, which wasn't included in the original PR.
=> SPEC-1584 Clarify absence of 'ns' field in idIndex for listCollections

source/crud/crud.rst, source/crud/tests/README.rst, source/read-write-concern/read-write-concern.rst, source/read-write-concern/tests/README.rst
Based on the "Read/Write Concern Provenance" downstream changes:
> - It is believed that drivers should not currently be attempting to parse "errInfo", but it would be good to add the necessary test coverage and/or spec definitions.
> 
> - Drivers should ensure that the contents of the "errInfo" object are propagated up to the application-visible error/exception, so that developers/admins can be aware of situations such as custom write concern defaults causing wtimeouts, etc.
PoC'ed the test with libmongoc.
=> SPEC-1578 ensure WriteConcernError 'errInfo' is propagated

source/crud/crud.rst
I didn't realize that bulk write models had separate options, so I didn't include them in my changes in #764. There are already tests for these changes.
=> SPEC-1647: Add hint option to DeleteOneModel and DeleteManyModel

source/ocsp-support/ocsp-support.rst
https://jira.mongodb.org/browse/SPEC-1650
=> SPEC-1650: Clarify OCSP documentation requirements for drivers unable to enable OCSP by default on a per MongoClient basis

source/change-streams/tests/README.rst, source/change-streams/tests/change-streams-resume-errorLabels.json, source/change-streams/tests/change-streams-resume-errorLabels.yml, source/change-streams/tests/change-streams-resume-whitelist.json, source/change-streams/tests/change-streams-resume-whitelist.yml
Removing the ability to specify the placeholder value as a simple string.
I was concerned only about a getMore expectation node. Since c# driver makes validations on value **and** type. 
Let me know if we need to change the other values.
=> Change json type of getMore placeholder value.

source/crud/tests/v2/unacknowledged-bulkWrite-delete-hint-clientError.json, source/crud/tests/v2/unacknowledged-bulkWrite-delete-hint-clientError.yml, source/crud/tests/v2/unacknowledged-bulkWrite-update-hint-clientError.json, source/crud/tests/v2/unacknowledged-bulkWrite-update-hint-clientError.yml, source/crud/tests/v2/unacknowledged-deleteMany-hint-clientError.json, source/crud/tests/v2/unacknowledged-deleteMany-hint-clientError.yml, source/crud/tests/v2/unacknowledged-deleteOne-hint-clientError.json, source/crud/tests/v2/unacknowledged-deleteOne-hint-clientError.yml, source/crud/tests/v2/unacknowledged-findOneAndDelete-hint-clientError.json, source/crud/tests/v2/unacknowledged-findOneAndDelete-hint-clientError.yml, source/crud/tests/v2/unacknowledged-findOneAndReplace-hint-clientError.json, source/crud/tests/v2/unacknowledged-findOneAndReplace-hint-clientError.yml, source/crud/tests/v2/unacknowledged-findOneAndUpdate-hint-clientError.json, source/crud/tests/v2/unacknowledged-findOneAndUpdate-hint-clientError.yml, source/crud/tests/v2/unacknowledged-replaceOne-hint-clientError.json, source/crud/tests/v2/unacknowledged-replaceOne-hint-clientError.yml, source/crud/tests/v2/unacknowledged-updateMany-hint-clientError.json, source/crud/tests/v2/unacknowledged-updateMany-hint-clientError.yml, source/crud/tests/v2/unacknowledged-updateOne-hint-clientError.json, source/crud/tests/v2/unacknowledged-updateOne-hint-clientError.yml
The Ruby spec runner did not flag this error because it compares the length of the expectations, and `[].length` and `{}.length` in Ruby both return 0. Mikalai pointed out that this failed in the .NET driver test runner, so fixing it now.
=> SPEC-1658 Replace empty object expectations with empty array in unacknowledged bulk write tests

source/uri-options/tests/read-preference-options.json, source/uri-options/tests/read-preference-options.yml
This test validates that drivers parse a single instance of the
`readPreferenceTags` option as an array.
=> DRIVERS-989: add uri options test for single `readPreferenceTags`

source/change-streams/tests/README.rst
Covers [SPEC-1506](https://jira.mongodb.org/browse/SPEC-1506) and [SPEC-1374](https://jira.mongodb.org/browse/SPEC-1374).
=> SPEC-1506: Add note about testing change streams on sharded clusters

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/rs/topology_version_equal.json, source/server-discovery-and-monitoring/tests/rs/topology_version_equal.yml, source/server-discovery-and-monitoring/tests/rs/topology_version_greater.json, source/server-discovery-and-monitoring/tests/rs/topology_version_greater.yml, source/server-discovery-and-monitoring/tests/rs/topology_version_less.json, source/server-discovery-and-monitoring/tests/rs/topology_version_less.yml
This PR updates the SDAM spec to reduce race conditions in SDAM error handling as part of [SPEC-1579](https://jira.mongodb.org/browse/SPEC-1579). I spun this off as a separate PR because these changes are self contained and do not depend on the streaming protocol.  In summary:
- Add topologyVersion field to ServerDescription.
- Add SDAM spec tests for topologyVersion comparison.
- Clients ignore stale errors based on generation number and topologyVersion.
=> SPEC-1663 Reduce race conditions in SDAM error handling

source/retryable-writes/retryable-writes.rst, source/transactions/tests/error-labels.json, source/transactions/tests/error-labels.yml, source/transactions/transactions.rst
Clarify that the RetryableWriteError label should not be added to errors that occur during writes within a transaction. @divjotarora did a POC and confirmed that these changes work in Go.
=> SPEC-1666 Clarify the conditions for adding the retryable writes error label during transactions

source/index-management.rst
A few things I wasn't sure of:
1. The `hidden` property for an index can be changed via the `collMod` command. I don't see any references to it in our existing specs, so I didn't mention this anywhere. Is a note in the resulting DRIVERS ticket sufficient so that any drivers with `collMod` helpers can update accordingly?
2. The `hidden` property is now returned in the `listIndexes` results documents. An example is `{v: 2, key: {x: 1}, hidden: true}`. This might affect drivers that have helper types for `listIndexes` results, but I don't see any other index options mentioned in https://github.com/mongodb/specifications/blob/master/source/enumerate-indexes.rst#getting-full-index-information, so I didn't make any edits to that spec.
=> SPEC-1676 Add support for hidden option to index creation

source/uri-options/tests/read-preference-options.json, source/uri-options/tests/read-preference-options.yml
libmongoc gives an error when parsing the URI `mongodb://example.com/?readPreferenceTags=dc:ny` because no explicit readPreference is considered a primary read preference. And a primary read preference is invalid with tags.
@ShaneHarvey pymongo is passing this test, because I think read preference validation won't occur at URI parse time, but at client construction time. E.g.
```
parsed = uri_parser.parse_uri ("mongodb://localhost/?readPreferenceTags=dc:ny")
client = MongoClient("mongodb://localhost/?readPreferenceTags=dc:ny")
```
I'm not totally sure what the behavior should be for that URI. I made the non-controversial change here to add an explicit readPreference to the test. I plan to create a DRIVERS ticket to consider what should happen for this URI. Some thoughts:
The URI options …
=> SPEC-1659 add explicit readPreference to test

source/message/OP_MSG.rst, source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst, source/server-discovery-and-monitoring/server-monitoring.rst, source/server-discovery-and-monitoring/tests/README.rst
Jira: https://jira.mongodb.org/browse/SPEC-1579
Summary:
- Clients stream isMaster responses from the server with OP_MSG exhaust to
reduce the time to recovery after server maintenance.
- Add "awaited" field to heartbeat events.
- Add section for awaitable isMaster server spec.
- Add section for SDAM prose tests.
- Update OP_MSG exhaustAllowed to mention isMaster.
I am working on converting some of the prose tests into a spec tests in the transaction runner format.
=> SPEC-1579 Add SDAM Monitoring rules for streaming heartbeat protocol

source/server-discovery-and-monitoring/server-monitoring.rst, source/server-discovery-and-monitoring/tests/integration/cancel-server-check.json, source/server-discovery-and-monitoring/tests/integration/cancel-server-check.yml
This change adds `tests/integration/cancel-server-check.yml`. This test verifies the "isMaster Cancellation" section of the spec. If a driver mistakenly did not cancel the isMaster check, the server would remain in the Unknown state for 10 seconds (until the in-progress streaming isMaster checks succeeds)  and thus the retried "insertOne" would fail during server selection (serverSelectionTimeoutMS=5000).
I have verified that the test succeeds in Python (https://evergreen.mongodb.com/version/5eb9d90a0ae6063d1374c3e1). I've also verified that the test fails when the cancellation logic is removed.
=> SPEC-1687 Add SDAM isMaster cancellation test

source/connections-survive-step-down/tests/README.rst
For drivers which need to check total connection count in order to verify that a pool was cleared, we need to instruct implementers to check after all operations have completed.
=> DRIVERS-1261: check pool clear criteria at the end of all tests

source/server-discovery-and-monitoring/server-monitoring.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/integration/isMaster-command-error.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-network-error.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-timeout.yml
- Note that the RTT monitor should ignore the ismaster response.
- Typo fix in test readme example "waitForEvent" => "assertEventCount".
- Note in tests that a ServerChangedEvent is expected in the beginning.
=> make minor clarifications to server monitoring

source/driver-read-preferences.rst, source/server-selection/server-selection.rst
https://jira.mongodb.org/browse/SPEC-1700
addSpecial referred to a generic method for assigning query modifiers for OP_QUERY, which is no longer relevant to the find command API.
=> SPEC-1700: Remove reference to addSpecial

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/server-monitoring.rst
Most developers confronted with the problem of calculating the RTT of an awaited isMaster ultimately have a similar "eureka" moment: "why aren't we just returning the milliseconds awaited on the server!?" Hopefully this rationale saves future implementers from spending too much time down that seemingly virtuous path.
=> Include rationale for why we don't use `awaitedTimeMS` for RTT

source/server-discovery-and-monitoring/server-monitoring.rst, source/server-discovery-and-monitoring/tests/integration/connectTimeoutMS.json, source/server-discovery-and-monitoring/tests/integration/connectTimeoutMS.yml
Jira: [SPEC-1705](https://jira.mongodb.org/browse/SPEC-1705)
The test passes in Python. I've also verified that the test will fail if a driver incorrectly sets a timeout on the connectTimeoutMS=0 connection. For example the failure in python would be:
```
FAIL: test_discovery_and_monitoring_integration_connectTimeoutMS_connectTimeoutMS=0 (test.test_discovery_and_monitoring.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/shane/git/mongo-python-driver/test/__init__.py", line 449, in wrap
return f(*args, **kwargs)
File "/Users/shane/git/mongo-python-driver/test/__init__.py", line 449, in wrap
return f(*args, **kwargs)
File "/Users/shane/git/mongo-python-driver/test/test_discovery_and_monitoring.py", line …
```
=> SPEC-1705 Support connectTimeoutMS=0 in streaming heartbeat protocol

source/server-discovery-and-monitoring/server-monitoring.rst
The spec prose (https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-monitoring.rst#network-or-command-error-during-server-check) already does things in this order and this PR updates the pseudocode to match.
See https://jira.mongodb.org/browse/PYTHON-2236?focusedCommentId=3076780&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3076780 for a description of the race this addresses.
=> Reset connection pool after setting server to Unknown in pseudocode

source/server-discovery-and-monitoring/tests/README.rst
Per this discussion: https://github.com/mongodb/mongo-c-driver/pull/648/commits/91c4e4c55a5378825a70428580382b9c9bf727b7?file-filters%5B%5D=.c#r448520715
=> Use 10s timeout for SDAM waitForEvent operation

source/server-discovery-and-monitoring/tests/README.rst
Per this discussion: https://github.com/mongodb/mongo-c-driver/pull/648/commits/91c4e4c55a5378825a70428580382b9c9bf727b7?file-filters%5B%5D=.c#r448526630
=> configureFailPoint is mutually exclusive with useMultipleMongoses

source/server-discovery-and-monitoring/tests/README.rst
Add an arbitrary timeout to the RTT prose test.
Per this comment https://github.com/mongodb/mongo-c-driver/pull/648/commits/91c4e4c55a5378825a70428580382b9c9bf727b7?file-filters%5B%5D=.c#r448552242
=> Add timeout to RTT test

source/change-streams/tests/change-streams-errors.json, source/change-streams/tests/change-streams-errors.yml
I mistakenly did not remove `ElectionInProgress` from the error allowlist in [CDRIVER-3589](https://jira.mongodb.org/browse/CDRIVER-3589).
Fortunately Clyde caught this when validating the behavior in the C++ driver.
This tests that ElectionInProgress does not resume, and also removes an unnecessary projection.
Validated the tests in libmongoc.
=> test that ElectionInProgress is not resumed

source/bson-corpus/tests/timestamp.json
https://jira.mongodb.org/browse/SPEC-1715
If the 64 bit number 2^32-1 is not stored in an unsigned number, it will wrap around to -1, which is a special value. I added another test that has the high-order bit set that doesn't yield a special value on error.
=> SPEC-1715 add additional timestamp test for not 2^32-1

source/ocsp-support/ocsp-support.rst, source/ocsp-support/tests/README.rst
The changes proposed here apply only to drivers whose TLS libraries hard-fail when an OCSP responder is unavailable. To ensure an OCSP responder outage doesn't affect Atlas connectivity, affected drivers should:
1. Set the `tlsDisableOCSPEndpointCheck` option to true by default if it is supported. This will allow the driver to support stapled OCSP when available and avoid reaching out to responders altogether when a stapled response isn't provided.
2. Set the `tlsDisableCertificateRevocationCheck` option to true by default if `tlsDisableOCSPEndpointCheck` is not supported. This will turn off all revocation checks, including non-OCSP checks, but is necessary if the driver doesn't have granular control of stapled vs non-stapled OCSP.
Note that the initial approach presented in the previous …
=> SPEC-1712: Default OCSP to "off" for drivers that hard-fail when an OCSP responder is unavailable

source/sessions/tests/dirty-session-errors.json, source/sessions/tests/dirty-session-errors.yml
The tests assume that the server supports retryable writes,
and even though standalones support sessions, they don't actually
support retryable writes (which require an oplog)
DRIVERS-1230
=> Revert addition of "single" topology type to dirty sessions test

source/connections-survive-step-down/tests/README.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/integration/rediscover-quickly-after-step-down.json, source/server-discovery-and-monitoring/tests/integration/rediscover-quickly-after-step-down.yml
Taking Eric's advice on [DRIVERS-1290](https://jira.mongodb.org/browse/DRIVERS-1290). @DmitryLukyanov can you POC these changes to see if it resolves the Windows C# issues?
Instead of retrying after LockTimeout errors, we increase the replSetStepDown timeout to avoid them altogether. Before we run replSetStepDown, run `{replSetFreeze:0}` to reset a secondary's timeout to ensure there is an electable node. This ensures a speedy election when the tests are run multiple times in a row (as is the case in C# for testing both sync and async).
We also increase the waitForPrimaryChange timeout from 5 seconds to 15 seconds to workaround slow elections on Windows (again found by C#). The slow elections are possibly caused by SERVER-48154.
=> SPEC-1708 Increase replSetStepDown timeout and run replSetFreeze instead of retrying

source/bson-decimal128/decimal128.rst
The current decimal128 spec mentions that it is based on IEEE 754-2008. That standard allows the coefficient to be encoded in one of two ways:
1. "decimal encoding" using 10-bit declets for groups of 3 digits. This method is also called Densely Packed Decimal (DPD).
2. "binary encoding" using a simple unsigned integer number (BID).
The specification sheet later formally declares that the BSON encoding is based on "Decimal Arithmetic Encodings" (http://speleotrove.com/decimal/decbits.html) which only allows for the coefficient to be encoded as DPD (method 1). To quote from that document:
> coefficient continuation
>
> The remaining, less significant, digits of the coefficient. The coefficient continuation is a multiple of 10 bits (the multiple depending on the format), and the most …
=> Add coefficient encoding detail to Decimal128 specification

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-connection.json, source/connection-monitoring-and-pooling/tests/pool-checkout-connection.yml, source/connection-monitoring-and-pooling/tests/pool-create-min-size.json, source/connection-monitoring-and-pooling/tests/pool-create-min-size.yml
SPEC-1412
This PR makes a number of modifications to the CMAP spec to clarify the lifecycle of a `Connection` and the terminology used to describe it. Besides resyncing the tests, this ideally should not require any changes in drivers that currently implement a CMAP-based connection pool.
This originally started out as fixing a minor issue with the wording of "creating a connection" that resulted in ConnectionReady events being fired before ConnectionCreated events according to a literal interpretation of the spec. In fixing this issue, I realized that a solution could not easily be found that worked for both drivers that had a background thread and/or async I/O and for drivers that were single threaded. Seeing as no single-threaded drivers currently implement CMAP or plan to do so, this …
=> SPEC-1412 Clarify Connection creation wording and terminology

source/bson-corpus/tests/binary.json, source/extended-json.rst
POC'ing this with PyMongo uncovered an issue - `$uuid` is also how UUIDs were represented in PyMongo's legacy extJSON format so  this might result in a backward-breaking change in the Python driver.
Also, there is no mention in this spec whether extJSON parsers should offer configuration options that allow the user to set UuidRepresentation (https://github.com/mongodb/specifications/blob/master/source/uuid.rst) and accordingly decode UUID fields (I'd guess that UNSPECIFIED would decode as Binary subtype 4, any other representation would decode as native UUID; on the generation/encoding side we'd need to decide whether native UUIDs will be encoded as subtype 4 or 3).
=> SPEC-1582 Parse $uuid fields as Binary subtype 4

source/retryable-reads/tests/README.rst, source/retryable-writes/tests/README.rst, source/transactions/tests/README.rst
Questions:
1. Should the same change be added for transactions-convenient-api?
2. Should I create a DRIVER ticket?
=> Add heartbeatFrequencyMS default value for retryable read/writes and transaction tests.

source/extended-json.rst
@reggi uncovered this inconsistency in the spec during the node implementation.
=> Fix error in extended JSON UUID example

source/extended-json.rst
https://jira.mongodb.org/browse/SPEC-1757
=> SPEC-1757: $-prefixed keys not matching types must be left as-is

source/uri-options/tests/connection-pool-options.json, source/uri-options/tests/connection-pool-options.yml, source/uri-options/uri-options.rst
Since this bug happened due to the CMAP options being added without sufficient tests, I added specific tests for both minPoolSize and maxPoolSize to the comprehensive test of CMAP URI options well as for the specific values of 0.
=> SPEC-1548 Allow 0 for min/max pool size and fully test cmap URI options

source/unified-test-format/tests/valid-pass/poc-gridfs.json, source/unified-test-format/tests/valid-pass/poc-gridfs.yml
Verified that the Go test runner passes with this change.
=> Use unsetOrMatches assertion for md5 field in GridFS tests

source/unified-test-format/unified-test-format.rst
This [test](https://github.com/mongodb/specifications/blob/23fb6262f3688fee52b0e284216d42fe472fdd97/source/unified-test-format/tests/valid-pass/poc-transactions-mongos-pin-auto.yml#L119) causes future tests to hang when doing operations against the same database/collection because the `abortTransaction` command fails server-side so the transaction is left open. Drivers ignore these errors, though, so the test still passes. There was some discussion about this in the original PR and the resolution was that this is a PHP-only issue because MongoClient/session pool instances are persisted across tests, but this will affect all test runners.
After discussing with @ShaneHarvey, we decided the simplest solution is to terminate open transactions if a test fails or starts a transaction.
=> Run killAllSessions in unified tests if the test started a transaction

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.json, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.yml, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-timeout.json, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-timeout.yml, source/connection-monitoring-and-pooling/tests/pool-checkout-returned-connection-maxConnecting.json, source/connection-monitoring-and-pooling/tests/pool-checkout-returned-connection-maxConnecting.yml, source/server-discovery-and-monitoring/server-monitoring.rst
SPEC-1753
This PR updates the CMAP spec to require that drivers limit the number of concurrently establishing connections.
=> SPEC-1753 Rate limit new connection creations (maxConnecting)

source/server-discovery-and-monitoring/server-discovery-and-monitoring-tests.rst
SPEC-1764
This PR adds a prose integration test to the SDAM spec to ensure that monitors wait at least 500ms between server checks even when a thread in server selection is requesting immediate checks.
=> SPEC-1764 Test that monitors wait minHeartbeatFrequencyMS between failed server checks

source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.json, source/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.yml
Tested in python here: https://evergreen.mongodb.com/version/5fc6afbdd1fe0771a322eaec
And a second time for good measure: https://evergreen.mongodb.com/version/5fc6edb032f417146256a3aa
=> SPEC-1767 Fix race in CMAP test 'maxConnecting is enforced'

source/uri-options/uri-options.rst
=> DRIVERS-1460: Fix wrong description for waitQueueTimeoutMS in URI options spec

source/versioned-api/tests/runcommand-helper-no-api-version-declared.json, source/versioned-api/tests/runcommand-helper-no-api-version-declared.yml
With requireApiVersion enabled, this test is no longer valid as the test client would always have an API version declared. As per the spec, declaring an API version in a command document for a command helper and declaring a version on the client is invalid and has undefined behaviour.
=> Skip runCommand tests when requireApiVersion is true

source/unified-test-format/tests/valid-pass/poc-retryable-writes.json, source/unified-test-format/tests/valid-pass/poc-retryable-writes.yml
The .NET driver does not return a result for the insertOne and insertMany methods, which is allowed in the CRUD spec (as all fields of the result are optional). To reflect this, we need to add a top-level `$$unsetOrMatches` to the expected result for such operations.
=> Add top level unsetOrMatches to insertMany operation

source/versioned-api/tests/test-commands-deprecation-errors.json, source/versioned-api/tests/test-commands-deprecation-errors.yml
The `test-commands-deprecation-errors` test should skip when requireApiVersion is true since it uses `runCommand` without setting an `apiVersion` (this issue [was also discovered](https://github.com/mongodb/specifications/pull/887) for other `runCommand` tests).  When requireApiVersion is true for `test-commands-deprecation-errors`, commands are sent to the server for test setup that lack a `ServerAPIVersion` and the server errors incorrectly before the `runCommand` is sent.
Skips the test when `requireApiVersion` is true.
=> Skip deprecation errors test when requireApiVersion is true

source/versioned-api/tests/transaction-handling.json, source/versioned-api/tests/transaction-handling.yml
[DRIVERS-1504](https://jira.mongodb.org/browse/DRIVERS-1504)
Committing a transaction should not append server API options, but committing will move the transaction state from "in progress" to "committed" (see an FSA [here](https://github.com/mongodb/specifications/blob/master/source/transactions/transactions.rst#clientsession-changes)). Any other commits directly following should not append server API options, but a driver may accidentally add them, as the transaction state is no longer "in progress".
Adds a new test case to the `transaction-handling` spec test for versioned api to make sure that committing a transaction more than once will not accidentally append server API options.
=> DRIVERS-1504 Update versioned api transaction-handling spec test

source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml
[DRIVERS-1505](https://jira.mongodb.org/browse/DRIVERS-1505)
In the `crud-api-version-1-strict` spec test, a $listLocalSessions stage is used in an aggregate test case. That stage was [excluded](https://docs.google.com/document/d/10heZ18gZQw3x4MFPaTcY1Pwb0XCW7aSsEX5-cSe-nvs/edit#heading=h.wl7sg62rrat1) from api version 1, so the test fails with an API strict error.
Updates the test to expect this error.
=> DRIVERS-1505 Update versioned api database aggregate strict test

source/transactions/transactions.rst
Minor change to document that the abortTransaction command accepts recoveryToken. The spec already mandates this and has tests to verify the behavior. 
Motivation: In [SERVER-53811](https://jira.mongodb.org/browse/SERVER-53811), the server asked me to explain which command args drivers use for commit and abort. I was planning to share this section of the spec but was surprised to see recoveryToken was not present in the abortTransaction example.
=> Document that the abortTransaction command accepts recoveryToken

source/bson-corpus/tests/binary.json
[SPEC-1777](https://jira.mongodb.org/browse/SPEC-1777)
[DRIVERS-848](https://jira.mongodb.org/browse/DRIVERS-848) adds support for parsing a new, relaxed $uuid extended JSON representation of binary subtype 4. This change requires drivers to validate passed in UUIDs to make sure they conform to RFC 4122 standards.
The current spec tests only have one invalid UUID case. The Go driver had to add more test coverage for invalid UUIDs, so it would probably be a good idea to add these to spec tests.
=> SPEC-1777 Add more spec tests for invalid relaxed UUIDs

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/etc/test-templates/awsTemporary.yml.template, source/client-side-encryption/tests/README.rst, source/client-side-encryption/tests/awsTemporary.json, source/client-side-encryption/tests/awsTemporary.yml
Adds integration tests for creating and passing temporary AWS credentials to authenticate KMS requests for CSFLE.
Drivers can obtain AWS temporary credentials with a new `set-temp-creds.sh` script included in drivers-evergreen-tools: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/136 By default, the temporary credentials expire after 12 hours.
POC of the new tests running in Evergreen in libmongoc: https://github.com/mongodb/mongo-c-driver/pull/725
Tests require libmongocrypt 1.2.0: https://github.com/mongodb/libmongocrypt/releases/tag/1.2.0
=> SPEC-1774 support AWS temp creds in CSFLE

source/unified-test-format/tests/valid-fail/operation-failure.json, source/unified-test-format/tests/valid-fail/operation-failure.yml
https://jira.mongodb.org/browse/SPEC-1781
As a valid-fail test, this will ensure test runners expect operations to succeed by default even if they have no result assertions.
=> SPEC-1781 Expect success for operations without expectError and expectResult

source/crud/crud.rst, source/crud/tests/unified/estimatedDocumentCount.json, source/crud/tests/unified/estimatedDocumentCount.yml, source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml
Adds a line clarifying an assumption drivers can make about the result of an aggregate with $collStats.
Disables multiple mongoses on the recently added spec tests for estimatedDocumentCount so that failpoints work as expected on sharded topologies.
=> SPEC-1780 Fix typos in estimatedDocumentCount spec and tests

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
The `checkOut` section currently states that the pool should wait until "either \[totalConnectionCount == maxPoolSize or pendingConnectionCount == maxConnecting\] are met or until a Connection becomes available" before re-entering the queue after being blocked on maxConnecting. This should instead state that the pool should wait until _neither_ of those are true or until a Connection becomes available, since otherwise it couldn't create a new connection after re-entering the loop.
=> minor: fix wording error in maxConnecting requirement

README.rst
This PR is to replace a 404 URI in the README with a current link to MongoDB Style Guidelines.
=> Fix 404 URI for Documentation Style Guidelines

source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml, source/versioned-api/tests/crud-api-version-1.json, source/versioned-api/tests/crud-api-version-1.yml
The PHP driver adds the `multi` and `upsert` fields with default values, which causes the versioned API spec tests to fail due to the fields not being expected. This PR uses the `$$unsetOrMatches` operator to make the command expectations more forgiving.
=> Use unsetOrMatches operator in bulk write command expectations

source/unified-test-format/schema-1.2.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-minProperties.json, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-minProperties.yml, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-enum.json, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-enum.yml, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-minItems.json, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-minItems.yml, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-type.json, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-property-type.yml, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-type.json, source/unified-test-format/tests/invalid/entity-client-storeEventsAsEntities-type.yml, source/unified-test-format/tests/valid-fail/entity-client-storeEventsAsEntity-conflict_with_client_id.json, source/unified-test-format/tests/valid-fail/entity-client-storeEventsAsEntity-conflict_with_client_id.yml, source/unified-test-format/tests/valid-fail/entity-client-storeEventsAsEntity-conflict_with_existing_id.json, source/unified-test-format/tests/valid-fail/entity-client-storeEventsAsEntity-conflict_with_existing_id.yml, source/unified-test-format/tests/valid-pass/entity-client-storeEventsAsEntity.json, source/unified-test-format/tests/valid-pass/entity-client-storeEventsAsEntity.yml, source/unified-test-format/unified-test-format.rst
2ce041277c07b2f67b0dff73f1b04fa7e10f2af8 (#903) missed updating the spec version and changelog for storeEventsAsEntities and loop. Additionally, storeEventsAsEntities required a schema update and corresponding tests.
=> DRIVERS-828 Update spec changelog and schema-1.2

source/unified-test-format/unified-test-format.rst
Previous syntax was not rendering correctly (markup was still visible). This also swaps the anchor to be consistent with other client entity options.
=> Fix RST link to storeEventsAsEntities

source/unified-test-format/schema-1.2.json
This was leftover from an earlier draft of the spec and was never codified.
=> Remove stream entity from schema

source/versioned-api/tests/transaction-handling.json, source/versioned-api/tests/transaction-handling.yml
DRIVERS-1595
Verified the test locally, but it's almost an exact copy of the `commitTransaction` test above so I skipped the evergreen patch build.
=> DRIVERS-1595 Verify that abortTransaction does not include Versioned API options

source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml, source/versioned-api/tests/crud-api-version-1.json, source/versioned-api/tests/crud-api-version-1.yml, source/versioned-api/tests/runcommand-helper-no-api-version-declared.json, source/versioned-api/tests/runcommand-helper-no-api-version-declared.yml, source/versioned-api/tests/test-commands-deprecation-errors.json, source/versioned-api/tests/test-commands-deprecation-errors.yml, source/versioned-api/tests/test-commands-strict-mode.json, source/versioned-api/tests/test-commands-strict-mode.yml, source/versioned-api/tests/transaction-handling.json, source/versioned-api/tests/transaction-handling.yml
After some discussion on whether versioned API tests should even run on 4.7, we've come to the conclusion that there's no point testing 4.7 as it was mainly an internal test release. This PR changes the `minServerVersion` requirement for all tests to 4.9 and drops testing `estimatedDocumentCount` with the `count` command on 4.7.
=> Use 4.9 as minServerVersion for versioned API tests

source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml
[DRIVERS-1561](https://jira.mongodb.org/browse/DRIVERS-1561)
Removes skipReason on estimatedDocumentCount test for versioned API. This test was being skipped because the $collStats aggregate pipeline stage was not a part of API version 1, but it was just added in [SERVER-54470](https://jira.mongodb.org/browse/SERVER-54470).
=> DRIVERS-1561 Remove skipReason on edc versioned API test

source/versioned-api/versioned-api.rst
This clarifies when an API Version should be sent to the server. I've tried to word this in a way that conveys that this only applies to commands sent through `OP_MSG` without placing too much emphasis on the wire protocol.
=> Clarify when API Version should be sent

source/client-side-encryption/client-side-encryption.rst
Both users and our integration tests have experienced newly spawned mongocryptd may taking more than one second before it can accept connections.
This bumps the fixed timeout to 10000.
=> SPEC-1792 bump timeout

source/wireversion-featurelist.rst
http://jira.mongodb.org/browse/DRIVERS-1627
This revises #943.
[Resumable Initial Sync](https://docs.mongodb.com/manual/release-notes/4.4/#resumable-initial-sync) was indeed a 4.4 feature, but I don't think it pertained to drivers. This change replaces it with a list of driver features I came across by quickly grepping through our specs and wire version checks in PHPLIB. I may be missing some, but I think this makes the entry more relevant to driver developers.
=> DRIVERS-1627: Note driver-related features for 4.4 wire version

source/versioned-api/tests/README.rst, source/versioned-api/tests/test-commands-deprecation-errors.json, source/versioned-api/tests/test-commands-deprecation-errors.yml, source/versioned-api/versioned-api.rst
https://jira.mongodb.org/browse/DRIVERS-1649
The server renamed this parameter.
=> DRIVERS-1649 acceptAPIVersion2 -> acceptApiVersion2

source/client-side-encryption/client-side-encryption.rst
Not urgent – but I wanted to capture this rationale somewhere.
=> include rationale for CSFLE cmds to mongocryptd on unencrypted colls

source/unified-test-format/tests/valid-pass/entity-find-cursor.json, source/unified-test-format/tests/valid-pass/entity-find-cursor.yml
Divjot, 
Java driver fails this type assertion on 2.6 and 3.0, since the cursorsKilled field isn't manufactured when translating from OP_KILL_CURSORS.  This changes works around that.  
How is Go driver dealing with this this?
=> DRIVERS-720 small fix to unified test format changes for LB support

source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-create-min-size-error.json, source/connection-monitoring-and-pooling/tests/pool-create-min-size-error.yml
[DRIVERS-1647](https://jira.mongodb.org/browse/DRIVERS-1647)
Updating pool-create-min-size-error test to include appName in the fail point.
=> DRIVERS-1647: Add appName to fail point at pool-create-min-size-error

source/retryable-reads/retryable-reads.rst, source/retryable-reads/tests/README.rst, source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/README.rst
DRIVERS-1483
This PR updates the language of the retryability specifications to require that [`PoolClearedErrors`](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#connection-pool-errors) are retried. This PR also adds a prose test to each spec so drivers can confirm they conform to the requirement correctly.
POC implementation in Rust: https://github.com/patrickfreed/mongo-rust-driver/commit/2ed7132e9cd936ca071ffdc7f072036150fc7115
This is the final spec change in the Avoiding Connection Storms project (DRIVERS-781)
=> DRIVERS-1483 PoolClearedErrors must be retried

source/unified-test-format/unified-test-format.rst
The unified test format changes for DRIVERS-720 introduced a ``hasServiceId`` assertion in expected events to assert whether or not the event published by the driver contains a ``serviceId`` field. The test files use this field correctly but it was incorrectly called ``serviceId`` in the spec rather than ``hasServiceId``.
=> Change serviceId to hasServiceId in expected events

source/load-balancers/tests/README.rst, source/load-balancers/tests/cursors.json, source/load-balancers/tests/cursors.yml, source/load-balancers/tests/event-monitoring.json, source/load-balancers/tests/event-monitoring.yml, source/load-balancers/tests/lb-connection-establishment.json, source/load-balancers/tests/lb-connection-establishment.yml, source/load-balancers/tests/non-lb-connection-establishment.json, source/load-balancers/tests/non-lb-connection-establishment.yml, source/load-balancers/tests/sdam-error-handling.json, source/load-balancers/tests/sdam-error-handling.yml, source/load-balancers/tests/server-selection.json, source/load-balancers/tests/server-selection.yml, source/load-balancers/tests/transactions.json, source/load-balancers/tests/transactions.yml, source/load-balancers/tests/wait-queue-timeouts.json, source/load-balancers/tests/wait-queue-timeouts.yml
This PR contains the YAML/JSON test files that were originally added in #935. They rely on the Unified Test Format changes that were merged into the `master` branch in https://github.com/mongodb/specifications/commit/ed4e62b48939378b814cbd7d9d4939a2c1076a6b.
I also added a README file describing how the cluster should be set up and what tests to run in scope of this PR. There were some modifications required to run existing tests (e.g. retryable reads/writes) against LB clusters but I didn't want to make this PR too large, so they are in #961.
=> DRIVERS-720 Add unified tests for LB support

source/server-discovery-and-monitoring/tests/integration/isMaster-command-error.json, source/server-discovery-and-monitoring/tests/integration/isMaster-command-error.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-network-error.json, source/server-discovery-and-monitoring/tests/integration/isMaster-network-error.yml
The complete explanation is in DRIVERS-1722. In short, this change is related to the fact that servers <4.9 do not activate fail points configured with `appName`.
DRIVERS-1722
=> Set the `minServerVersion` requirement to 4.9 in isMaster-network/command-error tests

source/message/OP_MSG.rst, source/server-discovery-and-monitoring/server-discovery-and-monitoring-tests.rst, source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/integration/connectTimeoutMS.json, source/server-discovery-and-monitoring/tests/integration/connectTimeoutMS.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-command-error.json, source/server-discovery-and-monitoring/tests/integration/isMaster-command-error.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-network-error.json, source/server-discovery-and-monitoring/tests/integration/isMaster-network-error.yml, source/server-discovery-and-monitoring/tests/integration/isMaster-timeout.json, source/server-discovery-and-monitoring/tests/integration/isMaster-timeout.yml, source/server-discovery-and-monitoring/tests/integration/minPoolSize-error.json, source/server-discovery-and-monitoring/tests/integration/minPoolSize-error.yml, source/versioned-api/versioned-api.rst
The legacy hello command will not be part of API Version 1. This requires drivers to exclusively use "hello" when an API Version is declared (as any server that supports the Versioned API is also expected to support "hello"). In the case that users misconfigure their clients and declare an API Version when connecting to servers that don't support "hello", the server type is expected to be "unknown", eventually triggering errors.
Note that the "Remove oppressive language" project will change the usage of hello vs. legacy hello when not using the Versioned API.
I previously considered requiring using `OP_MSG` with the Versioned API, as all servers that would support "hello" also support `OP_MSG`. However, while building the implementation in libmongoc I realised that this may cause …
=> DRIVERS-1633 Require using "hello" command with versioned API

source/mongodb-handshake/handshake.rst
The intent is to define `isMaster` as legacy hello and use legacy hello in other specs rather than referring to `isMaster`.
=> DRIVERS-1293: Updated to define hello and legacy hello (aka isMaster)

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
https://jira.mongodb.org/browse/DRIVERS-1726
=> [CMAP] A pool must emit PoolReadyEvent before resuming the background thread

source/crud/tests/unified/aggregate.json, source/crud/tests/unified/aggregate.yml
DRIVERS-1739
This PR fixes the "aggregate with multiple batches works" test in `unified/aggregate.yml` test by updating it to match the "find with multiple batches works" test in `unified/find.yml`, hopefully fixing this for good. The latter uses an odd number of result documents with a batch size of 2, which should make it so that regardless of whether the server requires an extra round trip at the end of the results, the test should still work. I've tested in on 3.6+ standalones and it seems to work on all those versions.
=> DRIVERS-1739 Fix broken aggregation test

source/server-selection/server-selection.rst
Separated out the removal of slaveOk URI option from other spec changes in PR #976.
=> DRIVERS-1738: Removed deprecated URI option in favour of readPreference=secondaryPreferred.

source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml, source/versioned-api/tests/crud-api-version-1.json, source/versioned-api/tests/crud-api-version-1.yml, source/versioned-api/tests/transaction-handling.json, source/versioned-api/tests/transaction-handling.yml, source/versioned-api/versioned-api.rst
DRIVERS-1720
The server already allows passing Versioned API options to transaction-continuing commands (see https://github.com/mongodb/mongo/commit/4aa27885874b90e098c1225fccb10f4daa3b3d38), and ``getMore`` will get the same treatment soon. The server will require these options no later than RC0, so we can already make the spec change.
Note that drivers implementing this will have to wait until the latest build includes the commit above as well as the commit to change ``getMore`` behaviour.
=> DRIVERS-1720 Require passing Versioned API options to getMore and transaction-continuing commands

source/server-selection/server-selection-tests.rst, source/server-selection/server-selection.rst
Updated the terminology to use "not writable primary", "SecondaryOk", and similar in place of deprecated terms.
One notable change that may deserve some discussion. Since the `slaveOK` URI option is deprecated and no longer in `source/uri-options/uri-options.rst` I simply removed the section discussing it. Since this URI option has been deprecated for a long time, drivers should remove it from their connection string parsing logic in their next major release anyways. There is really no good way to change `slaveOk=true` into something else. Even if we rename the URI option, we will force customers using it to update their connection strings - and they should switch to using read preference anyways.
=> DRIVERS-1293: Updated Server Selection spec to use modern terminology.

source/unified-test-format/schema-1.0.json, source/unified-test-format/schema-1.1.json, source/unified-test-format/schema-1.2.json, source/unified-test-format/schema-1.3.json, source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-1754
Older schemas were taken from the last revision before being deleted:
* https://github.com/mongodb/specifications/commits/master/source/unified-test-format/schema-1.3.json
* https://github.com/mongodb/specifications/commits/master/source/unified-test-format/schema-1.2.json
* https://github.com/mongodb/specifications/commits/master/source/unified-test-format/schema-1.1.json
* https://github.com/mongodb/specifications/commits/master/source/unified-test-format/schema-1.0.json
The only exception is that I manually removed the stream entity from _all_ older files (per https://github.com/mongodb/specifications/commit/59d8f93199bad36a6e32c30f434aa33259788f88).
The Makefile can continue to validate files against the most recent minor version; however, …
=> DRIVERS-1754: Restore old unified test format schema versions

source/crud/tests/unified/bulkWrite-arrayFilters.json, source/crud/tests/unified/bulkWrite-arrayFilters.yml, source/crud/tests/unified/bulkWrite-delete-hint.json, source/crud/tests/unified/bulkWrite-delete-hint.yml, source/crud/tests/unified/bulkWrite-update-hint.json, source/crud/tests/unified/bulkWrite-update-hint.yml
Noticed while implementing the CRUD unified tests in PyMongo. Without unsetOrMatches the tests fail with:
```
FAIL: test_BulkWrite_updateMany_with_arrayFilters (test.test_crud_unified.TestUnifiedBulkWriteArrayFilters)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/shane/git/mongo-python-driver/test/unified_format.py", line 970, in test_case
self.run_scenario(spec)
File "/Users/shane/git/mongo-python-driver/test/unified_format.py", line 954, in run_scenario
self.run_operations(spec['operations'])
File "/Users/shane/git/mongo-python-driver/test/unified_format.py", line 890, in run_operations
self.run_entity_operation(op)
File "/Users/shane/git/mongo-python-driver/test/unified_format.py", line 779, in …
```
=> DRIVERS-1758 Fix missing unsetOrMatches for insertedIds in unified CRUD tests

source/versioned-api/tests/README.rst
With 5.0 being added to drivers-evergreen-tools, I wanted to clarify that the Versioned API tests should run on 5.0+, not only latest.
=> Clarify server versions to test with Versioned API

source/transactions/tests/unified/mongos-unpin.json, source/transactions/tests/unified/mongos-unpin.yml
No drivers ticket needed since this only changes a test name.
=> Fix typo in test name TransientTransctionError -> TransientTransactionError

source/collection-management/tests/timeseries-collection.json, source/collection-management/tests/timeseries-collection.yml
DRIVERS-1774
Moves the `expireAfterSeconds` time-series option to be a top-level `createCollection` option instead of one under `timeseries`. Changes its value to a `$numberLong` to specify that it should be stored as an `int64` or equivalent. Removes `outcome` expectation from the duplicate `_id` test because of potential variations in ordering of documents with duplicate `_id` fields in test runners.
=> DRIVERS-1774 Move expireAfterSeconds in time-series tests

source/collection-management/tests/timeseries-collection.json, source/collection-management/tests/timeseries-collection.yml
DRIVERS-1779
Adds the `granularity` option to the `createCollection` operations for time-series tests to ensure that drivers can support non-default granularities (like "minutes").
=> DRIVERS-1779 Add granularity option to time-series tests

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/README.rst, source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.json, source/connection-monitoring-and-pooling/tests/pool-checkout-no-idle.yml, source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.json, source/connection-monitoring-and-pooling/tests/pool-checkout-no-stale.yml, source/connection-monitoring-and-pooling/tests/pool-clear-min-size.json, source/connection-monitoring-and-pooling/tests/pool-clear-min-size.yml, source/connection-monitoring-and-pooling/tests/pool-create-min-size-error.json, source/connection-monitoring-and-pooling/tests/pool-create-min-size-error.yml
Use the new option in `pool-checkout-no-idle.yml`, `pool-checkout-no-stale.yml` to disable background thread runs.
Use the new option in `pool-clear-min-size.yml` and `pool-create-min-size-error.yml` to specify 50 ms delay between runs.
DRIVERS-1724
=> DRIVERS-1724 Add `backgroundThreadIntervalMS` pool option to CMAP test specification

source/transactions/tests/legacy/errors-client.json, source/transactions/tests/legacy/errors-client.yml, source/unified-test-format/tests/valid-pass/poc-transactions.json, source/unified-test-format/tests/valid-pass/poc-transactions.yml
https://jira.mongodb.org/browse/DRIVERS-1237
Since dots/dollars are no longer prohibited, these tests can use update/replace validation to yield a client-side error.
=> DRIVERS-1237: Do not rely on dotted field for client-side error

source/bson-corpus/tests/top.json
https://jira.mongodb.org/browse/DRIVERS-1173
These were missed in the original PR (#996). Invalid DBRef documents are no longer parse errors but should be left as-is.
=> DRIVERS-1173: Remove DBRef parse error tests

source/crud/tests/unified/aggregate-let.json, source/crud/tests/unified/aggregate-let.yml
https://jira.mongodb.org/browse/DRIVERS-776
Original test was renamed and skipped on mongos to work around [SERVER-57403](https://jira.mongodb.org/browse/SERVER-57403). A separate test was introduced for the time being, which should run on mongos.
cc: @addaleax
=> DRIVERS-776: Splits tests to work around SERVER-57403

source/crud/tests/unified/aggregate-let.json, source/crud/tests/unified/aggregate-let.yml
For historical reasons, some drivers have different code paths for aggregating to a collection.
=> DRIVERS-776: Add tests for aggregate with $out using let option

source/load-balancers/load-balancers.rst
Drivers in load balanced mode must either document this is not allowed or explicitly prevent it.
=> DRIVERS-1789: Add guidance on concurrent cursor ops

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
The load balancer section was placed too far up the document and caused the single topology type subsections to appear under the load balancer heading.
=> DRIVERS-1790: Fixing SDAM section order for topology types

source/retryable-reads/tests/listCollectionObjects-serverErrors.yml, source/retryable-reads/tests/listCollectionObjects.yml, source/retryable-reads/tests/listDatabaseObjects-serverErrors.yml, source/retryable-reads/tests/listDatabaseObjects.yml
Added links to the Enumerating Databases and Enumerating Collections specs in the Retryable Reads spec tests for listDatabaseObjects and listCollectionObjects.
=> Clarified listDatabaseObjects and listCollectionObjects spec tests

source/command-monitoring/tests/unified/redacted-commands.json, source/command-monitoring/tests/unified/redacted-commands.yml, source/unified-test-format/unified-test-format.rst
An explicit flag to override a unified test runner's default behavior of ignoring commands with sensitive information.
=> DRIVERS-1653 Add observeSensitiveCommands property to the client entity type

source/versioned-api/tests/transaction-handling.json, source/versioned-api/tests/transaction-handling.yml
It seems in #961 where load balancer testing support was added the schema version should have been bumped in these files as they run against the load-balanced topology.
=> Fix schema version in versioned API transaction handling test file

source/wireversion-featurelist.rst
@kevinAlbs mentioned in https://github.com/mongodb/mongo-c-driver/pull/802#pullrequestreview-688918765 that wire version 12 was for 4.9. Now that 5.0 RCs are available for any pre-release testing, we can just use 13.
I'm not sure what additional features are present in wire version 13 that can be added to the feature list in the second column. If anyone has specific suggestions feel free to make a suggestion on the PR.
=> Use wire version 13 for 5.0 servers

source/retryable-reads/tests/README.rst, source/retryable-writes/tests/README.rst
This PR adds an error label to the failpoint used in the `PoolClearedError` retryable writes test. Without it, the test would fail on MongoDB 4.4+. This PR also adds information regarding the minimum MongoDB version required to run the retryability tests against.
=> DRIVERS-1483 Add error label to retryable writes `PoolClearedError` prose test

source/crud/tests/unified/insertOne-dots_and_dollars.json, source/crud/tests/unified/insertOne-dots_and_dollars.yml
This was inadvertently added in 851ca10388cced05117ceace0ced4b7e1aac02c4
Addresses an issue reported by @nbbeeken in [DRIVERS-1237](https://jira.mongodb.org/browse/DRIVERS-1237?focusedCommentId=3901764&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3901764).
=> DRIVERS-1237: Do not assert insertedCount field for insertOne results

source/sessions/tests/unified/snapshot-sessions-not-supported-server-error.json, source/sessions/tests/unified/snapshot-sessions-not-supported-server-error.yml
To fix this I deleted the json file and ran make to auto-generate the json from yaml. That's why the other changes show up here. 
Edit: I updated the test to run on all topologies <5.0 and all standalone servers (including 5.0+). 3.6 standalones report this expected error:
```
{'ok': 0.0, 'errmsg': "readConcern.level must be either 'local', 'majority', 'linearizable', or 'available'", 'code': 9, 'codeName': 'FailedToParse'}
```
4.0+ standalones report:
```
{'ok': 0.0, 'errmsg': 'read concern level snapshot is only valid in a transaction', 'code': 72, 'codeName': 'InvalidOptions'}
```
5.0+ standalones report:
```
{'ok': 0.0, 'errmsg': 'node needs to be a replica set member to use readConcern: snapshot', 'code': 123, 'codeName': 'NotAReplicaSet'}
```
=> DRIVERS-1607 Fix topologies field in snapshot reads test

source/sessions/snapshot-sessions.rst, source/sessions/tests/unified/snapshot-sessions-not-supported-client-error.json, source/sessions/tests/unified/snapshot-sessions-not-supported-client-error.yml, source/sessions/tests/unified/snapshot-sessions-not-supported-server-error.json, source/sessions/tests/unified/snapshot-sessions-not-supported-server-error.yml
Updated to require drivers raise a client-side error "snapshot reads require MongoDB 5.0 or later" when a snapshot read is attempted on < 5.0.
Note: I have a POC of this change here: https://github.com/mongodb/mongo-python-driver/pull/659
=> DRIVERS-1820 Snapshot reads raise client-side error on <5.0

source/retryable-reads/tests/mapReduce.json, source/retryable-reads/tests/mapReduce.yml
[DRIVERS-1603](https://jira.mongodb.org/browse/DRIVERS-1603)
`mapReduce` operation is not intended to work on serverless (see comment from [CLOUDP-93419](https://jira.mongodb.org/browse/CLOUDP-93419))
=> DRIVERS-1603: Exclude mapReduce from serverless testing

source/sessions/snapshot-sessions.rst, source/sessions/tests/unified/snapshot-sessions-unsupported-ops.json, source/sessions/tests/unified/snapshot-sessions-unsupported-ops.yml, source/sessions/tests/unified/snapshot-sessions.json, source/sessions/tests/unified/snapshot-sessions.yml
This PR requires drivers to send readConcern with all commands in a snapshot session (even writes). This effectively bans all unsupported operations in a snapshot session because the server will reject commands that do not support readConcern.level "snapshot". For example:
```
MongoDB Enterprise repl0:PRIMARY> db.runCommand({'listCollections': 'test', readConcern: {level: 'snapshot'}})
{
"ok" : 0,
"errmsg" : "Command listCollections does not support { readConcern: { level: \"snapshot\", provenance: \"clientSupplied\" } } :: caused by :: read concern not supported",
"code" : 72,
"codeName" : "InvalidOptions"
}
MongoDB Enterprise repl0:PRIMARY> db.runCommand({'insert': 'test', documents: [{}], readConcern: {level: 'snapshot'}})
{
"ok" : 0,
"errmsg" : "Command insert does not support { …
```
=> DRIVERS-1819 Snapshot session sends readConcern with all commands even writes

source/crud/tests/unified/insertMany-dots_and_dollars.json, source/crud/tests/unified/insertMany-dots_and_dollars.yml, source/crud/tests/unified/insertOne-dots_and_dollars.json, source/crud/tests/unified/insertOne-dots_and_dollars.yml, source/unified-test-format/tests/valid-pass/poc-crud.json, source/unified-test-format/tests/valid-pass/poc-crud.yml, source/unified-test-format/tests/valid-pass/poc-retryable-writes.json, source/unified-test-format/tests/valid-pass/poc-retryable-writes.yml, source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-1828
I ran the modified tests through PHPLIB, but would appreciate it if someone else tests in their driver as well.
=> DRIVERS-1828: Remove insertedCount and improve use of $$unsetOrMatches

source/command-monitoring/tests/unified/redacted-commands.json, source/command-monitoring/tests/unified/redacted-commands.yml, source/unified-test-format/schema-1.5.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/invalid/entity-client-observeSensitiveCommands-type.json, source/unified-test-format/tests/invalid/entity-client-observeSensitiveCommands-type.yml
DRIVERS-1816
This does not cover replies to all commands, since we're only able to make assertions against successful commands. With some authentication commands, getting them to work is a sizeable effort. For that reason, it's up to engineers to ensure they're not just redacting replies to the commands where we test this, but rather all commands. This includes replies that are potentially sensitive, e.g. replies for `saslStart` and `saslContinue`.
Note that due to a limitation of the unified test format, we can't make assertions against the contents of CommandFailedEvents. While the spec doesn't explicitly mention this event, it is assumed that drivers redact replies when they are exposed in CommandFailedEvents. That said, most if not all replies will not contain sensitive information, …
=> DRIVERS-1816 Test redaction of replies to security sensitive commands

source/crud/tests/README.rst, source/crud/tests/v1/read/aggregate-collation.json, source/crud/tests/v1/read/aggregate-collation.yml, source/crud/tests/v1/read/aggregate-out.json, source/crud/tests/v1/read/aggregate-out.yml, source/crud/tests/v1/read/count-collation.json, source/crud/tests/v1/read/count-collation.yml, source/crud/tests/v1/read/distinct-collation.json, source/crud/tests/v1/read/distinct-collation.yml, source/crud/tests/v1/read/find-collation.json, source/crud/tests/v1/read/find-collation.yml, source/crud/tests/v1/write/bulkWrite-collation.json, source/crud/tests/v1/write/bulkWrite-collation.yml, source/crud/tests/v1/write/deleteMany-collation.json, source/crud/tests/v1/write/deleteMany-collation.yml, source/crud/tests/v1/write/deleteOne-collation.json, source/crud/tests/v1/write/deleteOne-collation.yml, source/crud/tests/v1/write/findOneAndDelete-collation.json, source/crud/tests/v1/write/findOneAndDelete-collation.yml, source/crud/tests/v1/write/findOneAndReplace-collation.json, source/crud/tests/v1/write/findOneAndReplace-collation.yml, source/crud/tests/v1/write/findOneAndUpdate-collation.json, source/crud/tests/v1/write/findOneAndUpdate-collation.yml, source/crud/tests/v1/write/replaceOne-collation.json, source/crud/tests/v1/write/replaceOne-collation.yml, source/crud/tests/v1/write/updateMany-collation.json, source/crud/tests/v1/write/updateMany-collation.yml, source/crud/tests/v1/write/updateOne-collation.json, source/crud/tests/v1/write/updateOne-collation.yml
DRIVERS-1851
Atlas Serverless doesn't currently support `$out` aggregations or collation, so the associated crud-v1 tests need to be skipped. This involved slightly amending the crud-v1 format.
=> DRIVERS-1851 Skip crud-v1 tests for $out and collation on Serverless

source/client-side-encryption/tests/README.rst
The KMS TLS prose tests were not clear on how to start a KMS mock server with the [mock_kms script](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/csfle/mock_kms.js). Gives an example of starting a KMS mock server, acknowledges that TLS cert verification errors will have language-dependent messages, and removes misleading `mongodb://` protocol name on the KMS masterKeys.
=> Clarify KMS TLS prose tests

source/sessions/tests/README.rst
Skipping a DRIVERS ticket for this since it's the first and only prose test for sessions.
See: https://github.com/mongodb/specifications#prose-test-numbering
=> Use numbering for session prose test

source/command-monitoring/tests/legacy/find.json, source/command-monitoring/tests/legacy/find.yml
The modifiers option was removed from the crud spec long ago. See https://jira.mongodb.org/browse/DRIVERS-1879.
I'm testing this change in https://github.com/mongodb/mongo-python-driver/pull/696
=> DRIVERS-1879 Remove modifiers option from command monitoring spec test

source/sessions/snapshot-sessions.rst, source/sessions/tests/unified/snapshot-sessions-not-supported-client-error.json, source/sessions/tests/unified/snapshot-sessions-not-supported-client-error.yml, source/unified-test-format/schema-1.0.json, source/unified-test-format/schema-1.1.json, source/unified-test-format/schema-1.2.json, source/unified-test-format/schema-1.3.json, source/unified-test-format/schema-1.4.json, source/unified-test-format/schema-1.5.json, source/unified-test-format/tests/invalid/test-expectEvents-minItems.json, source/unified-test-format/tests/invalid/test-expectEvents-minItems.yml, source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-1878
=> DRIVERS-1878: Tests for client-side errors with snapshot reads use incorrect syntax for test.expectEvents

source/command-monitoring/command-monitoring.rst, source/command-monitoring/tests/unified/pre-42-server-connection-id.json, source/command-monitoring/tests/unified/pre-42-server-connection-id.yml, source/command-monitoring/tests/unified/server-connection-id.json, source/command-monitoring/tests/unified/server-connection-id.yml, source/unified-test-format/schema-1.6.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/invalid/expectedCommandEvent-commandFailedEvent-hasServerConnectionId-type.json, source/unified-test-format/tests/invalid/expectedCommandEvent-commandFailedEvent-hasServerConnectionId-type.yml, source/unified-test-format/tests/invalid/expectedCommandEvent-commandStartedEvent-hasServerConnectionId-type.json, source/unified-test-format/tests/invalid/expectedCommandEvent-commandStartedEvent-hasServerConnectionId-type.yml, source/unified-test-format/tests/invalid/expectedCommandEvent-commandSucceededEvent-hasServerConnectionId-type.json, source/unified-test-format/tests/invalid/expectedCommandEvent-commandSucceededEvent-hasServerConnectionId-type.yml, source/unified-test-format/unified-test-format.rst
DRIVERS-1141
Adds a new `serverConnectionId` field to `CommandStartedEvent`, `CommandSucceededEvent` and `CommandFailedEvent` so users of APM can correlate client-side `connectionId`s with server-side `serverConnectionId`s (see ticket for more details). Adds a new unified command monitoring test to verify that `serverConnectionId` is present in command monitoring events. 
Adds a new `hasServerConnectionId` field to `commandStartedEvent`, `commandSucceededEvent` and `commandFailedEvent` in the unified test format. This field is similar to the existing [`hasServiceId`](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#hasserviceid) field and lets us assert the existence of `serverConnectionId` without explicitly checking its value …
=> DRIVERS-1141 Add serverConnectionId to command monitoring events

source/command-monitoring/command-monitoring.rst, source/unified-test-format/unified-test-format.rst
DRIVERS-1141
Updates spec versions, last modified dates and change logs for the command monitoring and unified test format specs. Forgot to do this as part of #1050.
=> DRIVERS-1141 Update command monitoring and UTF spec versions

source/find_getmore_killcursors_commands.rst
Exhaust cursors cannot be implemented using OP_QUERY / OP_GET_MORE on 5.1+ servers due to [SERVER-57391](https://jira.mongodb.org/browse/SERVER-57391). Since exhaust cursors are only implemented on a handful of drivers, I intend to keep this change minimal.
=> DRIVERS-1857 Use OP_MSG for exhaust cursors on 3.6+

source/unified-test-format/unified-test-format.rst
I left spec version as-is and didn't bother changing the last updated date or change log since this is part of the same drivers ticket/clarification work you just did, but let me know if you think I should do so.
=> DRIVERS-1554 Clarify internal per-mongos clients may be used for targetedFailPoint

source/change-streams/change-streams.rst
DRIVERS-1896
Clarifies that server selection during change stream resumption should not only respect the original `aggregate`'s read preference but also follow the regular rules of server selection.
It seems that this detail was implied, but we may as well make it explicit and verify that all drivers have the same behavior.
=> DRIVERS-1896 Clarify server selection process for change stream resume

source/bson-corpus/bson-corpus.rst, source/bson-corpus/tests/document.json, source/bson-corpus/tests/regex.json, source/bson-corpus/tests/top.json
https://jira.mongodb.org/browse/DRIVERS-1621
POC PR: https://github.com/mongodb/mongo-php-driver/pull/1255
=> DRIVERS-1621: Prohibit null bytes in document field names and regex components

source/bson-corpus/tests/binary.json
The new test only validates correct subtype number encoding/decoding and binary data encoding/decoding. The binary data itself is not validated. DRIVERS-1875 states the data intended to be stored is "meant to be opaque", so I believe this should satisfy current requirements.
=> DRIVERS-1875 Add BSON corpus test for binary subtype 7

source/bson-corpus/bson-corpus.rst
https://jira.mongodb.org/browse/DRIVERS-1621
=> DRIVERS-1621: Clarify error expectation rules for parseErrors

source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst, source/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.json, source/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.yml, source/polling-srv-records-for-mongos-discovery/polling-srv-records-for-mongos-discovery.rst, source/uri-options/tests/srv-service-name-option.json, source/uri-options/tests/srv-service-name-option.yml, source/uri-options/uri-options.rst
DRIVERS-521
Allow the use of custom SRV service names for SRV lookup using a new `srvServiceName` URI option. Clarify that during initial DNS seedlist discovery and SRV polling, the value of `srvServiceName` should be prefixed to the URI and `mongodb` should only be used as a service name if `srvServiceName` is not specified.
Prototype available in Go [here](https://github.com/benjirewis/mongo-go-driver/tree/customServiceName).
=> DRIVERS-521 Allow custom service names with srvServiceName URI option

source/initial-dns-seedlist-discovery/tests/README.rst, source/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.json, source/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.yml, source/uri-options/tests/srv-service-name-option.json, source/uri-options/tests/srv-service-name-option.yml
DRIVERS-521
Switches endpoint of `srvServiceName` URI options spec tests from `test1` to `test22`. Because `_mongodb._tcp.test1.test.build.10gen.cc` and `_customname._tcp.test1.test.build.10gen.cc` had the same value after SRV lookup, the new spec tests did not really assess whether drivers were appending the custom service name correctly. Since `_mongdb._tcp.test22.test.build.10gen.cc` does not exist, drivers must append a custom service name correctly to successfully hit the endpoint.
=> DRIVERS-521 Use test22 for custom service name endpoint

source/uri-options/tests/README.rst, source/uri-options/tests/srv-options.json, source/uri-options/tests/srv-options.yml
https://jira.mongodb.org/browse/DRIVERS-1959
SRV option tests will either raise errors (e.g. using options with non-SRV scheme) or warnings (e.g. invalid value/type), but not both. This corrects a mistake originally introduced in b508f6d2a1819882d40c4e7e73b95fc8ae3bdfe5 (#1069).
=> DRIVERS-1959: Expect either valid:false or warning:true, but not both

source/client-side-encryption/tests/README.rst
"no_tls" is misleading. TLS is still enabled.
tlsClientCertificateKeyFile is not set.
=> DRIVERS-1353 client_encryption_no_tls => client_encryption_no_client_cert

source/ocsp-support/tests/README.rst
=> DRIVERS-1730 clarify OCSP stapling tests are not supported on all Linux platforms

source/client-side-encryption/tests/README.rst
Port 8002 should be used for client_encryption_no_tls and client_encryption_with_tls.
Port 8000 should be used for client_encryption_expired.
Port 8001 should be used for client_encryption_invalid_hostname
The AWS test cases require specifying the endpoint through the masterKey document. The C PoC had tested this behavior [here](https://github.com/mongodb/mongo-c-driver/pull/881/files#diff-d363a5539f2fbabfadf2d7cc6cdb96a203fb63f2caa31bae731c3e12d97b204cR2862-R2920), but I wrote the test cases incorrectly.
=> DRIVERS-1353 fix AWS cases KMS TLS Options Tests

source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/legacy/bulkWrite-serverErrors.json, source/retryable-writes/tests/legacy/bulkWrite-serverErrors.yml, source/retryable-writes/tests/legacy/deleteOne-serverErrors.json, source/retryable-writes/tests/legacy/deleteOne-serverErrors.yml, source/retryable-writes/tests/legacy/findOneAndDelete-serverErrors.json, source/retryable-writes/tests/legacy/findOneAndDelete-serverErrors.yml, source/retryable-writes/tests/legacy/findOneAndReplace-serverErrors.json, source/retryable-writes/tests/legacy/findOneAndReplace-serverErrors.yml, source/retryable-writes/tests/legacy/findOneAndUpdate-serverErrors.json, source/retryable-writes/tests/legacy/findOneAndUpdate-serverErrors.yml, source/retryable-writes/tests/legacy/insertMany-serverErrors.json, source/retryable-writes/tests/legacy/insertMany-serverErrors.yml, source/retryable-writes/tests/legacy/insertOne-serverErrors.json, source/retryable-writes/tests/legacy/insertOne-serverErrors.yml, source/retryable-writes/tests/legacy/replaceOne-serverErrors.json, source/retryable-writes/tests/legacy/replaceOne-serverErrors.yml, source/retryable-writes/tests/legacy/updateOne-serverErrors.json, source/retryable-writes/tests/legacy/updateOne-serverErrors.yml, source/transactions/tests/legacy/error-labels.json, source/transactions/tests/legacy/error-labels.yml, source/transactions/tests/legacy/mongos-recovery-token.json, source/transactions/tests/legacy/mongos-recovery-token.yml, source/transactions/tests/legacy/retryable-abort.json, source/transactions/tests/legacy/retryable-abort.yml, source/transactions/tests/legacy/retryable-commit.json, source/transactions/tests/legacy/retryable-commit.yml
Updates spec language and spec tests always to specify error labels at the top level. This behavior is verified in the comments of DRIVERS-1385.
=> DRIVERS-1385 Always specify error labels at the top level

source/crud/crud.rst
https://jira.mongodb.org/browse/DRIVERS-1969
Only fall back to a primary read preference if there is evidence that the driver is connected to a pre-5.0 server.
=> DRIVERS-1969: Revise rules for $out/$merge read preferences

source/atlas-data-lake-testing/tests/estimatedDocumentCount.json, source/atlas-data-lake-testing/tests/estimatedDocumentCount.yml
Atlas Data Lake has bumped its maxWireVersion to 13, which
triggers a change in driver behavior to use aggregate instead
of count command for the estimatedDocumentCount helper.
DRIVERS-1991
=> Update estimatedDocumentCount test

source/atlas-data-lake-testing/tests/estimatedDocumentCount.json, source/atlas-data-lake-testing/tests/estimatedDocumentCount.yml
The data lake tests currently use the legacy CRUD v2 (same as the legacy transactions) test format where commandName and databaseName should be named command_name and database_name.
=> DRIVERS-1991 Fix data lake tests which use legacy test format

source/server-selection/tests/server_selection/Unknown/read/ghost.json, source/server-selection/tests/server_selection/Unknown/read/ghost.yml, source/server-selection/tests/server_selection/Unknown/write/ghost.json, source/server-selection/tests/server_selection/Unknown/write/ghost.yml
This is tested by the Python driver here: https://github.com/mongodb/mongo-python-driver/pull/806, see https://spruce.mongodb.com/version/61a803745623432084f4fe64/tasks
Note that in pymongo I needed to update the test runner to handle the RSGhost server type. Other drivers may need to do the same:
```
diff --git a/test/utils_selection_tests.py b/test/utils_selection_tests.py
index 0006f6f6..de10312c 100644
--- a/test/utils_selection_tests.py
+++ b/test/utils_selection_tests.py
@@ -63,7 +63,7 @@ def make_server_description(server, hosts):
return ServerDescription(clean_node(server['address']), Hello({}))
hello_response = {'ok': True, 'hosts': hosts}
-    if server_type != "Standalone" and server_type != "Mongos":
+    if server_type not in ("Standalone", "Mongos", "RSGhost", "RSGhost"): …
```
=> DRIVERS-1999 Add server selection spec test to ensure that RSGhost servers are not selectable

source/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-invalid_integer.json, source/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-invalid_integer.yml, source/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-invalid_type.json, source/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-invalid_type.yml, source/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-invalid_integer.json, source/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-invalid_integer.yml, source/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-invalid_type.json, source/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-invalid_type.yml
https://jira.mongodb.org/browse/DRIVERS-2006
These cases should raise warnings, not errors. Since they are already tested by existing uri-options spec tests, these files can simply be removed.
=> DRIVERS-2006: Remove srvMaxHosts tests expecting an error for invalid values

source/socks5-support/socks5.rst, source/socks5-support/tests/README.rst, source/uri-options/tests/proxy-options.json, source/uri-options/tests/proxy-options.yml, source/uri-options/uri-options.rst
Node.js driver implementation PR: https://github.com/mongodb/node-mongodb-native/pull/3041
=> DRIVERS-1357 Add SOCKS5 proxy support spec

source/find_getmore_killcursors_commands.rst
- Require OP_MSG for exhaust cursors on 5.1+ instead of 3.6+.
- Relax requirement from MUST to SHOULD, and permit falling back to a non-exhaust cursor.
Exhaust cursors are [underspecified](https://jira.mongodb.org/browse/DRIVERS-535) and not implemented in all drivers.
Falling back to a non-exhaust cursor matches the proposed approach in https://github.com/mongodb/mongo-c-driver/pull/912.
Exhaust cursors with OP_QUERY only impact the C driver. Previously it was thought to affect Ruby as well. RUBY-2770 determined it is not possible to request an exhaust cursor.
=> DRIVERS-1857 relax exhaust cursor requirements

source/enumerate-collections.rst
A few things to ask/note about this ticket/PR:
1. The proposed changes in this spec may change the behavior of the `listCollectionNames` driver helper to list only the collections that the user has access to, as opposed to returning all collection names (which requires database wide access).
2. That said, should the `authorizedCollections` be forcibly set to true (i.e. even if the user provides the option as false) or just defaulted to true?
- On the one hand, this is would match the behavior of the `db.getCollectionNames()` shell command, and it is still possible to retrieve all of the collections using `listCollections`.
- On the other hand, we might not want to change the functionality of `listCollectionNames` and provide the users the option to retrieve all collection names. The Ruby …
=> DRIVERS-1393 listCollectionNames should use authorizedCollections argument

source/message/OP_MSG.rst
The original intention of this paragraph was to allow newer drivers published after MongoDB 3.6 to avoid implementing OP_QUERY purely for an initial handshake. Drivers that have historically supported pre-3.6 servers should continue to use OP_QUERY to ensure that meaningful error messages are raised when connecting to an old server instead of a silently dropped connection due to an unrecognized protocol.
----
Note: I skipped making a DRIVERS ticket for this to reduce overhead. If someone feels one is necessary I can do so.
=> Clarify that old drivers should default to OP_QUERY handshakes

source/load-balancers/load-balancers.rst
- Clarify that load balanced transactions must have exclusive access to pinned connection.
The `all operations go to the same mongos` test in https://github.com/mongodb/specifications/blob/master/source/load-balancers/tests/transactions.yml asserts this behavior. It runs multiple insert operations within a transaction and asserts only one `connectionCheckedOutEvent`.
I surveyed drivers here: [spreadsheet](https://docs.google.com/spreadsheets/d/1KYdZECD9NZRePk9U07ThUlUCE1QQBlIUZvpn-Nc-eZc/edit?usp=sharing). This found that Ruby pins to a `ServiceID` rather than a connection. I was unable to determine for the Node driver.
If a transaction does not have exclusive access to a load balanced connection, it may be unable to make progress if it cannot check out another connection to the same …
=> DRIVERS-1953 LB txns have exclusive connection

source/wireversion-featurelist.rst
https://jira.mongodb.org/browse/DRIVERS-2026
Also document how server 5.1+ calculates wire version
=> DRIVERS-2026: Add wire versions for 5.1 through 5.3

source/causal-consistency/causal-consistency.rst
DRIVERS-1374
Removing test that is incorrect due to SPEC-1019
=> DRIVERS-1374: remove outdated causal consistency test

.github/workflows/check_schema_version.sh, .github/workflows/unified-test-format-schema-check.yml, source/load-balancers/tests/cursors.json, source/load-balancers/tests/cursors.yml, source/load-balancers/tests/sdam-error-handling.json, source/load-balancers/tests/sdam-error-handling.yml, source/load-balancers/tests/transactions.json, source/load-balancers/tests/transactions.yml
I've made a script here that will grep for all json files that have a schemaVersion, and use that value in an `ajv` command to check that its a valid schema.
You can see what a failure looks like in the first commit's CI.
This uncovered missed version changes in: 
- `source/load-balancers/tests/cursors.yml`
- `source/load-balancers/tests/sdam-error-handling.yml`
- `source/load-balancers/tests/transactions.yml`
So we may want to change the ticket to drivers changes needed, but the impact might be non-existent if these tests have been sync-ed and no issues reported thus far.
Additionally made some drive-by improvements of the ci file, updated action/node/python versions simply to not let those run out of date. 
https://jira.mongodb.org/browse/DRIVERS-1767
=> DRIVERS-1767: test all json files with a schemaVersion against their corresponding schema

source/crud/crud.rst
https://jira.mongodb.org/browse/DRIVERS-1899
For write commands, this was previously inferable by existing documentation for the "acknowledged" property of Write Results. Likewise for findAndModify, comments suggested that the return value could be null. This change makes the documentation more explicit.
Also adds explicit documentation that InsertOneResult and InsertManyResult are not required, which was previously inferable.
Note: this is a spec clarification, so no driver changes are needed.
=> DRIVERS-1899: Permit optional results for unacknowledged write concerns

source/causal-consistency/causal-consistency.rst
RST formatting was previously broken by db967c5575c60385a8362ca5eef1fc1ce799b517.
Also adds missing changelog entries for 1a5ddeefb4c01180bf06d06ac651e7571ab29910 (DRIVERS-1607) and 568093ce7f0e1394cf4952c417e1e7dacc5fef53 (DRIVERS-1374).
Since both of those changes should have constituted a minor version bump, the spec version has been retroactively increased from 1.0 to 1.2.
=> Fix RST formatting and bump spec version

source/uri-options/tests/tls-options.json, source/uri-options/tests/tls-options.yml
I came across this duplicate test while fixing up the node driver uri spec runner. It's a minor thing, but it does mess with our IDE test runner tooling.
=> test: remove duplicate tls option test

source/sessions/driver-sessions.rst
https://jira.mongodb.org/browse/DRIVERS-1030
The language change is on the light side but the undertaking for this change is likely large for most drivers. I could use some discussion guidance on more rigorous prose tests to reccomend to drivers. 
The key pain point we're trying to solve is that connection pool size is the true to limit to how many concurrent operations can happen against a particular node, by obtaining implicit sessions after we've checkedOut we can be sure we're not creating a larger than necessary pool of sessions.
I looked at Transactions and LB and to my knowledge there isn't an impact to those specs, transactions are using explicit sessions, and LB will behave the same it has the continued concern of using the same connection related to a given session.
=> DRIVERS-1030: Implicit sessions allocate underlying server session after connection checkout

source/load-balancers/load-balancers.rst
Services now enable load balancing by the `--loadBalancerPort` option which requires the v1 or v2 proxy protocol to be enabled in the load balancer. Drivers wishing to bypass the load balancer and connect directly must do so now on the original service port without enabling load balancer mode. This PR updates the downstream wording to reflect this.
=> fix(DRIVERS-1983): update direct connection details

source/sessions/driver-sessions.rst
Circling back after a POC/implementation has been attempted in Java.
Some improvements to the test details, as well as permitting drivers to treat explicit sessions the same way, as long as they continue to function the same from a user's perspective it should be fine to treat the logic the same for both.
=> DRIVERS-1030: Session allocation should occur after connection checkout - test improvements

source/auth/auth.rst, source/auth/tests/connection-string.json, source/auth/tests/connection-string.yml, source/connection-string/tests/valid-auth.json, source/connection-string/tests/valid-auth.yml, source/uri-options/tests/auth-options.json, source/uri-options/tests/auth-options.yml
Updates the auth spec to allow drivers to allow a `SERVICE_HOST` property in their auth mechanism properties, which replaces the default host in the service principal name to the provided attribute.
Node impl: https://github.com/mongodb/node-mongodb-native/pull/3123
=> feat(DRIVERS-1108): add service host to mech props

source/client-side-encryption/tests/README.rst
Replace use of "example.com" in Client Side Encryption prose tests with "doesnotexist.invalid".
- Test expectations in "Custom Endpoint Test" Cases 6, 7, and 8 change from parsing errors to DNS resolution errors.
- The error expectation for Case 9 has not changed from "Invalid KMS response". The error comes from the response to the oauth request. The oauth request is still sent to a valid endpoint, but requests permissions to an [invalid scope](https://github.com/mongodb/libmongocrypt/blob/master/src/mongocrypt-kms-ctx.c#L1305-L1311).
Here is a PoC of the updated tests with the C driver: https://github.com/mongodb/mongo-c-driver/pull/942 with passing Client Side Encryption tests.
See DRIVERS-2191 for a repro. Sending AWS signed requests to example.com has been recently (as of 02/04/2022) …
=> DRIVERS-2191 Remove use of example.com in Client Side Encryption prose tests

source/auth/auth.rst
See DRIVERS-2180 for context, and https://github.com/mongodb-js/kerberos/pull/141 for the corresponding Node.js bugfix PR.
=> DRIVERS-2180 Clarify Kerberos on Windows credentials passing

source/client-side-encryption/client-side-encryption.rst
The test plan was hardcoded to link to a very old commit instead of to the current version of the test README.
=> Fix test plan link in client-side-encryption

source/initial-dns-seedlist-discovery/tests/README.rst, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection.json, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection.yml, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-replicaSet-errors.json, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-replicaSet-errors.yml, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-true-txt.json, source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-true-txt.yml, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.yml, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero-txt.json, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero-txt.yml, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero.json, source/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero.yml
Currently the `mongo-orchestration` changes made with [DRIVERS-1983](https://jira.mongodb.org/browse/DRIVERS-1983) break some initial DNS seedlist discovery load-balanced tests because the driver must now connect to the load balancer to work correctly when in load-balanced mode. See this [comment](https://jira.mongodb.org/browse/GODRIVER-2292?focusedCommentId=4355123&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4355123) for more details about the test failures.
[BUILD-14668](https://jira.mongodb.org/browse/BUILD-14668) adds two new SRV records:
* `_mongodb._tcp.test23.test.build.10gen.cc.   86400  IN SRV  8000   localhost.test.build.10gen.cc.`
* `_mongodb._tcp.test24.test.build.10gen.cc.   86400  IN SRV  8000   localhost.test.build.10gen.cc.`
and one new …
=> DRIVERS-2224 Fix load-balanced DNS seedlist discovery tests for new dedicated lb port.

source/client-side-encryption/tests/README.rst
The current port selection is the same ports used by haproxy for LB testing.
I'm not sure if we need a drivers ticket here there's no functional changes needed to anyones testing if they didn't run into this themselves, changing this now would just make future implementers pick a port that doesn't conflict. 
Please let me know if I should file one.
=> chore: suggest ports for CSFLE testing that don't conflict with loadbalancer test port

source/crud/tests/unified/bulkWrite-updateMany-let.json, source/crud/tests/unified/bulkWrite-updateMany-let.yml, source/crud/tests/unified/bulkWrite-updateOne-let.json, source/crud/tests/unified/bulkWrite-updateOne-let.yml
https://jira.mongodb.org/browse/DRIVERS-2226
Successful patch from the Node driver - https://spruce.mongodb.com/version/622618297742ae6d299817b2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-2226: bump minServerVersion to 4.2 for bulkwrite-update*let tests

source/server-selection/server-selection-tests.rst
The "Prose Test" in server-selection-tests.rst specifies configuring a `failCommand` fail point with the `blockTimeMS` option.
~~[SERVER-53512](https://jira.mongodb.org/browse/SERVER-53512)~~ [SERVER-41070](https://jira.mongodb.org/browse/SERVER-41070) added a `failCommand` fail point with `blockTimeMS` in ~~4.9.0~~ 4.2.9.
=> note that 4.2.9 server is required for server selection prose test

.github/CODEOWNERS
=> Fix CODEOWNERS rule for unowned specs

source/sessions/driver-sessions.rst
http://jira.mongodb.org/browse/DRIVERS-2218
* Clarify the purpose and goal of session limiting
* Adjust test 13 to correctly assert the optimal solution
* ~Clean up code snippets and test bullets~ moved to #1158
=> DRIVERS-2218: Clarify intended bounding of implicit session allocation and rework flaky prose test

source/change-streams/change-streams.rst, source/change-streams/tests/unified/change-streams.json, source/change-streams/tests/unified/change-streams.yml, source/crud/crud.rst, source/crud/tests/unified/aggregate.json, source/crud/tests/unified/aggregate.yml, source/crud/tests/unified/find-comment.json, source/crud/tests/unified/find-comment.yml
https://jira.mongodb.org/browse/DRIVERS-2243 - Fix OperationFailure on MongoDB <4.4.0
https://jira.mongodb.org/browse/DRIVERS-2244 - Test getMore with comment on all topologies
=> Fix getMore with comment specs

source/auth/auth.rst, source/auth/tests/mongodb-aws.rst, source/benchmarking/benchmarking.rst, source/change-streams/change-streams.rst, source/change-streams/tests/README.rst, source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/subtype6.rst, source/client-side-encryption/tests/README.rst, source/client-side-operations-timeout/client-side-operations-timeout.rst, source/collation/collation.rst, source/conf.py, source/connection-string/connection-string-spec.rst, source/driver-bulk-update.rst, source/find_getmore_killcursors_commands.rst, source/index.rst, source/max-staleness/max-staleness-tests.rst, source/ocsp-support/ocsp-support.rst, source/polling-srv-records-for-mongos-discovery/polling-srv-records-for-mongos-discovery.rst, source/read-write-concern/read-write-concern.rst, source/retryable-reads/retryable-reads.rst, source/uri-options/uri-options.rst
These changes allow all specification documents to render with Sphinx (Version 4) without generating errors or warnings. There are(should-be) no changes to the actual meaning of any documents. This is only the minimal changes to get Sphinx to generate the pages.
The current tool, `rstcheck`, is set to only report hard-errors, and only looks for semantic issues that Sphinx does not already report as errors/warnings.
=> Warning-free build with Sphinx

source/client-side-encryption/tests/README.rst
Remove string assertion from CSFLE "Custom Endpoint" test case 5.
The current HTTP reply from AWS does not include the invalid region in the error message.
AFAICT, it looks like the error message has changed from AWS. I do not have the full response prior to the change.
But to see the current error response with the AWS CLI, run the following:
```bash
KEK_ID="arn:aws:kms:us-east-1:579766882180:key/89fcc2c4-08b0-4bd9-9f25-e30687b580d0"
DEK="CpLBnghcm8fhhj5fSDOQIOZFLBVSOsTEuYsnrhDc7IoSANLmCWcL+Q7+Ei+QfKLVhItmJSvL3WNHqMTBG/g7FdqqDXUnxxGxk/JC+xD2VNawpBj1erCXcZ2X0G+1dgPy"
aws --profile csfle --debug kms --endpoint-url "https://kms.us-east-2.amazonaws.com:443" --region us-east-1 encrypt --key-id="$KEK_ID" --plaintext="$DEK"
```
Prints `{"__type":"InvalidSignatureException","message":"Credential …
=> DRIVERS-2266 remove string assertion from CSFLE Custom Endpoint test case 5

source/client-side-encryption/etc/test-templates/badQueries.yml.template, source/client-side-encryption/etc/test-templates/types.yml.template, source/client-side-encryption/tests/badQueries.json, source/client-side-encryption/tests/badQueries.yml, source/client-side-encryption/tests/types.json, source/client-side-encryption/tests/types.yml
mongocryptd 6.0 changed the error message.
Here is a [passing test run with the Go driver](https://github.com/mongodb/mongo-go-driver/pull/906).
=> DRIVERS-2272 Fix errorContains in badQueries and types tests

source/change-streams/change-streams.rst, source/change-streams/tests/unified/change-streams-pre_and_post_images.json, source/change-streams/tests/unified/change-streams-pre_and_post_images.yml, source/unified-test-format/tests/Makefile
https://jira.mongodb.org/browse/DRIVERS-1915
POC: https://github.com/mongodb/mongo-php-library/pull/911
Note: testing may require starting mongod with `--setParameter featureFlagChangeStreamPreAndPostImages=true` if the "latest" server build does not include [SERVER-52282](https://jira.mongodb.org/browse/SERVER-52282).
=> DRIVERS-1915: Change stream support for point-in-time pre and post-images

source/client-side-encryption/client-side-encryption.rst
Picking the behavior of _not_ setting csfle search paths when `bypassAutoEncryption` was passed, because:
- Creating a mongocrypt_t instance with an unnecessary csfle library may conflict with the creation of a mongocrypt_t instance that is supposed to use the csfle library but from another path
- It seems like `bypassAutoEncryption` could be implemented by using a `ClientEncryption` instance rather than a separate libmongocrypt handle (on what at least the Python and Node.js bindings call `AutoEncrypter`), in which case the csfle library should probably never be loaded
=> DRIVERS-2287 Clarify interaction of bypassAutoEncryption and csfle search paths

source/change-streams/tests/unified/change-streams-errors.json, source/change-streams/tests/unified/change-streams-errors.yml
DRIVERS-1713
Discovered when updating the Rust tests that the first test in `change-streams-errors.yml` fails with a different error code on server version 3.6 if the database doesn't exist.  Not sure why this didn't show up in previous test runs.
=> DRIVERS-1713 Fix change stream errors test on 3.6

source/crud/tests/unified/bulkWrite-comment.yml, source/crud/tests/unified/deleteMany-comment.yml, source/crud/tests/unified/deleteOne-comment.yml, source/crud/tests/unified/insertMany-comment.yml, source/crud/tests/unified/insertOne-comment.yml, source/crud/tests/unified/replaceOne-comment.yml, source/crud/tests/unified/updateMany-comment.yml, source/crud/tests/unified/updateOne-comment.yml
[DRIVERS-2290](https://jira.mongodb.org/browse/DRIVERS-2290)
Correct ROR YAML object array from two objects to one.  The separation is causes [this failure](https://github.com/mongodb/specifications/runs/6178549023?check_suite_focus=true).
=> DRIVERS-2290 Correct ROR in YML

source/client-side-encryption/tests/fle2-CreateCollection.json, source/client-side-encryption/tests/fle2-CreateCollection.yml
- Replace `commandName` / `databaseName` with `command_name` / `database_name` in the `fle2-CreateCollection` test.
`commandName` and `databaseName` is used in the Unified Test Format [expectedCommandEvent](https://github.com/mongodb/specifications/blob/de75e99fb7e53e3b436c6b69b3deb893e5f6b5d1/source/unified-test-format/unified-test-format.rst#expectedcommandevent)
The Client-Side Encryption specification tests are based on the [Transactions Test Format](https://github.com/mongodb/specifications/tree/de75e99fb7e53e3b436c6b69b3deb893e5f6b5d1/source/transactions/tests#test-format). I did not find a description of the field names for `commandName` / `command_name` or `databaseName` / `database_name`. All of the transaction tests use `command_name` and `database_name`.
---
Please complete the …
=> DRIVERS-2284 fix command_started_event field names

source/crud/crud.rst, source/crud/tests/unified/estimatedDocumentCount.json, source/crud/tests/unified/estimatedDocumentCount.yml, source/versioned-api/tests/crud-api-version-1-strict.json, source/versioned-api/tests/crud-api-version-1-strict.yml, source/versioned-api/tests/crud-api-version-1.json, source/versioned-api/tests/crud-api-version-1.yml
DRIVERS-2228
This is a follow up to the previous PR (#1187) which corrects the server version that the addition of `count` to the stable API was backported to. It also adds a test for `estimatedDocumentCount` on views.
=> DRIVERS-2228 Fix runOnRequirements for `estimatedDocumentCount` stable API tests, add test for views

source/client-side-encryption/tests/fle2-CreateCollection.json, source/client-side-encryption/tests/fle2-CreateCollection.yml
In the “CreateCollection from encryptedFieldsMap”, it makes sense
to also assert on the encryptedFields option that ends up being
passed to the server.
=> DRIVERS-2310 Include encryptFields in expected FLE2 test command

source/unified-test-format/tests/valid-fail/operation-unsupported.json, source/unified-test-format/tests/valid-fail/operation-unsupported.yml
https://jira.mongodb.org/browse/DRIVERS-2313
PHPLIB POC: https://github.com/mongodb/mongo-php-library/pull/923
=> DRIVERS-2313: valid-fail test for unsupported operation

source/change-streams/tests/unified/change-streams.json, source/change-streams/tests/unified/change-streams.yml
[SERVER-65497](https://jira.mongodb.org/browse/SERVER-65497) fixed this test for 6.0 but not yet for 5.3.
We made these changes in https://github.com/mongodb/mongo-python-driver/pull/924 to pass the `rapid` tests.
=> DRIVERS-1995 Skip failing test on Server Version 5.3

source/client-side-encryption/tests/README.rst
5.3.1 does not have all of FLE 2.0 functionality. Per [slack](https://mongodb.slack.com/archives/CFPHLTRMK/p1652192975727899) it may not load correctly on macOS.
=> Use 6.0.0-rc4 in `csfle` download example

source/collection-management/tests/clustered-indexes.json, source/collection-management/tests/clustered-indexes.yml, source/collection-management/tests/createCollection-pre_and_post_images.json, source/collection-management/tests/createCollection-pre_and_post_images.yml, source/collection-management/tests/modifyCollection-pre_and_post_images.json, source/collection-management/tests/modifyCollection-pre_and_post_images.yml
- [n/a] Bump spec version and last modified date.
- [n/a] Update changelog.
Not sure why this wasn't caught in initial testing, but serverless tests are failing in Java driver.
=> Add serverless: forbid for collection management tests

source/client-side-encryption/tests/README.rst
- Insert `key1Document` in the `keyvault.datakeys` collection in the `Explicit Encryption` test setup.
Inserting `key1Document` was [in the Go implementation](https://github.com/kevinAlbs/mongo-go-driver/pull/3/files#diff-55617555c17bae6fadeb3e9a0c0e3a10837496998c75937eba67712b871f58eeR101) but was missed when writing the setup steps.
Majority write concern must be used since the driver uses [majority read concern to find key documents](https://github.com/mongodb/specifications/blob/d1458823bd810014df9da16d3a5354d2269ab865/source/client-side-encryption/client-side-encryption.rst#key-vault-collection). 
=> DRIVERS-2302 add missing test setup step

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/fle2-CreateCollection.json, source/client-side-encryption/tests/fle2-CreateCollection.yml
The FLE 2 secondary collections benefit from being clustered collections
on _id. This reduces the write amplification by 50%.
@kevinAlbs, Unfortunately, I do not know how to write the drivers tests so I need help from someone to update the tests.
=> DRIVERS-2326 Update FLE 2 Collection Management

source/change-streams/change-streams.rst, source/change-streams/tests/unified/change-streams.json, source/change-streams/tests/unified/change-streams.yml
DRIVERS-2285
This adds the `wallTime` field now that it will always be populated in server versions 6.0+.  https://github.com/mongodb/mongo-rust-driver/pull/658 is the (very small) Rust PoC for this change.
=> DRIVERS-2285 Add `wallTime` field to change stream events

source/client-side-encryption/client-side-encryption.rst
The default value is applied in libmongocrypt, not the driver.
=> remove note about contentionFactor default

source/unified-test-format/tests/valid-pass/collectionData-createOptions.json, source/unified-test-format/tests/valid-pass/collectionData-createOptions.yml
- [n/a Bump spec version and last modified date.
- n/a Update changelog.
Forbids `serverless` on the `collectionData` test because it attempts to create a capped collection which are not allowed on serverless topologies.
=> DRIVERS-555 Forbid serverless on collectionData test

source/client-side-encryption/tests/legacy/fle2-CreateCollection.json, source/client-side-encryption/tests/legacy/fle2-CreateCollection.yml
- Add `listCollections` expected event to `fle2-CreateCollection` test for `createIndexes` command.
Tests were run with the [C driver here](https://github.com/mongodb/mongo-c-driver/pull/1009). The tests required the branch of libmongocrypt from https://github.com/mongodb/libmongocrypt/pull/341.
Drivers upgrading libmongocrypt to 1.5.0-alpha2 will need to update the `fle2-CreateCollection` test from this PR. 1.5.0-alpha2 is not yet released. libmongocrypt-1.5.0-alpha2 will contain [MONGOCRYPT-429](https://jira.mongodb.org/browse/MONGOCRYPT-429). I want to merge this before doing the 1.5.0-alpha2 release.
MONGOCRYPT-429 now runs "createIndexes" through query analysis (`mongocryptd` or `csfle` shared library).  The "createIndexes" command sent as part of CreateCollection for FLE 2 will now …
=> DRIVERS-2309 add listCollections events to fle2-CreateCollection

source/client-side-encryption/client-side-encryption.rst
This adds a block of rationale that was missing from https://github.com/mongodb/specifications/pull/1229.
As a drive-by fix, this PR also fixes the section title style that currently breaks HTML formatting on Github.
Because this issue is not being detected by `rstcheck`, I used `rst2html`:
```
rst2html --halt=none client-side-encryption.rst > /dev/null
```
This yielded the following set of warnings:
~~~
client-side-encryption.rst:87: (ERROR/3) Unknown interpreted text role "ref".
client-side-encryption.rst:245: (ERROR/3) Unknown interpreted text role "ref".
client-side-encryption.rst:642: (ERROR/3) Unknown interpreted text role "ref".
client-side-encryption.rst:644: (ERROR/3) Unknown interpreted text role "ref".
client-side-encryption.rst:669: (SEVERE/4) Title level inconsistent:
Create …
=> Add missing rationale for key management API and fix RST syntax

source/client-side-encryption/etc/test-templates/create-and-createIndexes.yml.template, source/client-side-encryption/etc/test-templates/fle2-validatorAndPartialFieldExpression.yml.template, source/client-side-encryption/etc/test-templates/validatorAndPartialFieldExpression.yml.template, source/client-side-encryption/tests/legacy/create-and-createIndexes.json, source/client-side-encryption/tests/legacy/create-and-createIndexes.yml, source/client-side-encryption/tests/legacy/fle2-validatorAndPartialFieldExpression.json, source/client-side-encryption/tests/legacy/fle2-validatorAndPartialFieldExpression.yml, source/client-side-encryption/tests/legacy/validatorAndPartialFieldExpression.json, source/client-side-encryption/tests/legacy/validatorAndPartialFieldExpression.yml
This contains integration tests for behavior added in [MONGOCRYPT-429](https://jira.mongodb.org/browse/MONGOCRYPT-429). libmongocrypt 1.5.0-alpha2 is required to run these tests expected. There are no driver changes required.
- Test that `create` and `collMod` with a `validator` for encrypted fields are an error.
- Test that `createIndexes` with a `partialFieldExpression` for encrypted fields is an error.
- Test that `create` and `createIndexes` continues to work.
Tests were run with the [Go driver here](https://github.com/kevinAlbs/mongo-go-driver/pull/6) and the [C driver here](https://github.com/mongodb/mongo-c-driver/pull/1005).
Tests are expected fail on `mongocryptd` or `csfle` versions >= 6.0.0-rc0 and <= 6.0.0-rc4. The versions do not include …
=> DRIVERS-2309 test `create`, `createIndexes`, and `collMod` in FLE

source/client-side-encryption/etc/test-templates/fle2-Compact.yml.template, source/client-side-encryption/tests/legacy/fle2-Compact.json, source/client-side-encryption/tests/legacy/fle2-Compact.yml
- Use "topology", not "topologies" in fle2-Compact test.
"topologies" is used in the [Unified Test Format](https://github.com/mongodb/specifications/blob/7f37c9325b423223edf54d795afed444e6989b98/source/unified-test-format/unified-test-format.rst#runonrequirement). "topology" is consistent with the [legacy transaction test format](https://github.com/mongodb/specifications/tree/7f37c9325b423223edf54d795afed444e6989b98/source/transactions/tests#test-format). The CSFLE legacy specification tests are based off of the legacy transactions test format.
=> DRIVERS-2307 use topology, not topologies

source/client-side-encryption/etc/test-templates/fle2-Delete.yml.template, source/client-side-encryption/etc/test-templates/fle2-EncryptedFields-vs-jsonSchema.yml.template, source/client-side-encryption/etc/test-templates/fle2-FindOneAndUpdate.yml.template, source/client-side-encryption/etc/test-templates/fle2-InsertFind-Indexed.yml.template, source/client-side-encryption/etc/test-templates/fle2-Update.yml.template, source/client-side-encryption/tests/legacy/fle2-Delete.json, source/client-side-encryption/tests/legacy/fle2-Delete.yml, source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.json, source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.yml, source/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.json, source/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.yml, source/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.json, source/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.yml, source/client-side-encryption/tests/legacy/fle2-Update.json, source/client-side-encryption/tests/legacy/fle2-Update.yml
- Update expected find payload in FLE 2 tests to account for MONGOCRYPT-433.
These tests require libmongocrypt 1.5.0-rc0 (not yet released) and 6.0.0-rc8 or later (not yet released). But tests can be validated by using libmongocrypt builds attached to the MONGOCRYPT-433 pull request [here](https://spruce.mongodb.com/version/6294f25561837d6698d1f6a1/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=upload-all) and the latest server builds.
=> DRIVERS-2343 Update expected FLE 2 find payloads

source/command-monitoring/tests/unified/find.json, source/command-monitoring/tests/unified/find.yml
Java driver is failing the `A successful find with options` test because it only include showRecordId and returnKey in the command if the value is true (the booleans are not nullable).  I switched up the tests a bit so that Java (and perhaps other drivers) will pass them.
DRIVERS-1096
- [ n/a] Bump spec version and last modified date.
- [ n/a] Update changelog.
- [ x] Make sure there are generated JSON files from the YAML test files.
- [ x] Test changes in at least one language driver.
=> DRIVERS-1096: Split showRecordId/returnKey into separate test

source/client-side-encryption/tests/README.rst
- Test CommandSucceeded and CommandFailed events emitted for automatic decryption.
Please see DRIVERS-2350 for motivation of these tests.
=> DRIVERS-2350 add Decryption Events prose tests

source/client-side-encryption/client-side-encryption.rst
Unlike [ClientEncryption.createKey()](https://github.com/mongodb/specifications/blob/f9cbedafe53faffd62f15bcb2e952d1e016934e9/source/client-side-encryption/tests/unified/createKey.yml#L61) and [ClientEncryption.rewrapManyDataKey()](https://github.com/mongodb/specifications/blob/f9cbedafe53faffd62f15bcb2e952d1e016934e9/source/client-side-encryption/tests/unified/rewrapManyDataKey.yml#L148), the unified spec tests for [ClientEncryption.addKeyAltName()](https://github.com/mongodb/specifications/blob/f9cbedafe53faffd62f15bcb2e952d1e016934e9/source/client-side-encryption/tests/unified/addKeyAltName.yml#L55) and [ClientEncryption.removeKeyAltName()](https://github.com/mongodb/specifications/blob/f9cbedafe53faffd62f15bcb2e952d1e016934e9/source/client- …
=> Clarify description of date fields of key documents

source/client-side-encryption/client-side-encryption.rst
The reference to the UUID spec was broken due to a missing trailing `_`.
=> Fix reference to UUID spec in CSE spec

source/unified-test-format/unified-test-format.rst
- Require server 4.2+ for the `csfle: true` `runOnRequirement`.
DRIVERS-2356 changed the implementation of removeKeyAltName to use one findOneAndUpdate operation with an aggregation pipeline. Using an aggregation pipeline for an update was added in MongoDB server 4.2: https://www.mongodb.com/docs/manual/tutorial/update-documents-with-aggregation-pipeline/.
A rejected alternative is to add `minServerVersion: "4.2.0"` to the runOnRequirement in removeKeyAltName.yml.
Client-Side Encryption requires a minimum server support of 4.2 for schema support. [The rationale](https://github.com/mongodb/specifications/blob/7f2ec854d730097494d23cfaf62abc5a0aea4570/source/client-side-encryption/client-side-encryption.rst#why-is-a-4-2-server-required) notes:
> Limiting to 4.2 reduces testing complexity …
=> DRIVERS-2359 Require server 4.2+ for `csfle: true`

source/sessions/tests/driver-sessions-dirty-session-errors.json, source/sessions/tests/driver-sessions-dirty-session-errors.yml
https://jira.mongodb.org/browse/DRIVERS-2279
Noticed while working on https://jira.mongodb.org/browse/PYTHON-3160.
=> DRIVERS-2279 Don't use explicit session in dirty implicit session test

source/client-side-encryption/tests/README.rst
This is a follow-up to prose test 14 added in DRIVERS-2350.
- Clarify that an empty pipeline is used in case 3 and case 4.
- Format `CommandStartedEvent`, `CommandFailedEvent`, and `CommandSucceededEvent`.
- Replace incorrect reference to `CommandStartedEvent` with `CommandSucceededEvent`.
=> DRIVERS-2350 clarify prose test 14

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst
- Change `EncryptOpts.QueryType` from an enum to a string.
String values helps with forward compatibility When new values of QueryType and IndexType are added in libmongocrypt, users would only need to upgrade libmongocrypt, and not the driver, to use the new values. See [DRIVERS-2352](https://jira.mongodb.org/browse/DRIVERS-2352) for the motivation.
=> DRIVERS-2352 use a string for QueryType

source/client-side-encryption/tests/README.rst
Change the last byte value. The last byte may have started as 0.
=> DRIVERS-2350 fix setup for Decryption Events tests

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/unified/rewrapManyDataKey.json, source/client-side-encryption/tests/unified/rewrapManyDataKey.yml
This PR resolves DRIVERS-2367.
=> DRIVERS-2367 Allow RewrapManyDataKeyResult.bulkWriteResult to be optional

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst, source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.json, source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml, source/client-side-encryption/tests/unified/createDataKey.json, source/client-side-encryption/tests/unified/createDataKey.yml, source/client-side-encryption/tests/unified/getKeys.json, source/client-side-encryption/tests/unified/getKeys.yml
This PR addresses DRIVERS-2370. All instances of `createKey()` have either been removed or renamed to `createDataKey()`.
Upon reconsideration, it was decided that the engineering effort, subsequent maintenance, and clarity of usage and documentation of adding to all Drivers a new `createKey()` function that is merely an alias to the existing `createDataKey()` function may not be desirable. It was deemed preferable for mongosh, whose interface the Key Management API is aiming to reach parity with, to add `createDataKey()` for parity instead.
Other factors considered was leaving room for further key types to be managed in the key vault collection. Instead of reserving the generic `createKey` for "data keys", `createDataKey()` leaves room for …
=> DRIVERS-2370 Remove createKey in favor of createDataKey

source/client-side-encryption/tests/README.rst
- Update "explicit encryption" prose tests to include required contentionFactor option
[MONGOCRYPT-447](https://jira.mongodb.org/browse/MONGOCRYPT-447) makes contentionFactor a required option when the algorithm is "Indexed".
Drivers require libmongocrypt with MONGOCRYPT-477 to run these tests. MONGOCRYPT-477 is planned in the 1.5.0 stable release. 1.5.0 is not yet released, but libmongocrypt can be downloaded from this [upload-all task](https://evergreen.mongodb.com/task/libmongocrypt_publish_snapshot_upload_all_b1d9dd9811d8c15dc294ab3d5dcb71364833f28d_22_06_27_20_02_56).
=> DRIVERS-2371 add required contention factor to prose tests

source/client-side-encryption/tests/unified/addKeyAltName.json, source/client-side-encryption/tests/unified/addKeyAltName.yml, source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.json, source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml, source/client-side-encryption/tests/unified/deleteKey.json, source/client-side-encryption/tests/unified/deleteKey.yml, source/client-side-encryption/tests/unified/getKey.json, source/client-side-encryption/tests/unified/getKey.yml, source/client-side-encryption/tests/unified/getKeyByAltName.json, source/client-side-encryption/tests/unified/getKeyByAltName.yml, source/client-side-encryption/tests/unified/removeKeyAltName.json, source/client-side-encryption/tests/unified/removeKeyAltName.yml, source/unified-test-format/tests/valid-pass/kmsProviders-unconfigured_kms.json, source/unified-test-format/tests/valid-pass/kmsProviders-unconfigured_kms.yml
This PR resolves DRIVERS-2373.
=> DRIVERS-2373 remove unnecessary use of on-demand credentials in CSE unified spec tests

source/client-side-encryption/client-side-encryption.rst
This PR resolves DRIVERS-2376.
An attempt to phrase the description explicitly in terms of `bulkWrite()` and `updateOne()` was attempted, but felt too clunky. If such a wording is preferable, suggestions are welcome.
=> DRIVERS-2376 Clarify bulk write operation expectations for rewrapManyDataKey

source/client-side-operations-timeout/etc/templates/global-timeoutMS.yml.template, source/client-side-operations-timeout/etc/templates/retryability-timeoutMS.yml.template, source/client-side-operations-timeout/tests/README.rst, source/client-side-operations-timeout/tests/bulkWrite.json, source/client-side-operations-timeout/tests/bulkWrite.yml, source/client-side-operations-timeout/tests/command-execution.json, source/client-side-operations-timeout/tests/command-execution.yml, source/client-side-operations-timeout/tests/error-transformations.json, source/client-side-operations-timeout/tests/error-transformations.yml, source/client-side-operations-timeout/tests/global-timeoutMS.json, source/client-side-operations-timeout/tests/global-timeoutMS.yml, source/client-side-operations-timeout/tests/retryability-timeoutMS.json, source/client-side-operations-timeout/tests/retryability-timeoutMS.yml
This change makes the tests more reliable in Python and Go.
Tested in python here: https://github.com/mongodb/mongo-python-driver/pull/954
=> DRIVERS-555 Increase CSOT test timeouts

source/unified-test-format/tests/valid-pass/collectionData-createOptions.json, source/unified-test-format/tests/valid-pass/collectionData-createOptions.yml
Explanation:
> If the size field is less than or equal to 4096, then the collection will have a cap of 4096 bytes.
https://www.mongodb.com/docs/manual/core/capped-collections/#create-a-capped-collection
Testing this change in Python here: https://github.com/mongodb/mongo-python-driver/pull/990
=> DRIVERS-555 Fix capped collection test on MMAPv1

source/client-side-encryption/tests/README.rst
- Clarify that driver tests < 6.0 should use mongocryptd
The goal of DRIVERS-2355 is to use a consistent version for crypt_shared and the server. Meeting that goal prohibits testing with crypt_shared on < 6.0 servers.
=> DRIVERS-2355 Clarify that driver tests < 6.0 should use mongocryptd

source/change-streams/tests/unified/change-streams-resume-errorLabels.json, source/change-streams/tests/unified/change-streams-resume-errorLabels.yml
DRIVERS-2387
Skips the `change stream resumes after StaleShardVersion` test on > 6.0.99. `StaleShardVersion` was removed (see [SERVER-64449](https://jira.mongodb.org/browse/SERVER-64449)) in 6.1.0 and is therefore not marked resumable by the server. `StaleShardVersion` was obsoleted by `StaleConfig`, but adding tests for the resumability of that error is non-trivial (see DRIVERS-2392), so I think we can just skip the `StaleShardVersion` test on 6.1.0+ for now.
=> DRIVERS-2387 Skip StaleShardVersion resume test on >= 6.1

source/transactions/tests/unified/do-not-retry-read-in-transaction.json, source/transactions/tests/unified/do-not-retry-read-in-transaction.yml
- [N/A] Bump spec version and last modified date.
- [N/A] Update changelog.
- [Done] Make sure there are generated JSON files from the YAML test files.
- [Done] Test changes in at least one language driver.
- [Done] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
Though the requirement is in the retryable reads spec, the test seemed more appropriate in the transactions spec.  Happy to move if there is strong disagreement.
DRIVERS-2395
=> DRIVERS-2395: Add test that read is not retried in a transaction

source/server_write_commands.rst
See DRIVERS-2390 for details. This value changed from 1000 to 100,000 in in 3.6. Since it could change again in the future and the spec states that the value can be found be `hello` it does not seem necessary to include the specific value here.
=> DRIVERS-2390 remove specific value for maxWriteBatchSize from write commands spec

source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.json, source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml, source/client-side-encryption/tests/unified/rewrapManyDataKey.json, source/client-side-encryption/tests/unified/rewrapManyDataKey.yml
Resolves DRIVERS-2404.
As a drive-by fix, also updates the descriptions of some CSE tests to be consistent with their filenames.
=> DRIVERS-2404 Fix Azure and KMIP key material for RewrapManyDataKey

source/client-side-encryption/tests/README.rst
- Add a prose test to test RewrapManyDataKey.
This is an integration regression test for MONGOCRYPT-464.
=> DRIVERS-2406 add Rewrap prose test

source/client-side-encryption/etc/test-templates/fle2-InsertFind-Unindexed.yml.template, source/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.json, source/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.yml
- Update expected error in fle2-InsertFind-Unindexed.
The expected error message changed recently in https://github.com/10gen/mongo-enterprise-modules/commit/212b584d4f7a44bed41c826a180a4aff00923d7a#diff-5f12b55e8d5c52c2f62853ec595dc2c1e2e5cb4fdbf7a32739a8e3acb3c6f818 Driver tests against "latest" will start failing.
Before the message was "cannot query non-indexed fields with the randomized encryption algorithm". Now it is "can only execute encrypted equality queries with an encrypted equality index". 
=> DRIVERS-2407 update expected error in fle2-InsertFind-Unindexed

source/gridfs/gridfs-spec.rst
The cursor timeout value is now configurable on a per server basis: https://jira.mongodb.org/browse/SERVER-8188. Additionally, the spec did not mark the `skip` option in `GridFSFindOptions` as `optional`.
=> Remove 10 minute cursorTimeout comment from GridFSFindOptions docs

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst
- Support GCP attached service accounts when using GCP KMS.
See [DBX Scope: Support attached service accounts for GCP KMS](https://docs.google.com/document/d/1RTDp5QMg_ayYnR_T7S9SriE19doNALwqIHNxlWerFeE/edit?usp=sharing).
This follows a similar pattern as the "aws" credentials for CSFLE added in DRIVERS-2280.
Support of the ``GCE_METADATA_HOST`` environment variable is not mentioned in https://google.aip.dev/auth/4115. It is implemented in the GCP SDKs I checked: (e.g. [Go](https://pkg.go.dev/cloud.google.com/go/compute/metadata#Client.Get) and [Python](https://github.com/googleapis/google-auth-library-python/blob/6f49d1fa1dff62c5f2ed0cf198507568f5c4296f/google/auth/compute_engine/_metadata.py#L35-L39)). I found it useful for development to test with a mock server. It may be useful for …
=> DRIVERS-2377 Support GCP attached service accounts when using GCP KMS

source/change-streams/change-streams.rst, source/change-streams/tests/unified/change-streams-disambiguatedPaths.json, source/change-streams/tests/unified/change-streams-disambiguatedPaths.yml
https://jira.mongodb.org/browse/DRIVERS-2344
POC PR in Node: https://github.com/mongodb/node-mongodb-native/pull/3365
A new field, `disambiguatedPaths` has been added to change stream update documents for servers >=6.1 where `showExpandedEvents` is enabled.
This feature is only supported in server 6.1 and above, so testing these changes will require running against the latest server build.
---
=> DRIVERS-2344: add disambiguatedPaths to change streams update document

source/server-discovery-and-monitoring/tests/unified/rediscover-quickly-after-step-down.json, source/server-discovery-and-monitoring/tests/unified/rediscover-quickly-after-step-down.yml, source/unified-test-format/unified-test-format.rst
This PR fixes the capitalization of a ReadPreference mode in one of the SDAM unified tests. It currently reads `Secondary`, which is consistent with existing server selection and max-staleness tests but inconsistent with existing unified format tests ([this CRUD unified test](https://github.com/mongodb/specifications/blob/master/source/crud/tests/unified/db-aggregate-write-readPreference.yml#L36) uses `secondaryPreferred`, for example).
This PR also updates the unified test format changelog to mention the addition of the `createEntities` operation.
Thanks to @dariakp for noticing these issues.
@ShaneHarvey @jyemin would you prefer if there was a separate DRIVERS ticket for this since you both already implemented the original change? Or do you just want to sync this in real quick as a …
=> DRIVERS-2366 Use camelCase for ReadPreference mode in unified tests

source/change-streams/tests/unified/change-streams-showExpandedEvents.json, source/change-streams/tests/unified/change-streams-showExpandedEvents.yml
The test in question sometimes fails for the PHP driver, due to the `create` event being emitted in the change stream. Since the test only checks the first event, we have to exclude the `create` event to ensure we only receive the `createIndexes` event we're looking for. This fixes the issue for PHP and shouldn't introduce problems for other drivers.
Note: after discussion with @jmikola we decided to only exclude the problematic `create` event from the change stream. This was done so that any other additional commands sent to the server before the `createIndex` call would cause the test to fail. This may be very unlikely to happen, but we figured it was more sensible than only including `createIndexes` in the change stream.
=> DRIVERS-2417: Exclude create events from change stream when testing showExpandedEvents

source/client-side-encryption/client-side-encryption.rst
- Remove requirement to check `GCE_METADATA_HOST`.
The check for `GCE_METADATA_HOST` was added in https://github.com/mongodb/specifications/commit/847d9ba741201f9c9d1305831a9c60e8ab2a1544 with the motivation:
> I found it useful for development to test with a mock server. It may be useful for diagnosing bugs in the future.
It defies the YAGNI principal. There are no specification tests for the `GCE_METADATA_HOST` environment variable check.
---
=> DRIVERS-2377 remove GCE_METADATA_HOST check

source/command-monitoring/command-monitoring.rst
I'm going to be making somewhat significant additions to this spec around command logging. A lot of the information in here is currently for outdated server versions that most drivers do not support and soon no drivers will support. Rather than trying to preserve it as I incorporate new information, I propose we remove it altogether. 
Rather than bumping the spec version and last modified date, I also took the liberty of removing the spec version and front matter as @jmikola will do in DRIVERS-2253 will do for all specs.
=> Remove MongoDB < 3.6 information and front matter from command monitoring spec

source/retryable-writes/tests/README.rst
There is doubt as to whether we should limit this prose test to 4.4+ or 6.1+. This test will work on versions 4.4+, but it doesn't become relevant until 6.1+. For now, I have left it as 4.4+, but I am open to changing it. See the discussion [here](https://jira.mongodb.org/browse/DRIVERS-2327?focusedCommentId=4815873&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4815873).
EDIT: Consensus seems to be that this change will be backported to 6.0, so I will leave this test as 6.0+.
=> DRIVERS-2327: limit prose test to server versions 6.0+

source/crud/tests/unified/distinct-comment.json, source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.yml
Fixes this error:
```
diff --git a/source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.json b/source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.json
index 6a7ca02..704a232 100644
--- a/source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.json
+++ b/source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.json
@@ -102,7 +102,7 @@
"a:27017",
{
"ok": 1,
-            "helloOk": true,
+            "hello": true,
"isWritablePrimary": true,
"hosts": [
"a:27017",
```
I also regenerated all the JSON files and the only other change was some formatting in `crud/tests/unified/distinct-comment.json`.
=> DRIVERS-1954 Fix hello->helloOk typo + regenerate all json tests

source/enumerate-collections.rst, source/enumerate-databases.rst, source/enumerate-indexes.rst
This PR clarifies the intended behavior for the following commands on pre-4.4 servers when comment is attached.
- listIndexes
- listCollections
- listDatabases
=> DRIVERS-2402: Clarify the behavior of comments on pre-4.4 servers

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst, source/unified-test-format/unified-test-format.rst
=> [DRIVERS-2411] Add behavior for automatic Azure KMS credentials

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/tests/README.rst, source/server-discovery-and-monitoring/tests/rs/electionId_precedence_setVersion.json, source/server-discovery-and-monitoring/tests/rs/electionId_precedence_setVersion.yml, source/server-discovery-and-monitoring/tests/rs/null_election_id-pre-6.0.json, source/server-discovery-and-monitoring/tests/rs/null_election_id-pre-6.0.yml, source/server-discovery-and-monitoring/tests/rs/null_election_id.json, source/server-discovery-and-monitoring/tests/rs/secondary_ignore_ok_0-pre-6.0.json, source/server-discovery-and-monitoring/tests/rs/secondary_ignore_ok_0-pre-6.0.yml, source/server-discovery-and-monitoring/tests/rs/set_version_can_rollback.yml, source/server-discovery-and-monitoring/tests/rs/setversion_equal_max_without_electionid.json, source/server-discovery-and-monitoring/tests/rs/setversion_equal_max_without_electionid.yml, source/server-discovery-and-monitoring/tests/rs/setversion_greaterthan_max_without_electionid.json, source/server-discovery-and-monitoring/tests/rs/setversion_without_electionid-pre-6.0.json, source/server-discovery-and-monitoring/tests/rs/setversion_without_electionid-pre-6.0.yml, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid-pre-6.0.json, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid-pre-6.0.yml, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid.json, source/server-discovery-and-monitoring/tests/rs/use_setversion_without_electionid.yml
Maintain `updateRSFromPrimary` behavior on pre 6.0 servers for electionId/setVersion checking. And include tests from before the change.
- (N/A unit tests) ~Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~
=> DRIVERS-2412: add pre 6.0 condition to stale primary logic

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
Fixed our code formatting to get some highlighting and the SDAM subroutines are now entries in the table contents under `Actions`.
None of the usual checklist applies since this does not have functional changes.
=> fix SDAM code formatting to get syntax highlighting

source/connection-monitoring-and-pooling/tests/pool-clear-interrupt-immediately.json
For some reason the GitHub action that checks the JSON tests have been regenerated started complaining about this on #1303.
=> minor: remove extra whitespace from CMAP test

source/client-side-operations-timeout/tests/README.rst
Numbers the CSOT prose tests for organization within drivers. Bumps the timeout of the `Multi-batch writes` test, restricts it to single topologies and uses 50 1MB docs instead of 100001 docs.
=> DRIVERS-555 Number CSOT prose tests and bump some timeouts.

source/collection-management/tests/modifyCollection-errorResponse.json, source/collection-management/tests/modifyCollection-errorResponse.yml, source/crud/tests/unified/aggregate-merge-errorResponse.json, source/crud/tests/unified/aggregate-merge-errorResponse.yml, source/crud/tests/unified/bulkWrite-errorResponse.json, source/crud/tests/unified/bulkWrite-errorResponse.yml, source/crud/tests/unified/deleteOne-errorResponse.json, source/crud/tests/unified/deleteOne-errorResponse.yml, source/crud/tests/unified/findOneAndUpdate-errorResponse.json, source/crud/tests/unified/findOneAndUpdate-errorResponse.yml, source/crud/tests/unified/insertOne-errorResponse.json, source/crud/tests/unified/insertOne-errorResponse.yml, source/crud/tests/unified/updateOne-errorResponse.json, source/crud/tests/unified/updateOne-errorResponse.yml, source/unified-test-format/schema-1.12.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/invalid/expectedError-errorResponse-type.json, source/unified-test-format/tests/invalid/expectedError-errorResponse-type.yml, source/unified-test-format/tests/valid-pass/expectedError-errorResponse.json, source/unified-test-format/tests/valid-pass/expectedError-errorResponse.yml, source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-2385
Prototype: https://github.com/mongodb/mongo-php-library/pull/989
----
=> DRIVERS-2385: expectedError.errorResponse for asserting server-side error doc

source/auth/auth.rst, source/auth/tests/mongodb-aws.rst
- https://github.com/mongodb/pymongo-auth-aws/pull/10
- https://github.com/mongodb/mongo-python-driver/pull/982
=> DRIVERS-2333 Cache AWS Credentials Where Possible

source/change-streams/change-streams.rst
Reformats the change stream spec Changelog to be the same format as other Changelogs reformatted in DRIVERS-2253.
=> DRIVERS-2461: Reformat change stream spec Changelog.

source/connection-monitoring-and-pooling/tests/pool-clear-schedule-run-interruptInUseConnections-false.json, source/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.json
I am not sure why, but when I regenerated files after making some changes in #1324 these ones changed. Seems like they had not been properly regenerated for whatever reason and the GitHub Action checking the files did not pick it up.
=> minor: regenerate JSON files

source/client-side-encryption/client-side-encryption.rst
- Permit a global cache for Azure credentials
Python has implemented a global cache for Azure credentials: https://github.com/mongodb/libmongocrypt/pull/484
=> DRIVERS-2411 permit global cache

source/causal-consistency/causal-consistency.rst, source/sessions/tests/implicit-sessions-default-causal-consistency.json, source/sessions/tests/implicit-sessions-default-causal-consistency.yml
=> DRIVERS-2369 Default causal consistency should be false in implicit sessions

source/retryable-reads/tests/etc/templates/handshakeError.yml.template, source/retryable-reads/tests/unified/handshakeError.json, source/retryable-reads/tests/unified/handshakeError.yml, source/retryable-writes/tests/etc/templates/handshakeError.yml.template, source/retryable-writes/tests/unified/handshakeError.json, source/retryable-writes/tests/unified/handshakeError.yml
This PR fixes an issue with the tests added in https://github.com/mongodb/specifications/pull/1336
Change streams don't yet work on serverless so we have to skip createChangeStream tests there.
=> DRIVERS-2489 Properly skip createChangeStream tests on serverless

source/client-side-encryption/tests/README.rst
This builds upon #1322 to add more basic test cases for CreateEncryptedCollection.
=> Define additional error-checking cases for CreateEncryptedCollection

source/command-logging-and-monitoring/command-logging-and-monitoring.rst, source/command-logging-and-monitoring/tests/logging/redacted-commands.json, source/command-logging-and-monitoring/tests/logging/redacted-commands.yml, source/command-logging-and-monitoring/tests/monitoring/redacted-commands.json, source/command-logging-and-monitoring/tests/monitoring/redacted-commands.yml, source/unified-test-format/tests/valid-pass/observeSensitiveCommands.json, source/unified-test-format/tests/valid-pass/observeSensitiveCommands.yml, source/unified-test-format/unified-test-format.rst
* The `getnonce` command is being removed in 6.2. This updates various driver tests which used getnonce to only run on lower server versions.
* While looking into this, I noticed that a lot of the other redaction tests used commands which have also been removed in recent server versions. These passed on newer server versions because they expected errors, so the server returned an error regardless: on newer versions, it would just be an error about the command not existing. This coverage didn't seem particularly valuable, and it seemed worthwhile to have each test annotated with the correct maxServerVersion so that as those versions get dropped from drivers we know when the tests can be removed. 
Tests pass in Rust, and since all this changes here is skipping tests in more places I …
=> DRIVERS-2490 Only run tests using getnonce on servers < 6.2; correct maxServerVersion for command/reply redaction tests

source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/unified/insertOne-noWritesPerformedError.json, source/retryable-writes/tests/unified/insertOne-noWritesPerformedError.yml
=> DRIVERS-2501 Break NoWritesPerformed-Only Error Sequence

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst
- Permit `tlsDisableOCSPEndpointCheck` in KMS TLS options.
There is a report of [timeouts to OCSP responders during KMS](https://jira.mongodb.org/browse/HELP-39172?focusedCommentId=4989713&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4989713). That results in operation failures using CSFLE. 
The rationale to prohibit the option is to avoid enabling insecure settings when using CSFLE. Product is OK with allowing `tlsDisableOCSPEndpointCheck` to be opt-in (see [comment](https://jira.mongodb.org/browse/DRIVERS-2507?focusedCommentId=5001801&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-5001801)).
Tested in C: https://github.com/mongodb/mongo-c-driver/pull/1153
=> DRIVERS-2507 Permit `tlsDisableOCSPEndpointCheck` in KMS TLS options

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst
- Rename references of `cryptSharedRequired` to `cryptSharedLibRequired`
The specification is inconsistent about the option name.
Surveying driver implementations, all use a form of `cryptSharedLibRequired` except for the Ruby driver as part of [RUBY-3184](https://jira.mongodb.org/browse/RUBY-3184) which appears unreleased. See [Do drivers use cryptSharedRequired or cryptSharedLibRequired?](https://docs.google.com/spreadsheets/d/1WD6NllbyfEF6Bynnl88LQkCyqXze9btNk9Nz6OotBTo/edit#gid=0).
Including `Lib` is consistent with the other option `cryptSharedLibPath`.
=> DRIVERS-2338 fix option typos

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/etc/data/range-encryptedFields-Date.json, source/client-side-encryption/etc/data/range-encryptedFields-DoubleNoPrecision.json, source/client-side-encryption/etc/data/range-encryptedFields-DoublePrecision.json, source/client-side-encryption/etc/data/range-encryptedFields-Int.json, source/client-side-encryption/etc/data/range-encryptedFields-Long.json, source/client-side-encryption/tests/README.rst
- Add `"rangePreview"` to `queryType`
- Add `"RangePreview"` to `EncrypOpts.algorithm`
- Add `rangeOpts` struct in `EncryptOpts`
- Add `ClientEncryption.encryptExpression()`
- Add prose tests for explicit encryption with range index.
Tests require [libmongocrypt 1.7.0-alpha1](https://github.com/mongodb/libmongocrypt/releases/tag/1.7.0-alpha1) release. Binaries for the release are available on this [upload-all task](https://spruce.mongodb.com/task/libmongocrypt_publish_snapshot_upload_all_2cd2f77ae806a3a4c12750b39b0be92b0ca3b2c1_22_12_08_13_33_51/files?execution=0).
Tests have been run with the Go driver here: https://github.com/mongodb/mongo-go-driver/pull/1145
After Decimal128 support is released in [MONGOCRYPT-483](https://jira.mongodb.org/browse/MONGOCRYPT-483), test cases will be …
=> DRIVERS-2505 Add explicit encryption API and tests for range indexes

source/client-side-encryption/tests/README.rst
- Require drivers test the latest Major release of `crypt_shared` with older server versions.
Testing `crypt_shared` with older server versions is a product ask. See DRIVERS-2465.
This change depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/247.
- ~[ ] Update changelog.~ **Not applicable. Test README changes only.**
- ~[ ] Make sure there are generated JSON files from the YAML test files.~ **Not applicable. Test README changes only.**
=> DRIVERS-2465 Test crypt_shared with older server versions

source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
> RSGhosts may report their setNames in the future (see SERVER-13458). 
Remove the above reference as SERVER-13458 was closed in 2014 as _Works as Designed_. This shouldn't require a changelog update.
=> Update SDAM Spec to remove "RSGhosts may report their setNames in the future"

source/client-side-encryption/tests/README.rst
`encryptedFields` requires MongoDB 6.0+ and is not supported on standalone. The message is consistent with `12. Explicit Encryption`
- ~~[ ] Update changelog.~~ **Not applicable.**
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ **Not applicable**
- ~~[ ] Test changes in at least one language driver.~~ **Not applicable**
- ~~[ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~ **Not applicable**
=> DRIVERS-2313 note prose test server requirement

source/client-side-encryption/tests/unified/rewrapManyDataKey.json, source/client-side-encryption/tests/unified/rewrapManyDataKey.yml
The `BulkWriteResult` can contain an optional `insertedIds` property so we check for it not being present or empty.
Tests running in the Node driver suite from PR: https://github.com/mongodb/node-mongodb-native/pull/3516
=> test(DRIVERS-2523): allow optional bulk write result inserted ids

source/command-logging-and-monitoring/tests/logging/unacknowledged-write.json, source/command-logging-and-monitoring/tests/logging/unacknowledged-write.yml
Adds a command logging test covering unacknowledged write behavior. Drivers are supposed to emit a "command succeeded" message with a reply of ok: 1 for unacknowledged writes but we were missing test coverage.
Rust doesn't have unacknowledged writes but @jyemin has confirmed this test passes for the Java driver.
=> DRIVERS-2525 Add a command logging test covering unacknowledged write behavior

source/client-side-encryption/tests/README.rst
- Skip `fle2-Range-<type>-Correctness` tests on macOS
Change applied in the Go driver [here](https://github.com/mongodb/mongo-go-driver/pull/1164).
The `fle-Range-*` tests are especially slow on macOS. Running the `fle-Range-*` tests on a 3-node replica on macOS with the Go driver takes 11 minutes. The same tests on Ubuntu 18.04 take 2 minutes. After skipping `fle2-Range-<type>-Correctness` tests, the `fle-Range-*` tests on macOS take 2 minutes.
It may be sufficient test coverage to test `fle2-Range-<type>-Correctness` on Linux and Windows.
The `fle2-Range-<type>-<operation>` tests will still run on macOS and provide some test coverage for Range Index on macOS.
Removing the `fle2-Range-<type>-Correctness` tests entirely was considered and rejected. The `fle2-Range-<type>-Correctness` …
=> DRIVERS-2286 allow skipping some fle2-Range on mac

source/client-side-encryption/client-side-encryption.rst
- clarify encryptedFields is returned on CreateCollection error.
~~- [ ] Make sure there are generated JSON files from the YAML test files.~~
~~- [ ] Test changes in at least one language driver.~~
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~
=> DRIVERS-2312 clarify encryptedFields is returned on CreateCollection error

source/client-side-encryption/client-side-encryption.rst
Given that:
- createEncryptedCollection does not mutate the auto encryption options on the MongoClient if it finds them there
- libmongocrypt throws if the encryptedFieldsMap is incomplete
The following code always throws:
```typescript
const client = new MongoClient(uri, { encryptedFieldsMap })
const ce = new ClientEncryption(...);
await cd.createEncryptedCollection(client.db('foo'), <options>))
// assume createEncryptedCollection succeeds
await client.connect(); // libmongocrypt throws because `encryptedFieldsMap` is not complete, even though the collection has been created
```
This PR updates the helper to never look for the `encryptedFieldsMap` on AutoEncryptionOptions and ensures that drivers document this potentially confusing behavior.
Additional context available in slack …
=> DRIVERS-2312: do not consider AutoEncryptionOptions in createEncryptedCollection

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/tests/README.rst
- Replace `DataKeyOpts` with `masterKey` in `CreateEncryptedCollection`
- Run test cases for `CreateEncryptedCollection` with `aws` KMS provider.
Updated API is implemented and tested in [the Go driver here](https://github.com/mongodb/mongo-go-driver/pull/1169).
Running test cases with the ``aws`` KMS provider is intended to provide test coverage for handling ``masterKey`` option. The ``local`` KMS provider not requiring a ``masterKey`` option.
The motivation for removing `keyAltNames` from `CreateEncryptedCollection` is noted in DRIVERS-2539:
> The problem is that if keyAltNames is given and createEncryptedCollection creates >1 key, then the method will always fail because of a duplicate key error.
> MONGOCRYPT-432 would allow createEncryptedCollection to create keys with different …
=> DRIVERS-2539 Replace `DataKeyOpts` with `masterKey` in `CreateEncryptedCollection`

source/connection-monitoring-and-pooling/tests/logging/connection-logging.json, source/connection-monitoring-and-pooling/tests/logging/connection-logging.yml
DRIVERS-1675
Drivers need to account for the logs created by closing the client as an operation, including those produced by ending a session.
=> DRIVERS-1675 Add the end session log expectations for CMAP

source/auth/auth.rst, source/auth/tests/mongodb-aws.rst
- Create a new client before a `find` operation. 
- Clear the AWS environment variables after the test.
- Clear the cache before steps expecting to cache credentials.
Create a new client before a `find` operation to ensure authentication is attempted.
Clear the AWS environment variables after the test to prevent the environment variable interacting with  other tests.
~~- [ ] Make sure there are generated JSON files from the YAML test files.~~
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~
=> DRIVERS-2333 add steps to credential caching tests

source/client-side-operations-timeout/client-side-operations-timeout.rst, source/client-side-operations-timeout/tests/command-execution.json, source/client-side-operations-timeout/tests/command-execution.yml, source/client-side-operations-timeout/tests/legacy-timeouts.yml, source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst, source/server-discovery-and-monitoring/server-monitoring.rst
https://jira.mongodb.org/browse/DRIVERS-2035
=> DRIVERS-2035 Use minimum RTT for CSOT maxTimeMS calculation instead of 90th percentile

source/unified-test-format/unified-test-format.rst
This PR fixes a small typo in the description of the `$$matchAsRoot` operator which may have caused some confusion when interpreting what the desired behaviour should be.
=> Fix typo in description of `$$matchAsRoot` operator

source/client-side-encryption/client-side-encryption.rst, source/client-side-encryption/etc/test-templates/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml.template, source/client-side-encryption/tests/legacy/fle2-CreateCollection.json, source/client-side-encryption/tests/legacy/fle2-CreateCollection.yml, source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json, source/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
- Update `fle2-*` tests to match collection name requirements in [SERVER-74069](https://jira.mongodb.org/browse/SERVER-74069)
Tested with the Go driver here: https://spruce.mongodb.com/version/63ffbcc532f4174d14a8b56d/tasks
[SERVER-74069](https://jira.mongodb.org/browse/SERVER-74069) adds a server requirements for the Queryable Encryption state collection namespaces.
State collection names are now required to have the form `enxcol_.<collection>.esc`, `enxcol_.<collection>.ecc`, or `enxcol_.<collection>.ecoc`.
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~ **Tested with replica set**
=> DRIVERS-2565 Update `fle2-*` tests to match collection name requirements in SERVER-74069

source/auth/auth.rst
- replace typo of `AWS_ROLE_SESSION_NAME` to `AWS_ROLE_ARN`
- fix typo of environment
~~- [ ] Make sure there are generated JSON files from the YAML test files.~~
~~- [ ] Test changes in at least one language driver.~~
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~
=> DRIVERS-1746 replace typo of `AWS_ROLE_SESSION_NAME` to `AWS_ROLE_ARN`

source/auth/auth.rst, source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml, source/auth/tests/mongodb-oidc.rst
The device workflow terminology was a bit confusing since OIDC device flow generally refers to a user interaction on a device (such as a phone or computer) to perform an action to get a token. This changes to use `PROVIDER_NAME` instead of `DEVICE_NAME` as a mechanism property and changes language of device workflow to "as service to obtain credentials".
=> fix(DRIVERS-2415): change device terminology to service provider

source/auth/tests/legacy/connection-string.json, source/auth/tests/unified/reauthenticate_without_retry.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-interrupting-pending-connections.json
This PR fixes the [Regenerate JSON test files](https://github.com/mongodb/specifications/actions/runs/4575395096/jobs/8078173164) task.
JSON files were regenerated locally using `make --always-make`. The `--always-make` option ignores file last-modification times and unconditionally makes the targets.
---
~~- [ ] Update changelog.~~ **Not applicable**
~~- [ ] Test changes in at least one language driver.~~ **Not applicable**
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~ **Not applicable**
=> regenerate JSON test files

source/mongodb-handshake/handshake.rst
DRIVERS-2209
The preservation order introduced in #1386 turned out to be both confusing and mildly broken - the server has constraints about the `driver` and `application` documents it wasn't respecting.  This PR simplifies the spec to only resolve the ambiguity that would otherwise have been introduced between `platform` and `env`; a larger scope set of rules, if needed, should be its own spec update.
=> DRIVERS-2209 Simplify metadata truncation rules

source/client-side-encryption/client-side-encryption.rst
I'm pretty sure this was a typo, but I'd like to defer to one of the spec owners to confirm.
This dates back to https://github.com/mongodb/specifications/commit/4de4e3c1897ca07efa09d456943badbe002cd756 for #1355.
=> DRIVERS-2505: Fix typo in RangeOpts doc block

source/client-side-encryption/tests/README.rst
The encryptedFields-Range-type.json files are used by test templates to generate spec tests (https://github.com/mongodb/specifications/commit/3634d568587a776f18885502cde4f26f1c0ac051). Prose tests rely on the range-encryptedFields-type.json files (https://github.com/mongodb/specifications/commit/4de4e3c1897ca07efa09d456943badbe002cd756).
=> Fix filename example in range index prose test

source/mongodb-handshake/handshake.rst
DRIVERS-2209
VERCEL_URL could potentially contain sensitive information, so it shouldn't be collected.  Also, as vercel runs on top of aws, it needs to take precedence when detecting the host environment.
=> DRIVERS-2209 Remove VERCEL_URL from collection and specify vercel>aws precedence

source/client-side-encryption/etc/test-templates/bypassedCommand.yml.template, source/client-side-encryption/tests/legacy/bypassedCommand.json, source/client-side-encryption/tests/legacy/bypassedCommand.yml, source/unified-test-format/tests/valid-pass/collectionData-createOptions.json, source/unified-test-format/tests/valid-pass/collectionData-createOptions.yml
Node POC: https://github.com/mongodb/node-mongodb-native/pull/3638
This PR removes usage of the `collStats` command and `currentOp` from tests.  
=> DRIVERS-2232: remove usages of `currentOp` and `collStats` from tests

source/mongodb-handshake/handshake.rst
- Remove `env.url` from `Hello Command` structure
This is a follow up to https://github.com/mongodb/specifications/pull/1398.
`env.url` is no longer expected to be set by drivers.
- ~~[ ] Update changelog.~~ **Not applicable? This is a minor fix**
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ **Not applicable.**
- ~~[ ] Test changes in at least one language driver.~~ **Not applicable**
- ~~[ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~ **Not applicable**
=> DRIVERS-2209 remove `env.url` reference

source/command-logging-and-monitoring/command-logging-and-monitoring.rst, source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/README.rst
- See CSHARP-4483.
- Added prose tests.
=> DRIVERS-2503: Require connectionId and serverConnectionId to be int64.

source/client-side-encryption/tests/README.rst
- Clarify type returned by `clientEncryption.decrypt()` may not match input type to `clientEncryption.encrypt()`
Clarification was requested in [this slack conversation](https://mongodb.slack.com/archives/C0406ECL478/p1681999190775319?thread_ts=1681989382.950349&cid=C0406ECL478).
- ~~[ ] Update changelog.~~ **Not applicable.**
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ **Not applicable.**
- ~~[ ] Test changes in at least one language driver.~~**Not applicable.**
- ~~[ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).~~**Not applicable.**
=> DRIVERS-2505 clarify type expectations in prose test

source/client-side-encryption/tests/README.rst
https://jira.mongodb.org/browse/DRIVERS-2505
Follow-up to https://github.com/mongodb/specifications/pull/1409.
This adds clarifying text and revises formatting inconsistencies throughout the test file. It does not change test behavior.
=> DRIVERS-2505: Clarifications for Range Explicit Encryption prose tests 

source/mongodb-handshake/handshake.rst
https://jira.mongodb.org/browse/DRIVERS-2623
Tested in Python here: https://github.com/mongodb/mongo-python-driver/pull/1204
=> DRIVERS-2623 AWS_EXECUTION_ENV must start with "AWS_Lambda_"

source/run-command/run-command.rst, source/run-command/tests/unified/runCommand.json, source/run-command/tests/unified/runCommand.yml
https://jira.mongodb.org/browse/DRIVERS-2577
POC PR in PHPLIB: https://github.com/mongodb/mongo-php-library/pull/1066
=> DRIVERS-2577: $readPreference is not sent to standalone server

source/client-side-encryption/tests/README.rst
- Add prose test to ensure error is returned when calling `rewrapManyDataKey` with a set `masterKey` without a `provider`.
The specified API for `rewrapManyDataKey` does not permit calling with a set `masterKey` without a `provider`.
```typescript
class ClientEncryption {
rewrapManyDataKey(filter: Document, opts: RewrapManyDataKeyOpts | null): RewrapManyDataKeyResult;
}
class RewrapManyDataKeyOpts {
provider: String
masterKey: Optional<Document>
}
```
Some driver implementations do not represent `RewrapManyDataKeyOpts` as a separate type. Instead, the `provider` and `masterKey` are both optional arguments to `RewrapManyDataKey`.
The C driver API permits setting `masterKey` without `provider`:
```c
MONGOC_EXPORT (bool)
mongoc_client_encryption_rewrap_many_datakey ( …
```
=> DRIVERS-2441 add prose test Rewrap Case 2

source/client-side-encryption/client-side-encryption.rst
This dates back to aa28f787718eb4306ce7ff8e5a87bd46bb0a2c05
=> Fix RST syntax for inline literal

source/client-side-encryption/etc/test-templates/getMore.yml.template, source/client-side-encryption/tests/legacy/getMore.json, source/client-side-encryption/tests/legacy/getMore.yml, source/load-balancers/tests/cursors.json, source/load-balancers/tests/cursors.yml, source/unified-test-format/tests/valid-pass/entity-cursor-iterateOnce.json, source/unified-test-format/tests/valid-pass/entity-cursor-iterateOnce.yml, source/unified-test-format/tests/valid-pass/entity-find-cursor.json, source/unified-test-format/tests/valid-pass/entity-find-cursor.yml
This accommodate drivers that encode BSON integers according to their range and is consistent with what is done in most other spec tests.
=> DRIVERS-2641: Allow int32 or int64 for getMore cursor ID

source/client-side-encryption/tests/legacy/fle2v2-CreateCollection.json, source/client-side-encryption/tests/legacy/fle2v2-CreateCollection.yml, source/transactions/tests/README.rst
- Remove null values from `command_started_event` in fle2v2-CreateCollection.yml.
- Link to legacy command monitoring spec tests runner in transactions test README.rst.
- Note `null` is only expected in top level fields of `command`.
The C driver incorrectly allows extra fields in subdocuments of the `command`. With this behavior fixed, the updated `fle2v2-CreateCollection.yml` test was [run in this patch](https://spruce.mongodb.com/version/6478a0cd7742ae7b3d6e48e3)
DRIVERS-2524 added a legacy Client Side Encryption (CSE) test with embedded null fields in a `command_started_event` in [fle2v2-CreateCollection.yml](https://github.com/mongodb/specifications/blob/aa28f78/source/client-side-encryption/tests/legacy/fle2v2-CreateCollection.yml#L99-L107):
```yml
- command_started_event:
command: …
```
=> DRIVERS-2619 Remove null values from `command_started_event` in fle2v2-CreateCollection.yml

source/client-side-encryption/tests/README.rst
The command monitoring spec's legacy test runner was removed in c51e7373aab211ed673061bd6fdb542f655e413d when all tests were ported to the unified format.
Re: https://github.com/mongodb/specifications/pull/1429#discussion_r1218134427
=> Link to command monitoring spec legacy test runner

source/command-logging-and-monitoring/command-logging-and-monitoring.rst, source/command-logging-and-monitoring/tests/monitoring/find.json, source/command-logging-and-monitoring/tests/monitoring/find.yml, source/unified-test-format/schema-1.15.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/invalid/expectedCommandEvent-commandFailedEvent-databaseName-type.json, source/unified-test-format/tests/invalid/expectedCommandEvent-commandFailedEvent-databaseName-type.yml, source/unified-test-format/tests/invalid/expectedCommandEvent-commandSucceededEvent-databaseName-type.json, source/unified-test-format/tests/invalid/expectedCommandEvent-commandSucceededEvent-databaseName-type.yml, source/unified-test-format/unified-test-format.rst
[DRIVERS-2452](https://jira.mongodb.org/browse/DRIVERS-2452)
Add `databaseName` field to `CommandFailedEvent` and `CommandSucceededEvent`.
=> DRIVERS-2452 Add databaseName field to CommandFailedEvent

source/client-side-encryption/client-side-encryption.rst
I'd consider this a small fix not worthy of a changelog entry but let me know if you disagree.
=> Fix error condition for contentionFactor option

source/client-side-encryption/etc/test-templates/explain.yml.template, source/client-side-encryption/tests/legacy/explain.json, source/client-side-encryption/tests/legacy/explain.yml
In previous server versions, apiVersion is not properly appended to the root of an explain command document.
When testing with requireApiVersion=1, that can cause test failures if the driver does not have additional logic to always append the field to a crypt_shared/mongocryptd respnse.
POC: https://github.com/mongodb/mongo-php-library/pull/1111
As noted in [DRIVERS-2612](https://jira.mongodb.org/browse/DRIVERS-2612?focusedCommentId=5502676&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5502676), this is blocked on the release of 7.0.0-rc4 for [BACKPORT-16190](https://jira.mongodb.org/browse/BACKPORT-16190).
=> DRIVERS-2612: Require 7.0+ for explain apiVersion bug fix

source/client-side-encryption/tests/README.rst, source/unified-test-format/unified-test-format.rst
https://jira.mongodb.org/browse/DRIVERS-2661
=> DRIVERS-2661: Clarify requirements for CSFLE spec/prose tests

source/command-logging-and-monitoring/command-logging-and-monitoring.rst, source/command-logging-and-monitoring/tests/logging/command.json, source/command-logging-and-monitoring/tests/logging/command.yml
[DRIVERS-2452](https://jira.mongodb.org/browse/DRIVERS-2452)
Add the database name to the "command failed" and "command succeeded" log messages.
=> DRIVERS-2452 Add database name to the "command failed" and "command succeeded" log messages

source/faas-automated-testing/faas-automated-testing.rst
Updates the FaaS testing spec to recommend using task groups as provided in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/325
Node impl: https://github.com/mongodb/node-mongodb-native/pull/3740
=> test(DRIVERS-2657): update faas testing spec

source/run-command/tests/unified/runCommand.json, source/run-command/tests/unified/runCommand.yml
https://jira.mongodb.org/browse/DRIVERS-2675
Although one test does not specify a minServerVersion, "sharded-replicaset" is still redundant since $readPreference is always sent to mongos.
=> DRIVERS-2675: Remove use of "sharded-replicaset"

source/client-side-operations-timeout/client-side-operations-timeout.rst, source/index-management/index-management.rst, source/index-management/tests/README.rst, source/index-management/tests/createSearchIndex.json, source/index-management/tests/createSearchIndex.yml, source/index-management/tests/createSearchIndexes.json, source/index-management/tests/createSearchIndexes.yml, source/index-management/tests/dropSearchIndex.json, source/index-management/tests/dropSearchIndex.yml, source/index-management/tests/listSearchIndexes.json, source/index-management/tests/listSearchIndexes.yml, source/index-management/tests/updateSearchIndex.json, source/index-management/tests/updateSearchIndex.yml
This PR does three things:
- This PR adds prose tests for the search index management helpers
- This PR strengthens assertions on the existing unified tests for the search index management helpers.
- This PR includes some clarifications in the search index management spec.
The third bullet can be separated into a different PR if necessary.
Node POC: https://github.com/mongodb/node-mongodb-native/pull/3736
The initial plan was to enhance the unified test runner to support the new search index management commands.  There ended up being complications integrating support for the new commands into the UTR (the largest issue was that the commands are asynchronous, and return from the server before the changes have finished).  The unified tests were already written and expected errors when run …
=> DRIVERS-2630: add e2e testing for search index commands and clarifications to search index spec

source/bson-corpus/tests/binary.json
The new test validates only the correct subtype, number encoding/decoding, and binary data encoding/decoding. Any binary data itself is not validated. [DRIVERS-2687](https://jira.mongodb.org/browse/DRIVERS-2687) specifies that data using this subtype is meant to not be logged, so this should satisfy testing requirements.
=> DRIVERS-2687 Add BSON Binary Data subtype Sensitive

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst, source/connection-monitoring-and-pooling/tests/logging/connection-logging.json, source/connection-monitoring-and-pooling/tests/logging/connection-logging.yml, source/connection-monitoring-and-pooling/tests/logging/connection-pool-options.json, source/connection-monitoring-and-pooling/tests/logging/connection-pool-options.yml
This spec change is implemented in https://github.com/mongodb/mongo-java-driver/pull/1166 for the MongoDB Java Driver.
There are no unified tests for `CommandSucceededEvent`/`CommandFailedEvent.duration` (see https://github.com/mongodb/specifications/blob/master/source/command-logging-and-monitoring/command-logging-and-monitoring.rst), similarly, there are no unified tests in this PR except those for logging.
DRIVERS-2469
=> DRIVERS-2469 Add durations to connection pool events

source/change-streams/change-streams.rst, source/change-streams/tests/README.rst
- [*] Update changelog.
- [n/a] Make sure there are generated JSON files from the YAML test files.
- [*] Test changes in at least one language driver.
- [*] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
https://github.com/mongodb/mongo-rust-driver/pull/930 implements this for the Rust driver.
=> DRIVERS-2674 Update server versions for `$changeStreamSplitLargeEvent` test

source/faas-automated-testing/faas-automated-testing.rst
=> DRIVERS-2384 FaaS testing spec clarifications

source/faas-automated-testing/faas-automated-testing.rst
Fixes `MONGODB_URI` typo, makes notes on how Docket can access a localhost server, increases assume role duration to 1 hour (from default 15 minutes)
=> chore(DRIVERS-2384): update localhost test domain

source/retryable-reads/retryable-reads.rst
This PR proposes a re-phrasing of the "[Why are read operations only retried once by default?](https://github.com/mongodb/specifications/blob/master/source/retryable-reads/retryable-reads.rst#id40)" section of retryable reads to fix inconsistencies between the retryable reads and SDAM specifications. From the retryable reads [Q&A](https://github.com/mongodb/specifications/blob/master/source/retryable-reads/retryable-reads.rst#why-are-read-operations-only-retried-once-by-default) on why read operations are only retried once:
> In the case of a transient error, the driver will mark the server as “unknown” per the [SDAM](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst) spec.
From the SDAM rationale for “[Other …
=> Sync retryable reads with SDAM

source/retryable-reads/retryable-reads.rst, source/retryable-reads/tests/README.rst, source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/README.rst, source/server-selection/server-selection.rst
Ruby PoC - https://github.com/mongodb/mongo-ruby-driver/pull/2717
Go PoC     - https://github.com/mongodb/mongo-go-driver/pull/1358
=> DRIVERS-1571 Retry on different mongos when possible

source/mongodb-handshake/handshake.rst
- [✓] Update changelog.
- [n/a] Make sure there are generated JSON files from the YAML test files.
- [✓] Test changes in at least one language driver.
- [✓] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless).
https://github.com/mongodb/mongo-rust-driver/pull/940 implements this in the Rust driver.
=> DRIVERS-2570 Report docker or kubernetes environment in handshake

source/index-management/tests/README.rst
While reviewing https://github.com/mongodb/mongo-php-library/pull/1097 I noticed several formatting issues in RST for Atlas Search prose tests. Most notably, the code blocks within each test were not indented correctly and caused the steps to reset from one.
This PR follows a previous commit to fix an RST issue: https://github.com/mongodb/specifications/commit/53303ddc05ec6f3c9c6353ec590a15a997845de6
=> Reformat RST for Atlas Search prose tests

source/collection-management/tests/timeseries-collection.json, source/collection-management/tests/timeseries-collection.yml
Update spec test's minServerVersion due to the availability of bucketing options starting from version 6.3
Related server ticket: [SERVER-67598](https://jira.mongodb.org/browse/SERVER-67598)
Related documentation: [timeseries-procedures](https://www.mongodb.com/docs/v7.0/core/timeseries/timeseries-procedures/)
=> DRIVERS-2720: Update spec test's minServerVersion

source/connection-string/connection-string-spec.rst, source/connection-string/tests/invalid-uris.json, source/connection-string/tests/invalid-uris.yml, source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-options.yml
- Change spec language to make delimiting slash between hosts and connection options optional.
- Updated connection-string spec tests to allow optional delimiting slash
=> DRIVERS-2679: make delimiting slash between hosts and connection options optional

.gitattributes
See: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
We recently started doing this in the PHP driver repositories for generated code (https://github.com/mongodb/mongo-php-driver/pull/1473#discussion_r1338192073).
=> Hide generated JSON spec test files from displaying in diffs by default

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst
DRIVERS-2707
@baileympearson, @matthewdale I added you as reviewers because you approved the [PR](https://github.com/mongodb/specifications/pull/1448) where I introduced the wording that this PR changes.
=> DRIVERS-2707 Relax the CMAP documentation requirement for durations in events

source/driver-bulk-update.rst
Update Bulk API to indicate `maxWriteBatchSize` change in 3.6
=> Update Bulk API to indicate `maxWriteBatchSize` change in 3.6

source/retryable-writes/retryable-writes.rst
- Add the case the pseudo-code for the retryable writes specification: CSOT is not enabled and one retry was attempted.
- Fix some syntax errors.
Driver changes are not needed.
=> DRIVERS-2695 Add a case of CSOT not enabled for the retryable writes.

source/command-logging-and-monitoring/command-logging-and-monitoring.rst
The Go Driver had a user inquire about adding an operation command to CommandSucceededEvent/CommandFailedEvent. The reason for why we don't do this is addressed in [INT-76](https://jira.mongodb.org/browse/INT-76). This PR suggests extending the specifications to include this information in a Q&A section.
Additionally, the headers for this file appear to be incorrectly structured per the rst [docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html), causing a runtime error when trying to add a section with correct formatting:
```
command-logging-and-monitoring.rst:35: (SEVERE/4) Title level inconsistent:
```
Removed use cases of `---\nx\n---` and replaced with just `---`. Updated subsections to use `^`. 
---
=> Add Q&A Section to Command Logging and Monitoring

source/initial-dns-seedlist-discovery/tests/replica-set/uri-with-uppercase-hostname.json, source/initial-dns-seedlist-discovery/tests/replica-set/uri-with-uppercase-hostname.yml
[DRIVERS-2668](https://jira.mongodb.org/browse/DRIVERS-2668). Unfortunately, as noted in [DEVPROD-174](https://jira.mongodb.org/browse/DEVPROD-174), it's not possible to add the exact test case I envisioned for DRIVERS-2668 (where DNS returns uppercase letters in the SRV result). However we can still add this related test case with uppercase letters in the initial SRV hostname.
=> DRIVERS-2668 Add SRV test with uppercase hostname

source/transactions-convenient-api/transactions-convenient-api.rst, source/transactions/transactions.rst
[Ruby Implementation](https://github.com/mongodb/mongo-ruby-driver/pull/2809)
=> DRIVERS-2584 Errors handling in Convenient Transactions API

source/retryable-writes/retryable-writes.rst
=> DRIVERS-1150 Writes are not retried within transactions

source/retryable-writes/tests/unified/bulkWrite-serverErrors.json, source/retryable-writes/tests/unified/bulkWrite-serverErrors.yml, source/retryable-writes/tests/unified/insertOne-serverErrors.json, source/retryable-writes/tests/unified/insertOne-serverErrors.yml, source/unified-test-format/tests/valid-pass/poc-retryable-writes.json, source/unified-test-format/tests/valid-pass/poc-retryable-writes.yml
https://jira.mongodb.org/browse/DRIVERS-2799
This also fixes an outstanding inconsistency in one of the retryable writes POC tests for the unified test runner, which would otherwise start failing once [DRIVERS-1641](https://jira.mongodb.org/browse/DRIVERS-1641) is implemented.
PHPLIB POC: https://github.com/mongodb/mongo-php-library/pull/1210
----
=> DRIVERS-2799: Use more permissive top-level runOnRequirements

source/index-management/tests/searchIndexIgnoresReadWriteConcern.json, source/index-management/tests/searchIndexIgnoresReadWriteConcern.yml
This fixes a wrong test name in the Atlas Search Indexes tests. The duplicate description causes errors when running these tests on PHP. Drivers that don't encounter issues when running these tests don't need to sync them right away.
=> Fix wrong test description

source/retryable-writes/tests/legacy/insertOne-errorLabels.json, source/retryable-writes/tests/legacy/insertOne-errorLabels.yml
https://jira.mongodb.org/browse/DRIVERS-2802
This corrects a mistake introduced in 5fc23f40f79d18f0693e7159eba81f0e7b276715 when these tests were originally moved from insertOne-serverErrors
This was missed in the POC for #1489 since libmongoc doesn't report inserted IDs (see: [json-test-operations.c](https://github.com/mongodb/mongo-c-driver/blob/1.25.4/src/libmongoc/tests/json-test-operations.c#L370)).
POC for this change: https://github.com/mongodb/mongo-php-library/pull/1214
=> DRIVERS-2802: Fix insertedId expectations in insertOne-errorLabels

source/retryable-writes/retryable-writes.rst, source/retryable-writes/tests/unified/insertOne-serverErrors.json, source/retryable-writes/tests/unified/insertOne-serverErrors.yml
https://jira.mongodb.org/browse/DRIVERS-1641
Also clarify that pre-4.4 writeErrors[].code should never be used to determine retryability. This is intentionally untested because failCommand does not provide a way to mock writeErrors.
POC: https://github.com/mongodb/mongo-c-driver/pull/1501
Patch build: https://spruce.mongodb.com/version/65a19aa461837db75d4d8efe/tasks (4.2-replica-auth and 4.2-sharded-auth are the relevant tasks).
----
=> DRIVERS-1641: pre-4.4 mongos writeConcernError does not determine retryability

source/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml, source/client-side-encryption/tests/unified/createDataKey.yml, source/client-side-encryption/tests/unified/deleteKey.yml, source/client-side-encryption/tests/unified/getKey.yml, source/client-side-encryption/tests/unified/getKeyByAltName.yml, source/client-side-encryption/tests/unified/rewrapManyDataKey-decrypt_failure.yml, source/client-side-encryption/tests/unified/rewrapManyDataKey-encrypt_failure.yml, source/client-side-encryption/tests/unified/rewrapManyDataKey.yml
Intended to prevent YAML parsers from incorrectly parsing the colon as a key/value separator.
Requested in https://github.com/mongodb/specifications/pull/1492#discussion_r1456230649
- ~~[ ] Update changelog.~~ Not applicable.
- ~~[ ] Test changes in at least one language driver.~~ Not applicable.
clusters, and serverless).~~ Not applicable.
=> quote "arn" strings

source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-interrupting-pending-connections.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-interrupting-pending-connections.yml
DRIVERS-2835. Testing in python here: https://github.com/mongodb/mongo-python-driver/pull/1528
=> DRIVERS-2835 Increase interruptInUseConnections timeout to fix flaky test

source/unified-test-format/unified-test-format.md
- [N/A] Make sure there are generated JSON files from the YAML test files.
- [N/A] Test changes in at least one language driver.
Based on discussions in DRIVERS-2816 this change should be sufficient.
=> DRIVERS-2816: Gossip cluster time from internal MongoClient to session entities

scripts/migrate_to_md.py, source/auth/auth.md, source/bson-decimal128/decimal128.md, source/change-streams/change-streams.md, source/client-side-operations-timeout/client-side-operations-timeout.md, source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.md
=> DRIVERS-2789 Replace curly quotes with regular quotes

source/read-write-concern/tests/README.rst, source/read-write-concern/tests/operation/default-write-concern-2.6.json, source/read-write-concern/tests/operation/default-write-concern-2.6.yml, source/read-write-concern/tests/operation/default-write-concern-3.2.json, source/read-write-concern/tests/operation/default-write-concern-3.2.yml, source/read-write-concern/tests/operation/default-write-concern-3.4.json, source/read-write-concern/tests/operation/default-write-concern-3.4.yml, source/read-write-concern/tests/operation/default-write-concern-4.2.json, source/read-write-concern/tests/operation/default-write-concern-4.2.yml, source/unified-test-format/tests/Makefile
https://jira.mongodb.org/browse/DRIVERS-2855
POC: https://github.com/mongodb/mongo-php-library/pull/1252
=> DRIVERS-2855: Convert default write concern tests to unified format

source/read-write-concern/tests/operation/default-write-concern-3.4.json, source/read-write-concern/tests/operation/default-write-concern-3.4.yml
https://jira.mongodb.org/browse/DRIVERS-2855
This was missed in #1547 (bfb6a841819e117aa7f066beae4cfa9da7690a1b)
> [x] Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and _serverless_).
...and that was a lie.
See: https://github.com/mongodb/mongo-php-library/pull/1253#discussion_r1523355940
=> DRIVERS-2855: Skip $out and mapReduce tests on serverless

source/auth/auth.md, source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml, source/auth/tests/mongodb-oidc.md, source/auth/tests/unified/mongodb-oidc-no-retry.yml, source/unified-test-format/unified-test-format.md
(cherry picked from commit dde0632)
=> DRIVERS-2856 Rename OIDC integration name and values.

source/client-side-encryption/client-side-encryption.md, source/client-side-encryption/tests/README.md
=> DRIVERS-2789 Fix Math Rendering in Client Side Encryption Spec

source/command-logging-and-monitoring/tests/logging/unacknowledged-write.json, source/command-logging-and-monitoring/tests/logging/unacknowledged-write.yml, source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.json, source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.yml
This will force completion of the w: 0 write, which addresses a TCP-based race condition in the tests
- [N/A] Update changelog.
- [Done] Make sure there are generated JSON files from the YAML test files.
- [Done] Test changes in at least one language driver.
- [Done] Test these changes against all server versions and topologies (including standalone, replica set, sharded
Note: there are other w: 0 writes in the unified tests but none that appear to be causing issues so leaving them alone for now.
=> DRIVERS-2877: Follow w: 0 write with a find in spec tests

source/auth/auth.md, source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml
=> DRIVERS-2601 OIDC: Automatic token acquisition for GCP Identity Provider

source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-is-enforced.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-is-enforced.yml
Updates the blocktime and wait time for the maxConnecting-is-enforced test to make the test less flaky. 
Node implementation: https://github.com/mongodb/node-mongodb-native/pull/4074
DRIVERS-2874
=> DRIVERS-2874: fix flaky maxConnecting-is-enforced CMAP test

source/server-discovery-and-monitoring/server-discovery-and-monitoring-logging-and-monitoring.rst, source/unified-test-format/schema-1.20.json, source/unified-test-format/tests/Makefile, source/unified-test-format/tests/valid-pass/expectedEventsForClient-topologyDescriptionChangedEvent.json, source/unified-test-format/tests/valid-pass/expectedEventsForClient-topologyDescriptionChangedEvent.yml, source/unified-test-format/unified-test-format.md
- Updated unified test format spec to detail how assertions on `topologyDescriptionChangedEvents` should be done
- Updated schema to support this spec change
- Added valid pass test for addition to schema
- Bumped schema version in makefile for unified test runner
=> DRIVERS-2875: add support for TopologyDescriptionChangedEvent to expectEvents

source/connection-monitoring-and-pooling/tests/cmap-format/README.md, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkin-make-available.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkin-make-available.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-connection.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-connection.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-error-closed.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-error-closed.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-timeout.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-timeout.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-clears-waitqueue.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-clears-waitqueue.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-ready.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-clear-ready.yml, source/connection-monitoring-and-pooling/tests/cmap-format/pool-ready.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-ready.yml, source/connection-monitoring-and-pooling/tests/cmap-format/wait-queue-timeout.json, source/connection-monitoring-and-pooling/tests/cmap-format/wait-queue-timeout.yml
[DRIVERS-2900](https://jira.mongodb.org/browse/DRIVERS-2900)
The CMAP logging tests currently check for durations to be set , but the CMAP pool event tests do not. Test that durations are included on relevant pool events.
=> DRIVERS-2900 Test that durations are included on relevant pool events.

source/auth/auth.md, source/auth/auth.rst, source/mongodb-handshake/handshake.rst, source/mongodb-handshake/tests/README.md
Ruby PoC - https://github.com/mongodb/mongo-ruby-driver/pull/2858
=> DRIVERS-2769 Clarify not validating saslSupportedMechs

source/index-management/index-management.md, source/index-management/index-management.rst, source/index-management/tests/README.md, source/index-management/tests/createSearchIndex.json, source/index-management/tests/createSearchIndex.yml, source/index-management/tests/createSearchIndexes.json, source/index-management/tests/createSearchIndexes.yml
[DRIVERS-2768](https://jira.mongodb.org/browse/DRIVERS-2768)
=> DRIVERS-2768 [Vector Search GA] Add support for types in search index creation

source/auth/auth.md, source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml, source/unified-test-format/unified-test-format.md
=> DRIVERS-2836 OIDC: Clarify that TOKEN_RESOURCE must be url-encoded

source/resources, source/server-discovery-and-monitoring/tests/rs/compatible.json, source/server-discovery-and-monitoring/tests/rs/compatible.yml, source/server-discovery-and-monitoring/tests/rs/compatible_unknown.json, source/server-discovery-and-monitoring/tests/rs/compatible_unknown.yml, source/server-discovery-and-monitoring/tests/sharded/compatible.json, source/server-discovery-and-monitoring/tests/sharded/compatible.yml, source/server-discovery-and-monitoring/tests/single/compatible.json, source/server-discovery-and-monitoring/tests/single/compatible.yml, source/server-discovery-and-monitoring/tests/single/too_old_then_upgraded.json, source/server-discovery-and-monitoring/tests/single/too_old_then_upgraded.yml
Once a driver removes support for MongoDB 3.6 and updates its minWireVersion from 6 to 7, these tests start to fail due to the wire version compatibility check required by the test runner.
Bumping from 6 to 21 (MongoDB 7.0 maxWireVersion) should hold us for a while.
Note: I don't think the intention of any of these tests were to check the minWireVersion of the driver, as they have been at 6 long before 6 was the minWireVersion.
- [ N/A] Update changelog.
- [ Done] Make sure there are generated JSON files from the YAML test files.
- [ Done (Java)] Test changes in at least one language driver.
- [ N/A] Test these changes against all server versions and topologies (including standalone, replica set, sharded
=> DRIVERS-2511: Update maxWireVersion from 6 to 21

source/client-side-operations-timeout/tests/convenient-transactions.json, source/client-side-operations-timeout/tests/convenient-transactions.yml, source/client-side-operations-timeout/tests/sessions-inherit-timeoutMS.json, source/client-side-operations-timeout/tests/sessions-inherit-timeoutMS.yml, source/client-side-operations-timeout/tests/sessions-override-operation-timeoutMS.json, source/client-side-operations-timeout/tests/sessions-override-operation-timeoutMS.yml, source/client-side-operations-timeout/tests/sessions-override-timeoutMS.json, source/client-side-operations-timeout/tests/sessions-override-timeoutMS.yml
=> DRIVERS-2871 CSOT tests: Expect withTransaction to propagate errors

source/retryable-reads/retryable-reads.md, source/retryable-writes/retryable-writes.md
- ~~[ ] Update changelog.~~ Typo fix only.
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ Not applicable.
- ~~[ ] Test changes in at least one language driver.~~ Not applicable.
clusters, and serverless).~~ Not applicable.
=> DRIVERS-2905 fix link to `PoolClearedError`

source/crud/bulk-write.md, source/crud/tests/README.md
`json` code blocks don't render nicely in github when their contents aren't valid JSON, e.g.:
```json
InsertOne {
"namespace": "db.coll",
"document": { "a": <int32> },
}
```
This PR ports them to `javascript` blocks, which look better:
```javascript
InsertOne {
"namespace": "db.coll",
"document": { "a": <int32> },
}
```
=> Improve rendering for bulk write JSON-like blocks

.github/workflows/lint.yml, .pre-commit-config.yaml, source/retryable-writes/tests/README.md, source/server-discovery-and-monitoring/server-monitoring.md, source/transactions/transactions.md, source/unified-test-format/unified-test-format.md
=> DRIVERS-2870 Fix content of retryable-writes-test readme

source/server_write_commands.rst
Also remove mention of upsert in the FAQ about client-side _id generation
=> Update FAQ to indicate legacy opcodes were removed

source/auth/auth.md, source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml, source/auth/tests/mongodb-oidc.md, source/connection-string/connection-string-spec.md, source/connection-string/tests/invalid-uris.yml, source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-options.yml, source/connection-string/tests/valid-warnings.json, source/connection-string/tests/valid-warnings.yml
=> DRIVERS-2915 OIDC: Disallow comma character in authMechanismProperties connection string value

source/client-side-encryption/tests/README.md
A missing newline from https://github.com/mongodb/specifications/commit/9bfa512e41c1231a51f83260f5672a36626d9bcd caused mdformat to crash.
=> Formatting fix for client-side-encryption/tests/README.md

source/command-logging-and-monitoring/tests/logging/unacknowledged-write.json, source/command-logging-and-monitoring/tests/logging/unacknowledged-write.yml, source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.json, source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.yml
https://jira.mongodb.org/browse/DRIVERS-2921
cd08b7248eb4e3ab901a8f7905874da41b908f7c added find operations after a w:0 write to ensure it applies, but the client also needs useMultipleMongoses:false to ensure this happens on the same host.
----
Patch build: https://spruce.mongodb.com/version/666093b08fe04300077b53b7/tasks
=> DRIVERS-2921: Use single mongos for unacknowledged write tests

source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml
When implementing OIDC in the Ruby driver I noticed that the username with `ENVIRONMENT:test` spec test was not failing because of the username being present but rather the URI was actually invalid, since `ENVIRONMENT:test` was not in the `authMechanismProperties`. This fixes that test.
Tests running on this PR: https://github.com/mongodb/mongo-ruby-driver/pull/2873
=> fix uri in username with test environment oidc test

source/client-side-encryption/etc/test-templates/timeoutMS.yml.template, source/client-side-encryption/tests/legacy/timeoutMS.json, source/client-side-encryption/tests/legacy/timeoutMS.yml
DRIVERS-2847
- Fix client-side encryption test in timeoutMS.yml by correcting the number of expected listCollections operations to one, based on libmongocrypt's caching behavior. 
- Update description to reflect that the internal MongoClient, not configured for auto encryption, does not generate extra listCollections events.
Tested in Java driver https://github.com/mongodb/mongo-java-driver/pull/1363.
=> DRIVERS-2847 Update CSOT encryption test for listCollections

source/connection-string/connection-string-spec.md, source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-options.yml, source/connection-string/tests/valid-warnings.json, source/connection-string/tests/valid-warnings.yml
DRIVERS-2915 (followup)
At least one driver (Java) requires `authMechanism` to be provided when `authMechanismProperties` are provided. Minor clarification, but no changes to substance of the spec. Fixes/narrows tests, including a formatting issue.
=> DRIVERS-2915 Add authMechanism option to tests where needed

source/client-side-encryption/client-side-encryption.md
Document "range" as unstable.
This is a follow-up to https://github.com/mongodb/specifications/pull/1587. Some drivers have implemented "range" support for DRIVERS-2767. There is pending work that may impact drivers (DRIVERS-2927). This is intended to unblock driver releases in the short term. Driver releases may be needed soon to comply with SSDLC.
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ N/A.
- ~~[ ] Test changes in at least one language driver.~~ N/A.
clusters, and serverless).~~ N/A.
=> DRIVERS-2928 document "range" as unstable

source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.json, source/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.yml
This removes a command expectation for a find command in the command monitoring tests. We've observed frequent failures on sharded clusters, which we assume are related to replication lag. Since the goal of the test is to test command monitoring for writes with `w: 0` and not the successful execution of such writes, I assume it's safe to remove the result expectation to reduce flakiness.
=> Remove result expectation in command monitoring tests

source/client-side-operations-timeout/tests/close-cursors.json
Somehow close-cursors.json was not generated correctly in [DRIVERS-2870](https://jira.mongodb.org/browse/DRIVERS-2870) (https://github.com/mongodb/specifications/pull/1552). 
@rozza Could you confirm the new test is correct?
=> DRIVERS-2870 Regenerate close-cursors.json

source/auth/tests/legacy/connection-string.json, source/auth/tests/legacy/connection-string.yml, source/connection-string/tests/valid-auth.json, source/connection-string/tests/valid-auth.yml, source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-options.yml
Changes to spec tests to close the [DRIVERS-2938](https://jira.mongodb.org/browse/DRIVERS-2938) Remove MONGODB-CR from spec tests
=> DRIVERS-2938: Remove MONGODB-CR from spec tests

source/client-side-encryption/client-side-encryption.md, source/client-side-encryption/tests/README.md
Document "range" as stable. Resolves DRIVERS-2776.
Drivers are expected to document "range" as stable for the upcoming server 8.0 releases. I expect drivers must wait to release until after libmongocrypt 1.11.0 is released (pending [MONGOCRYPT-662](https://jira.mongodb.org/browse/MONGOCRYPT-662)).
---
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~ **N/A. No spec tests changed**
- ~~[ ] Test changes in at least one language driver.~~ **N/A. No tests changed**
clusters, and serverless).~~ **N/A. No tests changed**
=> DRIVERS-2776 document "range" as stable

source/client-side-encryption/etc/test-templates/fle2v2-Compact.yml.template, source/client-side-encryption/etc/test-templates/fle2v2-Rangev2-Compact.yml.template, source/client-side-encryption/tests/legacy/fle2v2-Compact.json, source/client-side-encryption/tests/legacy/fle2v2-Compact.yml, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.json, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.yml
- Assert successful response to `compactStructuredEncryptionData`.
- Add `fle2v2-Rangev2-Compact` to test compact with "range".
Partially resolves DRIVERS-2776.
Spec tests are motivated by the bug fix in [MONGOCRYPT-699](https://jira.mongodb.org/browse/MONGOCRYPT-699).
Adding `result: { ok: 1 }` to the operation is to ensure test runners check the operation succeeded. The [test format](https://github.com/mongodb/specifications/blob/663db4db13c8acf415bb97259bf7f1909b32a670/source/transactions/tests/legacy-test-format.md#test-format) does not require checking the operation succeeded if `result` is not present.
An "insert" operation is added before `compactStructuredEncryptionData` for the range test. [The server check requiring `encryptionInformation`](https://github.com/10gen/mongo/blob/54e …
=> DRIVERS-2776 test compact with "range"

source/server-discovery-and-monitoring/tests/unified/serverMonitoringMode.json, source/server-discovery-and-monitoring/tests/unified/serverMonitoringMode.yml
Fixes DRIVERS-2951.
Question, should we still update the prose test [here](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring-tests.md#monitors-sleep-at-least-minheartbeatfrequencyms-between-checks) added in [DRIVERS-1251](https://jira.mongodb.org/browse/DRIVERS-1251) to run on both streaming and polling? Currently it implicitly tests polling on <4.4 servers.
=> DRIVERS-2951 Test serverMonitoringMode=poll waits after a successful heartbeat

source/client-side-encryption/etc/test-templates/fle2v2-Rangev2-Compact.yml.template, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.json, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.yml
Add `serverless: forbid` to skip range compact test due to [CLOUDP-267864](https://jira.mongodb.org/browse/CLOUDP-267864).
---
- ~~[ ] Update changelog.~~ N/A test changes only.
- ~~[ ] Test changes in at least one language driver.~~ C does not test CSFLE with serverless.
clusters, and serverless).~~ C does not test CSFLE with serverless.
=> DRIVERS-2776 skip serverless in range compact test 

source/server-discovery-and-monitoring/server-discovery-and-monitoring.md, source/server-discovery-and-monitoring/tests/rs/too_old.json, source/server-discovery-and-monitoring/tests/rs/too_old.yml, source/server-discovery-and-monitoring/tests/sharded/too_new.json, source/server-discovery-and-monitoring/tests/sharded/too_new.yml
=> DRIVERS-2250: Define Wire versions for host b in `too_new` and `too_old` tests

source/auth/auth.md, source/auth/tests/mongodb-oidc.md
=> DRIVERS-2960: Clarify Reauthentication and Speculative Authentication combination behavior

.pre-commit-config.yaml, scripts/check_links.py
=> DRIVERS-2789 Add script to check for malformed links

source/index-management/tests/createSearchIndex.json, source/index-management/tests/createSearchIndex.yml, source/index-management/tests/createSearchIndexes.json, source/index-management/tests/createSearchIndexes.yml, source/index-management/tests/searchIndexIgnoresReadWriteConcern.json, source/index-management/tests/searchIndexIgnoresReadWriteConcern.yml
Follow-up to https://github.com/mongodb/specifications/pull/1541
Skip search index tests on server 7.1.
This PR is intended to fix failing tests in the C driver using server version 7.1.0 (latest available on Ubuntu 18.04). An [example failure](https://spruce.mongodb.com/task/mongo_c_driver_gcc75_test_coverage_latest_replica_set_auth_sasl_openssl_fc243b90046371f09d8f50547bf3e7f25846d406_24_08_16_18_18_44/logs?execution=0) logs:
> expected error to contain "Atlas", but got: "BSON field 'createSearchIndexes.indexes.type' is an unknown field."
The "unknown field" error message appears in server 7.1.0, but not 7.0.9 or 7.2.1:
With 7.0.5:
```
% mongosh --eval "print(db.version()); db.runCommand({createSearchIndexes: 'coll', indexes: [{definition: { mappings: { dynamic: true } }, type: 'search' …
```
=> DRIVERS-2768 skip search index tests on 7.1

source/client-side-operations-timeout/tests/README.md
Follow-up to https://github.com/mongodb/specifications/pull/1636. Skip Atlas Serverless on CSOT prose test 11 using `bulkWrite`.
- ~~[ ] Make sure there are generated JSON files from the YAML test files.~~
- ~~[ ] Test changes in at least one language driver.~~
=> DRIVERS-716 skip CSOT `bulkWrite` prose test on serverless

source/client-side-operations-timeout/tests/README.md
Increase the CSOT timeouts for session prose tests. In CI the node driver cannot complete an insertOne within 10ms. (It can normally)
Alignment with: https://github.com/mongodb/specifications/pull/1552
=> DRIVERS-2969: increase CSOT timeouts for session prose tests

source/index-management/index-management.md
https://jira.mongodb.org/browse/DRIVERS-2768
b746fcc71ad7c1b376482852c3c9cbba4eed7d26 incorrectly added the "type" option to IndexOptions instead of SearchIndexOptions. Moreover, that change was made to the RST file after it was converted to Markdown (https://github.com/mongodb/specifications/commit/5c131192922823d034570b13b839df90c51b9ad2) and shortly before it was replaced with a stub pointing to the Markdown file (https://github.com/mongodb/specifications/commit/47c97fb2e72a248a521e00f6d2dc4db8acb29e4a). As a result, the change was entirely lost.
This adds back documentation for the "type" option and also restructures the SearchIndexModel and SearchIndexOptions definitions to be more consistent with IndexModel and IndexOptions. The "name" option is no longer duplicated between both …
=> DRIVERS-2768: Restore missing "type" option docs for search indexes

source/index-management/tests/searchIndexIgnoresReadWriteConcern.json, source/index-management/tests/searchIndexIgnoresReadWriteConcern.yml
The skip was added as part of 8be1189abcc9b879a081f1f606159f3d2578cb27. The skip is not necessary since the test does not specify `SearchIndexOptions.type`.
=> DRIVERS-2768 revert skip of 7.1 to `searchIndexIgnoresReadWriteConcern`

source/client-side-operations-timeout/client-side-operations-timeout.md, source/crud/crud.md, source/crud/tests/README.md
This PR specifies that drivers with explain helpers must provide a mechanism to set timeouts on the explain command.
Node POC: https://github.com/mongodb/node-mongodb-native/pull/4207
- [N/A] Make sure there are generated JSON files from the YAML test files.
=> DRIVERS-1256: specify how drivers set timeouts on explain commands

source/client-side-encryption/tests/README.md
Consolidates the first note and preceding paragraph to state that the test requires MongoDB 8.0+ and libmongocrypt 1.11+.
Removes the second note about MongoDB 7.0, which is no longer relevant.
Notes that the test should not be run on a standalone server, similar to prose test 21.
Additional context for this change can be found in this [Slack thread](https://mongodb.slack.com/archives/C0668RJBA0J/p1726236724878469).
=> Clarify requirements for range explicit encryption prose test

source/server-selection/tests/logging/operation-id.json, source/server-selection/tests/logging/operation-id.yml
=> DRIVERS-2978 Fix `server-selection/tests/logging/operation-id.json:Failed client bulkWrite operation: log messages have operationIds`

source/crud/bulk-write.md
=> DRIVERS-2968 Relax index type requirements in bulk write spec

source/crud/tests/unified/aggregate-write-readPreference.json, source/crud/tests/unified/aggregate-write-readPreference.yml, source/crud/tests/unified/db-aggregate-write-readPreference.json, source/crud/tests/unified/db-aggregate-write-readPreference.yml
This PR fixes errors when running the aggregate-write-readPreference tests on MongoDB 8.0. The error can be avoided by not creating the output collection during test setup. In addition, I removed the outcome assertions as the tests were flaky on sharded clusters; sometimes the query run to validate the outcome would yield no results, while they were available a split-second later. Tests were run using PHP, and I'd like @comandeo-mongo to confirm the changes fix the failures that Ruby is experiencing.
=> DRIVERS-2914: Don't create output collection in aggregate tests

.github/workflows/json-regenerate-check.yml, source/server-discovery-and-monitoring/tests/rs/null_election_id-pre-6.0.json, source/unified-test-format/tests/invalid/runOnRequirement-authMechanism-type.json
This PR aims to fix an issue introduced in #1660. By using `make -B` we can unconditionally make all targets, meaning that file modification times don't come into effect. This should catch issues as the one in #1660, as re-running `make` without modifying the original YAML file did not yield an updated JSON file.
This also resulted in two additional JSON tests being updated with changes introduced a while back.
=> Regenerate all JSON tests

source/crud/bulk-write.md, source/crud/tests/unified/client-bulkWrite-partialResults.json, source/crud/tests/unified/client-bulkWrite-partialResults.yml
=>  DRIVERS-2975 Fix logic for populating `BulkWriteException.partialResult`

source/crud/bulk-write.md
The `collation` field was inadvertently left out of the definition for the `update` operation document. This PR adds it in and clarifies how the `updateMods` field should be populated (see [this thread](https://mongodb.slack.com/archives/C035ZJL6CQN/p1727285353068969)). `collation` is already present in the update/replace write models and is tested in [this spec test](https://github.com/mongodb/specifications/blob/64c1692b8872301e552f04e6532029ac65666861/source/crud/tests/unified/client-bulkWrite-update-options.yml#L110).
=> Fix definition for bulk write update operation

source/client-side-operations-timeout/tests/README.md
This PR restricts CSOT prose test 11 to only run on standalone servers.
Tests passing in Node's implementation: https://spruce.mongodb.com/version/67056335720d470007b68379/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=8.0
[Node's implementation](https://github.com/mongodb/node-mongodb-native/pull/4261) includes the changes in this PR.
=> Specify that CSOT prose test 11 only runs on standalone servers

source/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.json, source/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.yml, source/crud/bulk-write.md, source/crud/tests/README.md, source/crud/tests/unified/client-bulkWrite-errors.json, source/crud/tests/unified/client-bulkWrite-errors.yml
Specify behavior with unacknowledged writes for `MongoClient.bulkWrite`:
- Return error if verbose results are requested.
- Return error if ordered writes are requested.
- Apply `w:0` to each batch.
Existing spec and prose tests using `MongoClient.bulkWrite` with unacknowledged write concern have been updated to use `ordered: false`. The default (`ordered: true`) is now expected to result in a client-side error.
See DRIVERS-2993 for motivation.
This PR expects the OP_MSG moreToCome bit is always set for all batches. This agrees with [OP_MSG](https://github.com/mongodb/specifications/blob/1de6a19410f9f03899676176f53a3c77de234a34/source/message/OP_MSG.md#moretocome-on-requests):
> Clients doing unacknowledged writes MUST set the `moreToCome` flag, and MUST set the writeConcern to `w=0`.
A …
=> DRIVERS-2993 specify behavior of `w:0` with `MongoClient.bulkWrite`

source/mongodb-handshake/handshake.md
DRIVERS-2830 Summary of changes:
- If both a FaaS provider and a container are present, both metadatas must be recorded. 
Python implementation: https://github.com/mongodb/mongo-python-driver/pull/1908.
=> DRIVERS-2830 - Record both FaaS and container metadata when both are present

source/client-side-encryption/client-side-encryption.md
Describe CSFLE/QE server support and naming. No behavior changes are intended.
Motivated by question about QEv1/QEv2 and server support (see [slack](https://mongodb.slack.com/archives/C0668RJBA0J/p1727193366893529)).
---
~~- [ ] Make sure there are generated JSON files from the YAML test files.~~
~~- [ ] Test changes in at least one language driver.~~
~~- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
=> Describe CSFLE/QE server support and naming

source/crud/tests/unified/client-bulkWrite-replaceOne-sort.json, source/crud/tests/unified/client-bulkWrite-replaceOne-sort.yml, source/crud/tests/unified/client-bulkWrite-updateOne-sort.json, source/crud/tests/unified/client-bulkWrite-updateOne-sort.yml
Follow-up to https://github.com/mongodb/specifications/pull/1644. Related to https://github.com/mongodb/specifications/pull/1636 the `bulkWrite` command is not supported on Atlas Serverless.
Verified with Rust driver in [this patch](https://spruce.mongodb.com/version/6718f8b5bcbcbd0007c00ddf) also containing https://github.com/mongodb/specifications/pull/1670.
=> DRIVERS-2822 skip `clientBulkWrite` tests on Serverless

source/transactions/transactions.md
Remove note on future non-primary read preference support.
=> chore(DRIVERS-2730): remove support for non primary read preference

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/json-regenerate-check.yml
Instead of asking us to regenerate files locally when forgotten, it might as well be done directly by the GitHub Action.
Example of commit: https://github.com/mongodb/specifications/commit/7f27d57440da24c28afadea6b143993b17d692f0
=> Commit generated files automatically

source/transactions/transactions.md
This fixes a broken image on the mkdocs / readthedocs build of the Transactions spec.
It's the one remaining place where the specs used an HTML image tag inside Markdown.
The image included some custom CSS style to set the size, which explains why it wasn't converted before: but that style is ignored by GitHub. Both the before and after generate effectively the same HTML on GitHub's viewer.
In mkdocs, this increases the image size to the full width of the page (default) and un-breaks the relative path by allowing mkdocs to add an extra "../" component needed to account for the directory containing each rendered Markdown document as an "index.html".
=> Use Markdown image instead of HTML image, fixes path on mkdocs

source/client-side-encryption/etc/test-templates/fle2v2-Rangev2-Compact.yml.template, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.json, source/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.yml
Reverts mongodb/specifications#1633
=> DRIVERS-2958: Unskip fle2v2-Rangev2-Compact on serverless

source/uri-options/tests/compression-options.json, source/uri-options/tests/compression-options.yml, source/uri-options/tests/concern-options.json, source/uri-options/tests/concern-options.yml, source/uri-options/tests/connection-options.json, source/uri-options/tests/connection-options.yml, source/uri-options/tests/connection-pool-options.json, source/uri-options/tests/connection-pool-options.yml, source/uri-options/tests/proxy-options.json, source/uri-options/tests/proxy-options.yml, source/uri-options/tests/read-preference-options.json, source/uri-options/tests/read-preference-options.yml, source/uri-options/tests/sdam-options.json, source/uri-options/tests/sdam-options.yml, source/uri-options/tests/single-threaded-options.json, source/uri-options/tests/single-threaded-options.yml, source/uri-options/tests/srv-options.json, source/uri-options/tests/srv-options.yml, source/uri-options/tests/tls-options.json, source/uri-options/tests/tls-options.yml
This PR updates URI options tests where the URI is invalid or warnings are expected, and the options are unpredictable. In this case, we use `null` to indicate that the options should not be asserted against.
=> DRIVERS-1368: Use null when options shouldn't be asserted against

source/gridfs/gridfs-spec.md, source/gridfs/tests/delete.json, source/gridfs/tests/delete.yml, source/gridfs/tests/download.json, source/gridfs/tests/download.yml, source/gridfs/tests/downloadByName.json, source/gridfs/tests/downloadByName.yml, source/gridfs/tests/rename.json, source/gridfs/tests/rename.yml
Fix [DRIVERS-3023](https://jira.mongodb.org/browse/DRIVERS-3023)
=> DRIVERS-3023 Add spec tests for GridFS rename and require client errors

source/gridfs/gridfs-spec.md
=> Fix quotes used instead of apostrophes in gridfs spec

source/crud/crud.md
=> DRIVERS-2728: Document query limitations in countDocuments API

source/crud/tests/unified/create-null-ids.json, source/crud/tests/unified/create-null-ids.yml
- ~[ ] Update changelog.~ N/A
Adds tests for null and undefined as `_id` values to check that drivers do not interpret these types as "unset" and generate an ObjectId and overwrite the value.
=> DRIVERS-2124: test that inserts and upserts respect null _id values

source/gridfs/gridfs-spec.md, source/gridfs/tests/deleteByName.json, source/gridfs/tests/deleteByName.yml, source/gridfs/tests/renameByName.json, source/gridfs/tests/renameByName.yml
Fix [DRIVERS-2808](https://jira.mongodb.org/browse/DRIVERS-2808) and [DRIVERS-2807](https://jira.mongodb.org/browse/DRIVERS-2807)
=> DRIVERS-2807 Update GridFS spec to add `delete_by_name` and `rename_by_name`

source/transactions/tests/README.md, source/transactions/transactions.md
Ruby PoC - https://github.com/mongodb/mongo-ruby-driver/pull/2906
=> DRIVERS-1815 Add TransientTransactionError label to PoolClearedError

source/client-side-operations-timeout/tests/runCursorCommand.json, source/client-side-operations-timeout/tests/runCursorCommand.yml
DRIVERS-2953
> The only time a "getMore" can include "maxTimeMS" is for a tailable awaitData cursor. The test bug is masked because the test case expects a timeout on "getMore", preventing the driver from receiving the server error.
=> DRIVERS-2953 getMore should not have maxTimeMS for non-tailable cursor

source/crud/bulk-write.md, source/crud/crud.md, source/crud/tests/unified/bypassDocumentValidation.json, source/crud/tests/unified/bypassDocumentValidation.yml
This effectively reverts #266 and adds tests for the behaviour. I've also decided to remove the rationale for sending `bypassDocumentValidation: true` in the bulk write specification as this difference no longer exists.
The new tests are grouped in a single file to make it easier for drivers to skip this particular test until they've had a chance to make the changes. No other test (aside client bulkWrite which already implements the new behaviour) use `bypassDocumentValidation: false`, so this change should not have any side effects in drivers.
=> DRIVERS-2865: Require drivers to always send out bypassDocumentValidation

source/unified-test-format/tests/valid-pass/operation-empty_array.json, source/unified-test-format/tests/valid-pass/operation-empty_array.yml, source/unified-test-format/unified-test-format.md
https://jira.mongodb.org/browse/DRIVERS-1593
POC: https://github.com/mongodb/mongo-php-library/pull/1513
=> DRIVERS-1593: test.operations array may be empty

source/crud/crud.md, source/crud/tests/unified/distinct-hint.json, source/crud/tests/unified/distinct-hint.yml
[DRIVERS-2658](https://jira.mongodb.org/browse/DRIVERS-2658)
Add a "hint" option for the "distinct" command.
=> DRIVERS-2658 Add hint support for distinct.

source/crud/tests/unified/estimatedDocumentCount.json, source/crud/tests/unified/estimatedDocumentCount.yml, source/retryable-reads/tests/unified/estimatedDocumentCount.json, source/retryable-reads/tests/unified/estimatedDocumentCount.yml, source/unified-test-format/tests/valid-pass/expectedError-isClientError.json, source/unified-test-format/tests/valid-pass/expectedError-isClientError.yml
https://jira.mongodb.org/browse/DRIVERS-1555
POC: https://github.com/mongodb/mongo-php-library/pull/1520
=> DRIVERS-1555: Test that isClientError considers network errors

source/client-side-encryption/client-side-encryption.md
Clarify decryption does not need the key ID or algorithm.
As a drive-by fix, the terms "In-Use Encryption" (the umbrella term) "CSFLE" (the first version) and "QE" (the second version) are applied.
Using "In-Use Encryption", "CSFLE", and "QE" is intended to more closely agree with public documentation. See [Naming](https://github.com/mongodb/specifications/blob/e26b8cdff55ec33c28cc0fbb2b4eeba004093c1e/source/client-side-encryption/client-side-encryption.md#naming).
- ~~[ ] Test changes in at least one language driver.~~
=> DRIVERS-1016 clarify decryption does not need the key ID or algorithm.

source/bson-corpus/tests/datetime.json
Test encoding dates after year 9999 with Relaxed Extended JSON
The extended JSON spec notes:
> | **BSON 1.1 Type or Convention**                                                            | **Canonical Extended JSON Format**                                                                                                                                                                                                                                                                                                                                                                                         | **Relaxed Extended JSON Format**                                                                                                            |
> | …
=> DRIVERS-3011 test relaxed encoding of dates after year 9999

source/client-side-encryption/client-side-encryption.md
This fixes a Markdown rendering error in the client-side-encryption spec due to a typo. The problem was much more noticeable on GitHub than on mkdocs (readthedocs):
* on GitHub, the word was no longer interpreted as math, and it rendered in plain text as "joining$dbName$"
* on mkdocs the math markup rendered normally still, so it appeared as "joiningdbName" with "dbName" in math italics, making the missing space somewhat hard to see
=> fix missing space before inline math

source/unified-test-format/tests/valid-pass/operator-type-number_alias.json, source/unified-test-format/tests/valid-pass/operator-type-number_alias.yml
https://jira.mongodb.org/browse/DRIVERS-2467
POC: https://github.com/mongodb/mongo-php-library/pull/1521
=> DRIVERS-2467: Test $$type operator "number" alias

source/unified-test-format/tests/valid-fail/operator-matchAsDocument.json, source/unified-test-format/tests/valid-fail/operator-matchAsDocument.yml, source/unified-test-format/tests/valid-fail/operator-matchAsRoot.json, source/unified-test-format/tests/valid-fail/operator-matchAsRoot.yml, source/unified-test-format/tests/valid-pass/operator-lte.json, source/unified-test-format/tests/valid-pass/operator-lte.yml, source/unified-test-format/tests/valid-pass/operator-matchAsDocument.json, source/unified-test-format/tests/valid-pass/operator-matchAsDocument.yml, source/unified-test-format/tests/valid-pass/operator-matchAsRoot.json, source/unified-test-format/tests/valid-pass/operator-matchAsRoot.yml
https://jira.mongodb.org/browse/DRIVERS-2573
Note: I implemented `$$matchAsDocument` and `$$matchAsRoot` in PHPLIB in order to POC this, so I'd appreciate it if another language driver could also test this.
=> DRIVERS-2573: Reference test for $$matchAsDocument and $$matchAsRoot

source/crud/bulk-write.md, source/crud/tests/README.md
[Preview](https://github.com/stIncMale/specifications/blob/bulkWriteUpdateSizeValidationRequirements/source/crud/bulk-write.md#size-limits)
DRIVERS-3036
=> DRIVERS-3036 Update the requirements regarding the size validation

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.md, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-returned-connection-maxConnecting.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-returned-connection-maxConnecting.yml
[DRIVERS-2223](https://jira.mongodb.org/browse/DRIVERS-2223)
Don't wait on the remaining checkOut events to resolve a race condition in the "threads blocked by maxConnecting check out returned connections" test caused by different connection pool implementations.
Based on a helpful [comment](https://github.com/mongodb/specifications/pull/1152#issuecomment-1057088946) by @stIncMale from https://github.com/mongodb/specifications/pull/1152.
=> DRIVERS-2223 Fix race condition in pool-checkout-returned-connection-maxConnecting.yml

source/connection-monitoring-and-pooling/tests/cmap-format/pool-create-min-size-error.json, source/connection-monitoring-and-pooling/tests/cmap-format/pool-create-min-size-error.yml, source/server-discovery-and-monitoring/server-discovery-and-monitoring.md, source/server-discovery-and-monitoring/tests/unified/pool-clear-application-error.json, source/server-discovery-and-monitoring/tests/unified/pool-clear-application-error.yml, source/server-discovery-and-monitoring/tests/unified/pool-clear-checkout-error.json, source/server-discovery-and-monitoring/tests/unified/pool-clear-checkout-error.yml, source/server-discovery-and-monitoring/tests/unified/pool-clear-min-pool-size-error.json, source/server-discovery-and-monitoring/tests/unified/pool-clear-min-pool-size-error.yml
Node POC: https://github.com/mongodb/node-mongodb-native/pull/4296
This PR adds tests ensuring that drivers always clear the pool before checking a connection back in / emitting close events, regardless of if the pool cleared error occurs on establishment during minPoolSize population, connection checkout or during operation execution on a checked out connection.
---
This PR originally intended to just add a test that demonstrated that, when we encounter a pool clear error on an application connection, we clear the pool before checking the connection back into the pool.  This avoids a small race condition between SDAM and connection checkout for subsequent requests in the pool - the subsequent requests might check out the errored connection before the pool is cleared.
As I was looking …
=> DRIVERS-1785: clarify ordering of CMAP events when pool is cleared

source/server-discovery-and-monitoring/tests/unified/logging-replicaset.json, source/server-discovery-and-monitoring/tests/unified/logging-replicaset.yml, source/server-discovery-and-monitoring/tests/unified/logging-sharded.json, source/server-discovery-and-monitoring/tests/unified/logging-sharded.yml, source/server-discovery-and-monitoring/tests/unified/logging-standalone.json, source/server-discovery-and-monitoring/tests/unified/logging-standalone.yml
DRIVERS-3033 SDAM logging tests should allow durationMS as a float
See details in the ticket.
=> DRIVERS-3033 SDAM logging tests should allow durationMS as a float

source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.md
The relevant Slack discussion: https://mongodb.slack.com/archives/C72LB5RPV/p1732060999166209.
DRIVERS-3056
=> Relax the WaitQueue fairness requirement in the CMAP spec

source/client-side-encryption/client-side-encryption.md, source/client-side-encryption/etc/test-templates/keyCache.yml.template, source/client-side-encryption/tests/legacy/keyCache.json, source/client-side-encryption/tests/legacy/keyCache.yml, source/client-side-encryption/tests/unified/keyCache.json, source/client-side-encryption/tests/unified/keyCache.yml
Follow-up to https://github.com/mongodb/specifications/pull/1730
- Increase `wait` time in `keyCache.json` tests to fix failures on Windows.
- Document `keyExpirationMS=0` means "never expire".
See https://github.com/mongodb/mongo-c-driver/pull/1804 for motivation.
---
clusters, and ~~serverless~~).~~ **Verified by this [patch build](https://spruce.mongodb.com/version/675066dec4dc3c0006a3e9b3). But C does not test serverless.**
=> DRIVERS-2781 increase `wait` time.

.github/workflows/json-regenerate-check.yml
The `Check if all JSON test files are up-to-date` job runs on `ubuntu-latest` and Github has [announced](https://github.com/actions/runner-images/issues/10636) that Ubuntu 24.04 is being rolled out as the default version for the "ubuntu-latest" label in GitHub Actions. Now the latest python version supported on Ubuntu 24.04 is 3.9.* but we are using 3.7 which currently breaks the setup-python action. This PR bumps the version to the lowest supported version on Ubuntu 24.04
=> Bump python version for setup-python action

source/transactions/tests/unified/findOneAndReplace.json, source/transactions/tests/unified/findOneAndReplace.yml, source/transactions/tests/unified/findOneAndUpdate.json, source/transactions/tests/unified/findOneAndUpdate.yml, source/transactions/tests/unified/mongos-recovery-token.json, source/transactions/tests/unified/mongos-recovery-token.yml, source/transactions/tests/unified/pin-mongos.json, source/transactions/tests/unified/pin-mongos.yml, source/transactions/tests/unified/write-concern.json, source/transactions/tests/unified/write-concern.yml
While migrating to unified spec format for transactions tests in CSHARP Driver I've run into 2 minor problems which I suggest to fix by this PR (please let me know if the changes makes sense and I'll create an appropriate ticket):
1) CSharp Driver does not write default values for optional fields, that's why we should make 'new' field of `findOneAndModify` command optional (`{ $$unsetOrMatches: false }`)
2) When there is a failPoint set on `hello` command, I suggest to use appName to let other connection work (we use additional client to setup and tire down the failpoints).
=> DRIVERS-3081: Relax requirement for optional fields and introducing appName for failPoints for transactions unified tests

source/client-side-operations-timeout/tests/README.md
DRIVERS-3039 Remove outdated CSOT test
This test is outdated because we removed the non-consecutive socket timeout tracking behavior in DRIVERS-1807.
=> DRIVERS-3039 Remove outdated CSOT test

source/command-logging-and-monitoring/command-logging-and-monitoring.md, source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.md, source/server-discovery-and-monitoring/server-discovery-and-monitoring-logging-and-monitoring.md
Update spec text to match the tested types for logging `durationMS`.
Tests for logging durationMS permit BSON Int32/Int64/Double. [Example](https://github.com/mongodb/specifications/blob/60fe09fc17a1963d683e904eb8b43f6675d77a1a/source/command-logging-and-monitoring/tests/logging/command.yml#L95):
```yaml
durationMS: { $$type: [double, int, long] }
```
Related: DRIVERS-3033 added support for `double`.
- ~~[ ] Test changes in at least one language driver.~~ No test changes.
clusters, and serverless).~~ No test changes.
=> DRIVERS-3089 document durationMS in logs may be Int32/Int64/Double

source/load-balancers/tests/non-lb-connection-establishment.json, source/load-balancers/tests/non-lb-connection-establishment.yml
Skip the test `operations against non-load balanced clusters fail if URI contains loadBalanced=true` on >= 8.1. See DRIVERS-3108 for motivation.
Tested in the C driver in [this patch](https://spruce.mongodb.com/version/67b4ad051cd3dc00077ea2ab). Patch also applies https://github.com/mongodb-labs/drivers-evergreen-tools/pull/607 to test unreleased 8.1 servers. The failure on macOS appears to be a separate issue.
---
- ~~[ ] Update changelog.~~ **Test changes only**
=> DRIVERS-3108 skip non-LB test on >=8.1 server

source/change-streams/change-streams.md
Specifications typically use `Optional<...>` instead of `| null` to indicate that a field is only present in some circumstances because drivers represent conditionally present values differently.  While some drivers might use `null` to indicate that a value isn't present, other drivers (like Node) omit keys entirely.  
The changes in this PR make `nsInfo` consistent with other optional fields (ex: `to` or `operationDescription`).
=> Make `nsType` optional in ChangeStreamDocument

source/connection-string/tests/valid-options.json, source/connection-string/tests/valid-options.yml, source/connection-string/tests/valid-warnings.json, source/connection-string/tests/valid-warnings.yml
Tested in https://github.com/mongodb/mongo-rust-driver/pull/1315.
I didn't file a separate ticket for this as I don't expect other drivers will need to sync these tests. Added an "ENVIRONMENT" entry to a few tests that were failing in the Rust driver due to enforcement of the rule listed [here](https://github.com/mongodb/specifications/blob/master/source/auth/auth.md#mongocredential-properties-6) regarding the combination of "ENVIRONMENT" and "TOKEN_RESOURCE".
=> DRIVERS-2915 Add ENVIRONMENT auth mechanism property to test URIs

source/client-side-encryption/etc/data/lookup/key-doc.json, source/client-side-encryption/etc/data/lookup/schema-csfle.json, source/client-side-encryption/etc/data/lookup/schema-csfle2.json, source/client-side-encryption/etc/data/lookup/schema-qe.json, source/client-side-encryption/etc/data/lookup/schema-qe2.json, source/client-side-encryption/tests/README.md
Add prose test for `$lookup` support in QE/CSFLE.
Tests were run in the C driver in [this patch](https://spruce.mongodb.com/version/67b1feac78623900074b9ef8). Note: `latest` tasks were updated to use `latest-build` to use unreleased 8.1 builds (see [slack](https://mongodb.slack.com/archives/C72LB5RPV/p1739884710850709) for background).
Testing requires a unreleased version of libmongocrypt to include changes from [MONGOCRYPT-723](https://jira.mongodb.org/browse/MONGOCRYPT-723). Binaries are available on [this patch build](https://spruce.mongodb.com/task/libmongocrypt_publish_upload_all_patch_c3dff011c9c0dc326c31414471a4b613e0d91365_67af62d2eff4dc0007490c8f_25_02_14_15_35_47/files?execution=0) or by building from source at https://github.com/mongodb/libmongocrypt/commit/33fdf65cce5a0c0cdd29 …
=> DRIVERS-3082 add prose tests for `$lookup`

source/server-selection/server-selection.md
Refer: DRIVERS-2929
These changes are not behavioral. They only require that a warning is issued for users in case they make use of a driver's hedged-reads APIs, as well as documentation updates. ([Example commit][cdriver])
[cdriver]: https://github.com/mongodb/mongo-c-driver/commit/4cc8a974f750ebad14c0daba076423385029514e
clusters, and serverless).~~ (No behavioral changes)
=> [DRIVERS-2929] Note the deprecation of hedged reads, require a warning

source/sessions/driver-sessions.md, source/sessions/tests/README.md
=> DRIVERS-2798 Drivers do not gossip $clusterTime on SDAM commands

source/load-balancers/tests/non-lb-connection-establishment.json, source/load-balancers/tests/non-lb-connection-establishment.yml
Revert test skip from https://github.com/mongodb/specifications/pull/1758
Verified with [this C driver patch build](https://spruce.mongodb.com/version/67c890930593660007b45fe7) testing latest server builds. The macOS failure is likely caused by [SERVER-101020](https://jira.mongodb.org/browse/SERVER-101020)
https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5 added a temporary test skip to workaround SERVER-101078. With SERVER-101078 fixed, this skip is removed.
- ~~[ ] Update changelog.~~ (N/A).
clusters, and serverless).~~ (C does not test serverless)
=> DRIVERS-3109 Revert skip to non-lb-connection-establishment

source/server-discovery-and-monitoring/tests/rs/secondary_ipv6_literal.json, source/server-discovery-and-monitoring/tests/rs/secondary_ipv6_literal.yml
Add regression test for the bug identified in [this comment of HELP-68823](https://jira.mongodb.org/browse/HELP-68823?focusedCommentId=7116340&focusedId=7116340&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-7116340).
Test is added to spec repo to validate other drivers handle IPv6 literals correctly. The tested scenario is:
- Connect with: `mongodb://[::1]:27017/?replicaSet=rs`
- Server responds as a secondary (putting the driver's topology state in `ReplicaSetNoPrimary`) and a `"me":"[::1]:27017`.
- Expect the server to be present. The bug from [HELP-68823](https://jira.mongodb.org/browse/HELP-68823) triggered the server to be (unexpectedly) removed from the topology due to the [mismatched `me` check](https://github.com/mongodb/specifications/blob/f04df7d …
=> DRIVERS-3128 test secondary with IPv6 literal in SDAM

source/auth/auth.md, source/auth/tests/mongodb-aws.md, source/client-side-encryption/client-side-encryption.md, source/client-side-encryption/tests/README.md
Adds section to auth spec and CSFLE spec on allowing user provided custom credential providers for AWS and notes on testing.
Node implementation: https://github.com/mongodb/node-mongodb-native/pull/4373
=> feat(DRIVERS-2903): use custom aws configuration

source/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.json, source/command-logging-and-monitoring/tests/monitoring/unacknowledged-client-bulkWrite.yml
https://jira.mongodb.org/browse/DRIVERS-3139
This makes the assertion consistent with collection bulkWrites by allowing for an entirely optional result and conditionally checking acknowledged=false.
=> DRIVERS-3139: Revise assertion for unacknowledged client bulkWrite result

source/sessions/tests/driver-sessions-dirty-session-errors.json, source/sessions/tests/driver-sessions-dirty-session-errors.yml
=> DRIVERS-3143: Relax requirement for optional fields for sessions unified tests

source/unified-test-format/unified-test-format.md
This was missed in a8a7d01036615dc6122ad16a854834453b25e6f8.
Intentionally omitting the changelog entry, as the option was already documented in the entry for schema version 1.9.
=> Document timeoutMS in collectionOrDatabaseOptions

source/client-side-operations-timeout/tests/waitQueueTimeout.json, source/client-side-operations-timeout/tests/waitQueueTimeout.yml
DRIVERS-3130 Test wait queue timeout errors do not clear the pool
- Answer: There's already a test for waitQueueTimeoutMS here: https://github.com/mongodb/specifications/blob/fe86082/source/connection-monitoring-and-pooling/tests/cmap-format/wait-queue-timeout.yml
=> DRIVERS-3130 Test wait queue timeout errors do not clear the pool

source/client-side-encryption/tests/legacy/fle2v2-BypassQueryAnalysis.json, source/client-side-encryption/tests/legacy/fle2v2-BypassQueryAnalysis.yml, source/client-side-encryption/tests/legacy/fle2v2-EncryptedFields-vs-EncryptedFieldsMap.json, source/client-side-encryption/tests/legacy/fle2v2-EncryptedFields-vs-EncryptedFieldsMap.yml, source/client-side-encryption/tests/legacy/localSchema.json, source/client-side-encryption/tests/legacy/localSchema.yml, source/client-side-encryption/tests/legacy/maxWireVersion.json, source/client-side-encryption/tests/legacy/maxWireVersion.yml
Restore legacy tests removed in https://github.com/mongodb/specifications/pull/1756
Failing lint task (on mdformat) appears unrelated and is failing in master.
Some drivers now use a git submodule to sync spec tests (example: [PHP](https://github.com/mongodb/mongo-php-library/tree/a4ccccd9011bad978e6f0d52efd1a512ef64d35a/tests)). As a result, when they update the submodule, all tests get synced. This PR restores the .json/.yml files (not templates) for the legacy tests. Once all drivers have synced the new tests migrated for DRIVERS-2295, the old tests can be removed. Filed DRIVERS-3178 to track removing the tests.
This is intended to prevent a loss of test coverage (e.g. driver upgrades submodule to get non-CSFLE test updates, but does not-yet have the test runner changes implemented to …
=> DRIVERS-3106 restore legacy CSFLE tests

source/crud/tests/unified/client-bulkWrite-replaceOne-sort.json, source/crud/tests/unified/client-bulkWrite-replaceOne-sort.yml
The suite name says updateOne but the test is for replaceOne
=> chore: fix client bulkWrite replaceOne-sort suite name

source/client-side-encryption/tests/README.md
Update Client-Side Encryption prose test `7. Custom Endpoint Test` to fix recently seen timeout failures:
- Update case 4 to use `localhost` instead of AWS.
- Use `.invalid` instead of `.local` for test URIs intended to be invalid.
Tested in C driver: https://github.com/mongodb/mongo-c-driver/pull/2001
Drivers have seen recent test failures due to timeout. [Node](https://spruce.mongodb.com/task/mongo_node_driver_next_rhel80_large_Node22_test_rapid_sharded_cluster_82303f3de52ac623bd558ec78f72d7180182e793_25_04_23_18_56_15/tests?execution=0&sortBy=STATUS&sortDir=ASC) indicates failure in Client-Side Encryption prose test: `7. Custom Endpoint Test` case 4. Drivers are expected to connect to a KMS using the endpoint string from [mongocrypt_kms_ctx_endpoint](https://github.com/mongodb/libmongoc …
=> DRIVERS-3181 fix timeouts in CSE custom endpoint test

source/unified-test-format/tests/Makefile
This PR does not check any specifications or test files, but it completely revamps the makefile used to test specifications. The change was prompted by me realising that not all folders were properly checked. As a result, I changed the following:
- Introduced separate targets for each folder containing test files. This creates multiple targets in specifications like the unified test format, e.g. `unified-test-format/invalid` and `unified-test-format/valid-pass`. In those cases, I also added a compound target, e.g. `unified-test-format`, that runs all individual targets
- Sorted target names alphabetically
The following specifications didn't have their test files checked previously:
- auth
- connection-monitoring-and-pooling
- index-management
- run-command
- …
=> Check all unified tests in UTF makefile

.pre-commit-config.yaml
Updates markdown link check to 3.13.7 to fix dead link failures.
=> fix: markdown link check

README.md
Updating the README with automated test best practices that support cross-drivers submodule approach to automated test syncs.
- [N/A] Update changelog.
- [N/A] Test changes in at least one language driver.
- [N/A] Test these changes against all server versions and topologies (including standalone, replica set, sharded
=> Add automated test best practice guidelines

source/auth/tests/mongodb-oidc.md
=> Add a prose test for OIDC reauthentication when a session is involved

source/client-side-encryption/tests/README.md, source/extended-json/extended-json.md, source/retryable-writes/retryable-writes.md, source/server-discovery-and-monitoring/server-discovery-and-monitoring.md, source/server-discovery-and-monitoring/server-monitoring.md, source/transactions-convenient-api/transactions-convenient-api.md, source/transactions/tests/legacy-test-format.md, source/unified-test-format/unified-test-format.md
Working on #1807 I noticed a number of errors with pre-commit that are already present in master. This PR fixes those errors.
=> Fix pre-commit linter errors

.github/PULL_REQUEST_TEMPLATE.md, source/serverless-testing/README.md, source/unified-test-format/unified-test-format.md
This PR marks the serverless testing spec as obsolete and deprecates the `serverless` runOnRequirement in the unified test format. No tests have been modified as part of this PR as we want to preserve existing test behaviour until all drivers have disabled serverless testing.
=> DRIVERS-3115: Remove serverless testing requirements

source/client-side-encryption/tests/unified/localSchema.json, source/client-side-encryption/tests/unified/localSchema.yml
Use `errorContains` for assertion in test: `A local schema with no encryption is an error`.
https://github.com/mongodb/specifications/issues/1756 migrated `errorContains` (in [legacy](https://github.com/mongodb/specifications/blob/668992950d975d3163e538849dd20383a214fc37/source/client-side-encryption/tests/legacy/localSchema.yml#L64-L65)) to `isClientError` (in [unified](https://github.com/mongodb/specifications/blob/668992950d975d3163e538849dd20383a214fc37/source/client-side-encryption/tests/unified/localSchema.yml#L102)). I expect this may have been copied from other unified tests. `isClientError` triggered a [test failure in Node](https://mongodb.slack.com/archives/C0668RJBA0J/p1752600616931609?thread_ts=1752528282.188439&cid=C0668RJBA0J).
`A local schema with no encryption is an …
=> DRIVERS-3106 revise expected error

source/unified-test-format/tests/valid-pass/poc-queryable-encryption.json, source/unified-test-format/tests/valid-pass/poc-queryable-encryption.yml
This PR updates the poc-queryable-encryption unified tests not to run on standalone servers, because QE is not supported on standalone servers.
clusters).
=> DRIVERS-3106: don't run QE unified tests on standalone servers

source/bson-binary-vector/tests/README.md
Follow-up to https://github.com/mongodb/specifications/pull/1812. Applies pending suggestions from [review](https://github.com/mongodb/specifications/pull/1812#pullrequestreview-2971930645):
- Allow drivers to skip the comparison test if the `Vector` type does not support comparison. The C driver's [bson_vector_packed_bit_view_t](https://mongoc.org/libbson/current/bson_vector_packed_bit_view_t.html) does not support comparison.
- Do not use `Binary.from_vector` in test example with non-zero ignored bits. PyMongo 4.14.0-dev raises an exception:
```
>>> b2 = Binary.from_vector([0b11111111], BinaryVectorDtype.PACKED_BIT, padding=7)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/kevin.albertson/code/mongo-python-driver/bson/binary.py", line 482, in …
```
=> DRIVERS-3123 add test skip and clarification

source/faas-automated-testing/faas-automated-testing.md
=> DRIVERS-3250 Add information on obtaining secrets for faas testing

source/client-side-operations-timeout/tests/tailable-awaitData.json, source/client-side-operations-timeout/tests/tailable-awaitData.yml
DRIVERS-3092
Ensure drivers are short-circuiting socket timeouts by validating if maxAwaitTimeMS < operational timeout for tailable awaitData cursors.
clusters).
=> DRIVERS-3092 Check for timeout in tailable-awaitData unified spec tests

source/client-side-encryption/tests/unified/localSchema.json, source/client-side-encryption/tests/unified/localSchema.yml
The current localSchema.json spec test uses empty UUIDs which causes test failures for the C# driver. This PR updates the test data to use non-empty UUIDs.
In C#, UUIDs are represented as GUIDs (value types/structs) with a default value of an empty UUID (00000000-0000-0000-0000-000000000000). Following standard C# conventions, an empty UUID indicates an uninitialized GUID. Therefore, the C# driver correctly treats empty UUID IDs as "not-set" and automatically generates new IDs during insert operations, which is the expected behavior for the language.
After evaluation, we've decided to maintain the C# driver's current behavior as it aligns with C# language conventions. This behavior will be documented in our driver documentation to ensure users are aware of this UUID handling.
We could …
=> DRIVERS-3106: Replace empty UUIDs in localSchema.json spec test

source/client-side-encryption/tests/README.md
Document expected server error codes in prose test for CSFLE/QE bulkWrite prose test expecting a "too-large document" error.
[SERVER-104405](https://jira.mongodb.org/browse/SERVER-104405) recently changed the expected error code. This broke some drivers testing of [BSON Size Limits and Batch Splitting](https://github.com/mongodb/specifications/blob/49ade88e52ddfa6cee7fa0de286e5f8b0d62dcd0/source/client-side-encryption/tests/README.md#4-bson-size-limits-and-batch-splitting). Document the expected server errors in the specification.
Checking server error codes is not made into a requirement. `MongoCollection.bulkWrite` does not prohibit client-side checks after auto-encryption. The expected error might be a driver-side or server-side error.
--- …
=> DRIVERS-3279 clarify expected server errors in CSE prose test 4

source/auth/auth.md, source/auth/tests/mongodb-aws.md, source/client-side-encryption/tests/README.md
Updates the AWS auth spec to require drivers that implement custom AWS credential providers to use the custom provider before any other method.
Updates test wording to include the extra scenario for testing a custom provider when explicit credentials are also provided.
Node implementation: https://github.com/mongodb/node-mongodb-native/pull/4656
clusters).
=> DRIVERS-3207: Custom AWS credential providers execute earlier
